import {createHash,randomUUID} from 'node:crypto';
export const ACCESS_LEVELS=Object.freeze([{id:'training',label:'Treino',features:{training:true,nutrition:false}},{id:'training-nutrition',label:'Treino e Nutrição',features:{training:true,nutrition:true}}]);
const marker=createHash('sha256').update('sim-access-grants-v1').digest('hex');
export function accessPolicy({store,now,deny,audit}){
 async function state(row){const records=await store.all('SELECT actor_id,result FROM operations WHERE request_hash=? AND operation_key LIKE ?',marker,'access-grant-'+row.id+'-%');let grants;try{grants=records.map(r=>({...JSON.parse(r.result),issuedBy:r.actor_id})).filter(g=>g.orgId===row.org_id&&g.studentId===row.id).sort((a,b)=>b.sequence-a.sequence);}catch{deny(503,'Autorização de acesso indisponível.');}const g=grants[0];if(!g)return {mode:'legacy-existing',active:true,sequence:0,level:null,expiresAt:null,features:{training:true,nutrition:true}};const level=ACCESS_LEVELS.find(l=>l.id===g.level);return {...g,mode:'manual',active:!!level&&g.enabled===true&&g.email===row.email&&(g.expiresAt===null||g.expiresAt>now()),features:level?.features||{training:false,nutrition:false}};}
 function validate(level,expiresAt,allowExpired=false){if(!ACCESS_LEVELS.some(l=>l.id===level)||expiresAt!==null&&(!Number.isSafeInteger(expiresAt)||expiresAt<=0||!allowExpired&&expiresAt<=now()))deny(400,'Selecione um nível permitido e vencimento futuro, ou deixe sem vencimento.');}
 async function grantLocked(actor,row,{level,expiresAt,enabled=true,sequence}){if(actor.role!=='admin'||actor.org_id!==row.org_id)deny(403,'Acesso manual exige administrador da organização.');validate(level,expiresAt,enabled===false);if(typeof enabled!=='boolean')deny(400,'Estado de acesso inválido.');const old=await state(row);if(sequence!==undefined&&sequence!==old.sequence)deny(409,'Autorização mudou. Recarregue.');const value={studentId:row.id,orgId:row.org_id,email:row.email,level,expiresAt,enabled,sequence:old.sequence+1,source:'manual',createdAt:now()};await store.run('INSERT INTO operations VALUES (?,?,?,?,?)',actor.id,'access-grant-'+row.id+'-'+randomUUID(),marker,200,JSON.stringify(value));await audit(actor,row.id,'access.manual.'+(enabled?'authorized':'paused')+':'+value.sequence);return {...value,issuedBy:actor.id};}
 async function assertActive(row,feature){const s=await state(row);if(!s.active||feature&&s.features[feature]!==true)deny(403,'Este acesso não está liberado. Procure o responsável pelo seu acompanhamento.');return s;}
 async function userSummary(actor){if(actor.role!=='student')return undefined;const row=await store.get('SELECT * FROM students WHERE user_id=? AND org_id=?',actor.id,actor.org_id);if(!row)return {active:false,features:{training:false,nutrition:false}};const s=await state(row);return {active:s.active,mode:s.mode,level:s.level,expiresAt:s.expiresAt,features:s.features};}
 return {state,validate,grantLocked,assertActive,userSummary};
}
