import {randomUUID,createHash} from 'node:crypto';
import {demoMedia} from './analysis-demo-media.mjs';
import {DEMO_STUDENT,demoFacts,demoMethod,demoTraining,demoNutrition,DEMO_FOODS,DEMO_TARGETS} from './analysis-demo-data.mjs';
import {responsesProposalAdapter,trainingProposalSchemaFor,validateSchema} from './proposal-responses.mjs';
import {proposalSpecs} from './proposal-specs.mjs';
import {nutritionAnalysisAdapter,validateDemoNutrition} from './analysis-demo-nutrition.mjs';
const hash=value=>createHash('sha256').update(JSON.stringify(value)).digest('hex');
const reply=payload=>new Response(JSON.stringify({status:'completed',usage:{output_tokens:100},output:[{type:'message',role:'assistant',status:'completed',content:[{type:'output_text',text:JSON.stringify(payload)}]}]}));
export function createAnalysisDemo({enabled=false,security,videoDirectory}={}){
 const active=enabled===true&&!security?.production;const media=active?demoMedia(videoDirectory):null;
 const state={execution:{},revision:1,intakeRevision:1,facts:demoFacts(),training:null,nutrition:null,choices:[],trainingHistory:[],nutritionHistory:[]};
 const method=()=>demoMethod(media?.catalog||[]);
 const training=responsesProposalAdapter({apiKey:'synthetic-no-credential',model:'offline-analysis-training',mockOnly:true,fetchImpl:async(_url,request)=>reply(demoTraining(JSON.parse(JSON.parse(request.body).input)))});
 const nutrition=nutritionAnalysisAdapter({enabled:true,apiKey:'synthetic-no-credential',model:'offline-analysis-nutrition',mockOnly:true,fetchImpl:async()=>reply(demoNutrition())});
 const validateTraining=payload=>{const input={kind:'training',untrustedFacts:state.facts,untrustedMethod:method()};validateSchema(payload,trainingProposalSchemaFor(input));return proposalSpecs({configuration:{mode:'local-simulation',methodology:method()},deny:(_status,message)=>{throw Error(message);},exact:(value,keys)=>{if(!value||Object.keys(value).sort().join()!==keys.sort().join())throw Error('Invalid fields');},text:(v,min,max)=>{if(typeof v!=='string'||v.trim().length<min||v.length>max)throw Error('Invalid text');return v.trim();}}).training.validate(payload,{facts:state.facts});};
 const snapshot=()=>({demo:true,syntheticOnly:true,student:DEMO_STUDENT,revision:state.revision,intakeRevision:state.intakeRevision,originalIntake:demoFacts(),facts:state.facts,execution:state.execution,training:state.training,nutrition:state.nutrition,nutritionView:state.nutrition?validateDemoNutrition(state.nutrition.payload,state.facts,state.choices):null,history:{training:state.trainingHistory,nutrition:state.nutritionHistory},catalog:media?.catalog||[],mediaAvailable:media?.available||false,indexHash:media?.indexHash||null,foods:DEMO_FOODS,targets:DEMO_TARGETS,providers:{training:training.kind,nutrition:nutrition.kind,transport:'fake-test',realTrainingGate:false,realNutritionGate:false,externalCalls:0},clinicalApproval:false,published:false});
 async function read(req){let size=0;const chunks=[];for await(const chunk of req){size+=chunk.length;if(size>65536)throw Error('Body too large');chunks.push(chunk);}return JSON.parse(Buffer.concat(chunks).toString('utf8'));}
 const send=(res,status,data)=>{res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(data));};
 return {enabled:active,snapshot,async handle(req,res,pathname){
  if(!pathname.startsWith('/api/demo/analysis'))return false;
  if(!active){send(res,404,{error:'Demonstração desativada.'});return true;}
  const video=/^\/api\/demo\/analysis\/videos\/([a-f0-9-]{36})$/.exec(pathname);
  if(video&&['GET','HEAD'].includes(req.method)){media.serve(req,res,video[1]);return true;}
  if(pathname==='/api/demo/analysis'&&req.method==='GET'){send(res,200,snapshot());return true;}
  const actions={'/api/demo/analysis/training/execution':'PUT','/api/demo/analysis/intake':'PUT','/api/demo/analysis/training/generate':'POST','/api/demo/analysis/training/edit':'PUT','/api/demo/analysis/nutrition/generate':'POST','/api/demo/analysis/nutrition/edit':'PUT','/api/demo/analysis/nutrition/choices':'PUT'};
  if(actions[pathname]!==req.method){send(res,404,{error:'Ação demonstrativa inexistente.'});return true;}
  try{const body=await read(req),expected=state.revision;const fields=pathname.endsWith('/execution')?['revision','sessionId','exerciseId','completedSets']:pathname.endsWith('/intake')?['revision','days']:pathname.endsWith('/edit')?['revision','payload']:pathname.endsWith('/choices')?['revision','choices']:['revision'];if(Object.keys(body).sort().join()!==fields.sort().join())throw Error('Campos demonstrativos inválidos.');if(body.revision!==expected){send(res,409,{error:'A versão mudou. Recarregue.'});return true;}
   if(pathname.endsWith('/intake')){if(![2,3,4].includes(body.days))throw Error('Use dois, três ou quatro dias fictícios.');state.facts=demoFacts(body.days);state.intakeRevision++;state.execution={};state.training=null;state.nutrition=null;state.choices=[];}
   else if(pathname.endsWith('/execution')){const e=state.training?.content.sessions.find(s=>s.id===body.sessionId)?.exercises.find(e=>e.exerciseId===body.exerciseId);if(!e||!Number.isInteger(body.completedSets)||body.completedSets<0||body.completedSets>e.sets)throw Error('Invalid demo execution');state.execution[body.sessionId+':'+body.exerciseId]=body.completedSets;}
   else if(pathname.includes('/training/')){if(!media.available)throw Error('Subconjunto exato de vídeos indisponível; nenhuma associação inventada.');const raw=pathname.endsWith('/generate')?await training.generate({kind:'training',untrustedFacts:state.facts,untrustedMethod:method()}):body.payload;if(state.revision!==expected){send(res,409,{error:'Contexto mudou durante geração simulada.'});return true;}const validated=validateTraining(raw),payload=proposalSpecs({}).training.editable(validated);const version={id:randomUUID(),revision:state.trainingHistory.length+1,intakeRevision:state.intakeRevision,payload,content:validated,state:'draft',syntheticOnly:true,clinicalApproval:false,origin:pathname.endsWith('/generate')?'responses-mock':'human-demo-edit',sha256:hash(payload)};state.execution={};state.training=version;state.trainingHistory.push(version);}
   else if(pathname.endsWith('/choices')){if(!state.nutrition)throw Error('Gere primeiro o cardápio fictício.');validateDemoNutrition(state.nutrition.payload,state.facts,body.choices);state.choices=body.choices;}
   else{const payload=pathname.endsWith('/generate')?await nutrition.generate({kind:'nutrition',untrustedFacts:state.facts,untrustedMethod:{version:'fixture-nutrition-v1',foods:DEMO_FOODS,targets:DEMO_TARGETS}}):body.payload;if(state.revision!==expected){send(res,409,{error:'Contexto mudou durante geração simulada.'});return true;}validateDemoNutrition(payload,state.facts);const version={id:randomUUID(),revision:state.nutritionHistory.length+1,intakeRevision:state.intakeRevision,payload,state:'draft',syntheticOnly:true,clinicalApproval:false,origin:pathname.endsWith('/generate')?'responses-mock':'human-demo-edit',sha256:hash(payload)};state.nutrition=version;state.nutritionHistory.push(version);state.choices=[];}
   state.revision++;send(res,200,snapshot());
  }catch{send(res,400,{error:'Dados demonstrativos inválidos ou recurso indisponível. Confira IDs, porções, referências e revisões.'});}return true;
 }};
}
