import {INTAKE_VERSION,CONSENT_VERSION,validateIntake,attentionReview} from '../public/sim/intake-fields.js';
export function anamnesisFlow({store,now,deny,exact,read,mutation,student,audit,changed,start}){
 async function state(id,org){const a=await store.get('SELECT * FROM anamneses WHERE student_id=? AND org_id=?',id,org);return {version:INTAKE_VERSION,revision:a?.revision||0,complete:!!a&&a.version===INTAKE_VERSION&&a.status==='complete'&&a.training_consent===1,reviewPending:!a||a.reviewed_revision!==a.revision,attentionReview:!!a?.attention_review,consents:{training:a?.training_consent===1,nutrition:a?.nutrition_consent===1},consentVersion:a?.consent_version||CONSENT_VERSION,completedAt:a?.completed_at||null,reviewedBy:a?.reviewed_by||null,reviewedRevision:a?.reviewed_revision??null,adminAccessAuthorized:a?.training_consent===1&&a?.consent_version===CONSENT_VERSION};}
 async function handle(actor,req,route){const m=/^\/api\/local\/students\/([a-f0-9-]{36})\/anamnesis(\/(complete|review))?$/.exec(route);if(!m)return null;const row=await student(actor,m[1]),id=row.id;const current=()=>store.get('SELECT * FROM anamneses WHERE student_id=? AND org_id=?',id,actor.org_id);
  if(req.method==='GET'&&!m[2]){const a=await current(),meta=await state(id,actor.org_id);let answers;if(actor.role==='student')answers=JSON.parse(a?.answers||'{}');else if(actor.role==='admin'&&a?.training_consent===1&&a?.consent_version===CONSENT_VERSION){answers=JSON.parse(a.answers);await audit(actor,id,'anamnesis.admin.read:'+a.revision);}else if(actor.role==='coach'&&a?.training_consent===1)answers=JSON.parse(a.answers);else if(actor.role==='nutrition'&&a?.training_consent===1&&a?.nutrition_consent===1){const credential=await store.get('SELECT verified FROM nutrition_credentials WHERE user_id=? AND org_id=?',actor.id,actor.org_id);if(credential?.verified===1){const all=JSON.parse(a.answers);answers=Object.fromEntries(['current_diet','injuries','fractures','restrictions'].filter(k=>k in all).map(k=>[k,all[k]]));}}return {status:200,data:{anamnesis:{...meta,...(answers?{answers}:{})}}};}
  if(req.method==='PUT'&&!m[2]){if(actor.role!=='student')deny(403,'Respostas e autorizações pertencem ao aluno.');const b=await read(req);exact(b,['version','revision','answers','consents','consentVersion']);if(b.version!==INTAKE_VERSION||!Number.isInteger(b.revision))deny(400,'Versão ou revisão inválida.');exact(b.consents,['training','nutrition']);if(typeof b.consents.training!=='boolean'||typeof b.consents.nutrition!=='boolean'||b.consents.nutrition&&!b.consents.training)deny(400,'Autorizações inválidas.');if(b.consents.training&&b.consentVersion!==CONSENT_VERSION)deny(409,'Recarregue e confirme as finalidades atuais, incluindo a supervisão administrativa.');let answers;try{answers=validateIntake(b.answers);}catch(e){deny(400,e.message);}if(!b.consents.training&&Object.keys(answers).length)deny(400,'Autorize a finalidade de treinamento antes de registrar respostas.');return mutation(actor,req,b,async()=>{await store.lockStudent(id);await student(actor,id);const a=await current();if(b.revision!==(a?.revision||0))deny(409,'Respostas mudaram. Recarregue.');const retained=!b.consents.training?(a?.answers||'{}'):JSON.stringify(answers),revision=(a?.revision||0)+1;await store.run('INSERT INTO anamneses(student_id,org_id,version,answers,status,training_consent,nutrition_consent,consent_version,consented_at,revision,attention_review,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(student_id) DO UPDATE SET version=excluded.version,answers=excluded.answers,status=excluded.status,training_consent=excluded.training_consent,nutrition_consent=excluded.nutrition_consent,consent_version=excluded.consent_version,consented_at=excluded.consented_at,completed_at=NULL,revision=excluded.revision,attention_review=excluded.attention_review,reviewed_by=NULL,reviewed_revision=NULL,updated_at=excluded.updated_at',id,actor.org_id,INTAKE_VERSION,retained,'draft',Number(b.consents.training),Number(b.consents.nutrition),CONSENT_VERSION,now(),revision,Number(attentionReview(JSON.parse(retained))),now());await changed(actor,id,row.revision);await audit(actor,id,'anamnesis.saved:'+revision+':training='+b.consents.training+':nutrition='+b.consents.nutrition);return {status:200,data:{anamnesis:await state(id,actor.org_id)}};});}
  if(req.method==='POST'&&m[3]){const b=await read(req);exact(b,['version','revision','confirmed']);if(b.version!==INTAKE_VERSION||!Number.isInteger(b.revision)||b.confirmed!==true)deny(400,'Confirme versão e respostas atuais.');if(m[3]==='complete'&&actor.role!=='student')deny(403,'A conclusão pertence ao aluno.');if(m[3]==='review'&&actor.role!=='coach')deny(403,'Revisão exige o personal vinculado.');return mutation(actor,req,b,async()=>{await store.lockStudent(id);await student(actor,id);const a=await current();if(!a||a.revision!==b.revision)deny(409,'Respostas mudaram. Recarregue.');if(!a.training_consent)deny(409,'Autorização de treinamento pendente.');if(m[3]==='review'){if(a.status!=='complete')deny(409,'Conclua as respostas antes da revisão.');await store.run('UPDATE anamneses SET reviewed_by=?,reviewed_revision=revision,updated_at=? WHERE student_id=? AND org_id=?',actor.id,now(),id,actor.org_id);await audit(actor,id,'anamnesis.reviewed:'+a.revision);return {status:200,data:{anamnesis:await state(id,actor.org_id)}};}try{validateIntake(JSON.parse(a.answers),{complete:true});}catch(e){deny(400,e.message);}await store.run("UPDATE anamneses SET status='complete',completed_at=COALESCE(completed_at,?),updated_at=? WHERE student_id=? AND org_id=?",now(),now(),id,actor.org_id);if(a.status!=='complete')await audit(actor,id,'anamnesis.completed:'+a.revision);const result=await start(actor,row);return {status:result.status,data:{...result.data,anamnesis:await state(id,actor.org_id)}};});}
  return null;
 }
 return {state,handle};
}
