import {randomUUID} from 'node:crypto';
import {publicTrainingContent} from './manual-training.mjs';
const ZONE='America/Sao_Paulo';
export function executionDay(now){const parts=Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone:ZONE,year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date(now)).map(p=>[p.type,p.value]));return parts.year+'-'+parts.month+'-'+parts.day;}
export function executionWeek(day){const date=new Date(day+'T12:00:00Z');date.setUTCDate(date.getUTCDate()-((date.getUTCDay()+6)%7));return date.toISOString().slice(0,10);}
export function executionFlow({store,now,audit,deny,exact,text,read,mutation,student}){
  const today=()=>executionDay(now());
  async function own(actor){if(actor.role!=='student')deny(403,'Execução pertence ao aluno.');const row=await store.get('SELECT id FROM students WHERE user_id=? AND org_id=?',actor.id,actor.org_id);if(!row)deny(404,'Vínculo de aluno pendente.');return await student(actor,row.id);}
  async function allowed(actor,row){if(!row||row.org_id!==actor.org_id)deny(404,'Execução não encontrada.');const profile=await student(actor,row.student_id);if(!['admin','coach','student'].includes(actor.role))deny(403,'Execução restrita ao aluno e equipe de treino.');return profile;}
  async function dto(row){return {id:row.id,planId:row.plan_id,day:row.day,prescription:JSON.parse(row.prescription),completed:Boolean(row.completed),revision:row.revision,sets:(await store.all('SELECT exercise_index,set_index,reps,load,completed FROM workout_sets WHERE workout_id=? ORDER BY exercise_index,set_index',row.id)).map(s=>({exerciseIndex:s.exercise_index,setIndex:s.set_index,reps:s.reps,load:s.load,completed:Boolean(s.completed)}))};}
  async function handle(actor,req,route){
    if(route==='/api/local/workouts/current'&&req.method==='GET'){const profile=await own(actor),row=await store.get('SELECT * FROM workouts WHERE student_id=? AND org_id=? AND day=?',profile.id,actor.org_id,today());return {status:200,data:{workout:row?await dto(row):null,day:today(),timeZone:ZONE}};}
    if(route==='/api/local/workouts'&&req.method==='POST'){
      const profile=await own(actor),body=await read(req);exact(body,['planId',...(Object.hasOwn(body,'sessionId')?['sessionId']:[])]);if(typeof body.planId!=='string'||!/^[a-f0-9-]{36}$/.test(body.planId))deny(400,'Plano inválido.');
      return await mutation(actor,req,body,async()=>{await store.lockStudent(profile.id);await own(actor);const plan=await store.get("SELECT * FROM plans WHERE id=? AND student_id=? AND status='published'",body.planId,profile.id);if(!plan)deny(404,'Treino publicado não encontrado.');const content=publicTrainingContent(JSON.parse(plan.content));let selectedSession;if(content.sessions){selectedSession=content.sessions.find(s=>s.id===body.sessionId);if(!selectedSession)deny(400,'Choose one published session explicitly');}else if(Object.hasOwn(body,'sessionId'))deny(400,'This plan has no sessions');const day=today(),previous=await store.get('SELECT * FROM workouts WHERE student_id=? AND day=?',profile.id,day);if(previous){if(previous.plan_id!==plan.id||selectedSession&&JSON.parse(previous.prescription).sessionId!==selectedSession.id)deny(409,'Já existe uma execução hoje. Retome o treino iniciado.');return {status:200,data:{workout:await dto(previous)}};}
        if(!content.exercises?.length)deny(409,'Treino em PDF: consulte o arquivo; registro por série exige prescrição estruturada.');const weeklyTarget=content.daysPerWeek||3,id=randomUUID();await store.run('INSERT INTO workouts(id,org_id,student_id,plan_id,day,prescription,weekly_target,updated_at) VALUES (?,?,?,?,?,?,?,?)',id,actor.org_id,profile.id,plan.id,day,JSON.stringify({...content,daysPerWeek:weeklyTarget,...(selectedSession?{sessions:[selectedSession],sessionId:selectedSession.id,sessionName:selectedSession.name,exercises:selectedSession.exercises}: {})}),weeklyTarget,now());await audit(actor,profile.id,'workout.started');return {status:201,data:{workout:await dto(await store.get('SELECT * FROM workouts WHERE id=?',id))}};});
    }
    const match=/^\/api\/local\/workouts\/([a-f0-9-]{36})(\/sets|\/history)?$/.exec(route);
    if(match){const row=await store.get('SELECT * FROM workouts WHERE id=?',match[1]);await allowed(actor,row);
      if(!match[2]&&req.method==='GET')return {status:200,data:{workout:await dto(row)}};
      if(match[2]==='/history'&&req.method==='GET')return {status:200,data:{edits:(await store.all('SELECT id,actor_id,before_value,after_value,created_at FROM workout_edits WHERE workout_id=? ORDER BY created_at DESC LIMIT 100',row.id)).map(e=>({id:e.id,actorId:e.actor_id,before:JSON.parse(e.before_value),after:JSON.parse(e.after_value),createdAt:e.created_at}))}};
      if(match[2]==='/sets'&&req.method==='PUT'){
        if(actor.role!=='student')deny(403,'Somente o aluno registra sua execução.');const body=await read(req);exact(body,['exerciseIndex','setIndex','reps','load','completed','revision']);
        if(!Number.isInteger(body.exerciseIndex)||!Number.isInteger(body.setIndex)||!Number.isInteger(body.reps)||!Number.isFinite(body.load)||body.load<0||body.load>500||typeof body.completed!=='boolean'||!Number.isInteger(body.revision))deny(400,'Registro de série inválido.');
        return await mutation(actor,req,body,async()=>{await store.lockStudent(row.student_id);await store.lockWorkout(row.id);const current=await store.get('SELECT * FROM workouts WHERE id=?',row.id);await allowed(actor,current);if(current.day!==today())deny(409,'Somente a execução de hoje pode ser editada.');if(body.revision!==current.revision)deny(409,'Execução mudou. Recarregue para retomar.');const exercises=JSON.parse(current.prescription).exercises,exercise=exercises[body.exerciseIndex];if(!exercise||body.setIndex<0||body.setIndex>=exercise.sets||body.reps<0||body.reps>exercise.reps||(body.completed&&body.reps<1))deny(400,'Registre somente séries e repetições do treino prescrito.');
          const previous=await store.get('SELECT exercise_index,set_index,reps,load,completed FROM workout_sets WHERE workout_id=? AND exercise_index=? AND set_index=?',row.id,body.exerciseIndex,body.setIndex),value={exerciseIndex:body.exerciseIndex,setIndex:body.setIndex,reps:body.reps,load:body.load,completed:body.completed};
          if(previous&&previous.reps===body.reps&&previous.load===body.load&&Boolean(previous.completed)===body.completed)return {status:200,data:{workout:await dto(current),changed:false}};
          await store.run('INSERT INTO workout_sets(workout_id,exercise_index,set_index,reps,load,completed) VALUES (?,?,?,?,?,?) ON CONFLICT(workout_id,exercise_index,set_index) DO UPDATE SET reps=excluded.reps,load=excluded.load,completed=excluded.completed',row.id,body.exerciseIndex,body.setIndex,body.reps,body.load,body.completed?1:0);
          const count=(await store.get('SELECT COUNT(*) AS n FROM workout_sets WHERE workout_id=? AND completed=1',row.id)).n,total=exercises.reduce((sum,e)=>sum+e.sets,0);const changed=await store.run('UPDATE workouts SET completed=?,revision=revision+1,updated_at=? WHERE id=? AND revision=?',Number(count)===total?1:0,now(),row.id,body.revision);if(changed.changes!==1)deny(409,'Execução mudou. Recarregue para retomar.');await store.run('INSERT INTO workout_edits VALUES (?,?,?,?,?,?)',randomUUID(),row.id,actor.id,JSON.stringify(previous?{exerciseIndex:previous.exercise_index,setIndex:previous.set_index,reps:previous.reps,load:previous.load,completed:Boolean(previous.completed)}:null),JSON.stringify(value),now());await audit(actor,row.student_id,'workout.set.saved');return {status:200,data:{workout:await dto(await store.get('SELECT * FROM workouts WHERE id=?',row.id)),changed:true}};});
      }
    }
    const studentMatch=/^\/api\/local\/students\/([a-f0-9-]{36})\/workouts$/.exec(route);
    if(studentMatch&&req.method==='GET'){await student(actor,studentMatch[1]);if(!['admin','coach','student'].includes(actor.role))deny(403,'Execução restrita à equipe de treino.');const rows=await store.all('SELECT * FROM workouts WHERE student_id=? AND org_id=? ORDER BY day DESC LIMIT 30',studentMatch[1],actor.org_id);return {status:200,data:{workouts:await Promise.all(rows.map(dto))}};}
    if(route==='/api/local/ranking/preferences'){
      const profile=await own(actor);
      if(req.method==='GET'){const p=await store.get('SELECT enabled,alias,revision FROM ranking_preferences WHERE student_id=?',profile.id);return {status:200,data:{preferences:{enabled:Boolean(p?.enabled),alias:p?.alias||'',revision:p?.revision||0}}};}
      if(req.method==='PUT'){const body=await read(req);exact(body,['enabled','alias','revision']);if(typeof body.enabled!=='boolean'||typeof body.alias!=='string'||!Number.isInteger(body.revision)||body.revision<0)deny(400,'Preferência inválida.');const alias=body.enabled?text(body.alias,2,24):'';if(body.enabled&&/[<>\r\n]/.test(alias))deny(400,'Use um pseudônimo simples.');return await mutation(actor,req,body,async()=>{const p=await store.get('SELECT revision FROM ranking_preferences WHERE student_id=?',profile.id);if((p?.revision||0)!==body.revision)deny(409,'Preferência mudou. Recarregue.');if(p)await store.run('UPDATE ranking_preferences SET enabled=?,alias=?,revision=revision+1 WHERE student_id=?',body.enabled?1:0,alias,profile.id);else await store.run('INSERT INTO ranking_preferences(student_id,org_id,enabled,alias) VALUES (?,?,?,?)',profile.id,actor.org_id,body.enabled?1:0,alias);await audit(actor,profile.id,body.enabled?'ranking.opted-in':'ranking.opted-out');return {status:200,data:{preferences:{enabled:body.enabled,alias,revision:body.revision+1}}};});}
    }
    if(route==='/api/local/ranking'&&req.method==='GET'){
      const day=today(),week=executionWeek(day),people=await store.all("SELECT p.alias,SUM(CASE WHEN w.completed=1 THEN 1 ELSE 0 END) AS finished,MAX(w.weekly_target) AS target FROM ranking_preferences p JOIN students s ON s.id=p.student_id JOIN users u ON u.id=s.user_id LEFT JOIN workouts w ON w.student_id=s.id AND w.org_id=p.org_id AND w.day>=? AND w.day<=? WHERE p.org_id=? AND s.org_id=? AND u.org_id=? AND u.active=1 AND u.role='student' AND p.enabled=1 GROUP BY p.student_id,p.alias",week,day,actor.org_id,actor.org_id,actor.org_id),entries=people.map(p=>({alias:p.alias,consistency:Math.min(100,Math.round(Number(p.finished)*100/(Number(p.target)||3)))}));
      entries.sort((a,b)=>b.consistency-a.consistency||a.alias.localeCompare(b.alias));return {status:200,data:{week,timeZone:ZONE,entries:entries.slice(0,50)}};
    }
    return null;
  }
  return {handle};
}
