import {randomUUID} from 'node:crypto';

// Integer arithmetic: composition hundredths per 100 g × portion tenths of a gram.
// Sum unrounded integers first. No raw/cooked conversion or clinical target is inferred.
export function nutritionTotals(meals,choices=[]){
 const keys=['energyKcal','proteinG','carbsG','fatG'];const total=Object.fromEntries(keys.map(k=>[k,0]));
 meals.forEach((meal,mi)=>meal.items.forEach((item,ii)=>{const option=choices.find(c=>c.mealIndex===mi&&c.itemIndex===ii)?.optionIndex||0;const entry=option===0?item:item.alternatives[option-1];if(!entry)throw Error('Invalid approved choice');for(const key of keys)total[key]+=entry.composition[key]*entry.gramsTenths;}));
 const output=Object.fromEntries(keys.map(k=>[k,Math.round(total[k]/100)/1000]));output.macroEnergyKcal=Math.round((total.proteinG*4+total.carbsG*4+total.fatG*9)/100)/1000;return output;
}
export function nutritionFlow({store,now,deny,exact,text,read,mutation,student,audit}){
 const uuid=id=>typeof id==='string'&&/^[a-f0-9-]{36}$/.test(id);
 const revision=v=>{if(!Number.isInteger(v)||v<0)deny(400,'Revisão inválida.');};
 const tags=value=>{if(!Array.isArray(value)||value.length>30||value.some(v=>typeof v!=='string'||v.length<2||v.length>60||!/^[a-z0-9-]+$/.test(v))||new Set(value).size!==value.length)deny(400,'Declare alergênicos por códigos únicos (2–60 letras, números ou hífen).');return value;};
 const scaled=(v,max,scale)=>{if(typeof v!=='number'||!Number.isFinite(v)||v<0||v>max||Math.abs(v*scale-Math.round(v*scale))>1e-7)deny(400,'Valor ou precisão inválidos. Use gramas e valores por 100 g.');return Math.round(v*scale);};
 async function qualified(actor){if(actor.role!=='nutrition')deny(403,'Prescrição exige nutricionista responsável; admin não recebe esse papel.');const c=await store.get('SELECT * FROM nutrition_credentials WHERE user_id=? AND org_id=? AND verified=1',actor.id,actor.org_id);if(!c)deny(403,'Habilitação profissional precisa ser conferida pela administração.');return c;}
 async function manager(actor,id){await qualified(actor);const row=await student(actor,id);if(row.nutrition_id!==actor.id)deny(404,'Aluno não encontrado.');return row;}
 async function access(actor,id){if(!['admin','nutrition','student'].includes(actor.role))deny(403,'Nutrição restrita ao aluno, responsável e administração.');return await student(actor,id);}
 async function food(actor,id){const row=await store.get("SELECT * FROM nutrition_foods WHERE id=? AND org_id=? AND status='approved'",id,actor.org_id);if(!row)deny(400,'Use alimento aprovado da sua organização.');return row;}
 const foodDTO=row=>({id:row.id,name:row.name,preparation:row.preparation,per100g:Object.fromEntries(Object.entries(JSON.parse(row.composition)).map(([k,v])=>[k,v/100])),allergens:JSON.parse(row.allergens),mayContain:JSON.parse(row.may_contain),provenance:JSON.parse(row.provenance),status:row.status,revision:row.revision});
 async function snapshot(actor,input,allergies){exact(input,['foodId','grams']);if(!uuid(input.foodId))deny(400,'Alimento inválido.');const gramsTenths=scaled(input.grams,2000,10);if(gramsTenths<1)deny(400,'Porção deve ser positiva em gramas.');const row=await food(actor,input.foodId),allergens=JSON.parse(row.allergens),mayContain=JSON.parse(row.may_contain);if([...allergens,...mayContain].some(tag=>allergies.includes(tag)))deny(400,'Alimento ou alternativa conflita com alergia declarada.');return {foodId:row.id,name:row.name,preparation:row.preparation,gramsTenths,composition:JSON.parse(row.composition),allergens,mayContain,provenance:JSON.parse(row.provenance),catalogRevision:row.revision,approvedBy:row.approved_by};}
 async function content(actor,body){exact(body,['title','allergies','allergiesChecked','meals']);if(body.allergiesChecked!==true)deny(400,'Confira alergias, traços e adequação das opções.');const allergies=tags(body.allergies);if(!Array.isArray(body.meals)||body.meals.length<1||body.meals.length>6)deny(400,'Use 1–6 refeições.');let portions=0;
  const meals=[];for(const meal of body.meals){exact(meal,['name','items']);if(!Array.isArray(meal.items)||meal.items.length<1||meal.items.length>6)deny(400,'Use 1–6 itens por refeição.');const items=[];for(const item of meal.items){exact(item,['foodId','grams','alternatives']);if(!Array.isArray(item.alternatives)||item.alternatives.length>4)deny(400,'Use até quatro alternativas aprovadas.');portions+=1+item.alternatives.length;if(portions>60)deny(400,'Limite de 60 porções/opções por plano.');const primary=await snapshot(actor,{foodId:item.foodId,grams:item.grams},allergies),alternatives=[];for(const alternative of item.alternatives)alternatives.push(await snapshot(actor,alternative,allergies));items.push({...primary,alternatives});}meals.push({name:text(meal.name,2,80),items});}
  return {allergies,allergiesChecked:true,meals};
 }
 const choices=async plan=>await store.all('SELECT meal_index,item_index,option_index,revision FROM nutrition_choices WHERE plan_id=? AND student_id=?',plan.id,plan.student_id);
 const choiceDTO=c=>({mealIndex:c.meal_index,itemIndex:c.item_index,optionIndex:c.option_index,revision:c.revision});
 async function planDTO(row,actor){const base={id:row.id,studentId:row.student_id,title:row.title,status:row.status,revision:row.revision};if(actor.role==='admin')return {...base,clinicalDetailsRestricted:true};const c=JSON.parse(row.content),selected=(await choices(row)).map(choiceDTO);return {...base,content:c,choices:selected,totals:nutritionTotals(c.meals,selected),baseTotals:nutritionTotals(c.meals),calculation:'catalog-per-100g-integer-rounded-at-total',unit:'g',clinicalTargetsGenerated:false};}
 async function plan(actor,id){const row=await store.get('SELECT * FROM nutrition_plans WHERE id=? AND org_id=?',id,actor.org_id);if(!row)deny(404,'Plano não encontrado.');await access(actor,row.student_id);if(actor.role==='student'&&row.status!=='published')deny(404,'Plano não encontrado.');return row;}
 async function lockingManager(actor,id){await store.lockStudent(id);return await manager(actor,id);}
 return {async handle(actor,req,route){
  const credentialsRoute=route==='/api/local/nutrition/credentials',foodsRoute=route==='/api/local/nutrition/foods';
  const studentRoute=/^\/api\/local\/students\/([a-f0-9-]{36})\/nutrition(?:\/(requests))?$/.exec(route);
  const planRoute=/^\/api\/local\/nutrition\/plans\/([a-f0-9-]{36})(?:\/(submit|approve|publish|choices))?$/.exec(route);
  const foodApproval=/^\/api\/local\/nutrition\/foods\/([a-f0-9-]{36})\/approve$/.exec(route);
  const requestReview=/^\/api\/local\/nutrition\/requests\/([a-f0-9-]{36})\/review$/.exec(route);
  if(!credentialsRoute&&!foodsRoute&&!studentRoute&&!planRoute&&!foodApproval&&!requestReview)return null;
  if(credentialsRoute){
   if(req.method==='GET'){if(actor.role==='admin')return {status:200,data:{credentials:await store.all("SELECT u.id,u.name,c.registration,c.verified,c.revision FROM users u LEFT JOIN nutrition_credentials c ON c.user_id=u.id WHERE u.org_id=? AND u.role='nutrition' AND u.active=1 ORDER BY u.name",actor.org_id)}};if(actor.role==='nutrition'){const credential=await store.get('SELECT registration,verified,revision FROM nutrition_credentials WHERE user_id=? AND org_id=?',actor.id,actor.org_id);return {status:200,data:{credential:credential||null}};}deny(403,'Habilitação restrita à administração/profissional.');}
   if(req.method!=='PUT'||actor.role!=='admin')deny(403,'Conferência profissional exige administração.');const body=await read(req);exact(body,['userId','registration','verified','checkedRegistration','revision']);if(!uuid(body.userId)||typeof body.verified!=='boolean'||body.checkedRegistration!==true)deny(400,'Confirme registro e habilitação no órgão competente.');revision(body.revision);const registration=text(body.registration,3,80);
   return await mutation(actor,req,body,async()=>{await store.lockActor(body.userId);const user=await store.get("SELECT id FROM users WHERE id=? AND org_id=? AND role='nutrition' AND active=1",body.userId,actor.org_id);if(!user)deny(404,'Profissional não encontrado.');const old=await store.get('SELECT * FROM nutrition_credentials WHERE user_id=?',body.userId);if((old?.revision||0)!==body.revision)deny(409,'Habilitação mudou. Recarregue.');await store.run('INSERT INTO nutrition_credentials(user_id,org_id,registration,verified,verified_by,verified_at,revision) VALUES (?,?,?,?,?,?,?) ON CONFLICT(user_id) DO UPDATE SET registration=excluded.registration,verified=excluded.verified,verified_by=excluded.verified_by,verified_at=excluded.verified_at,revision=excluded.revision',body.userId,actor.org_id,registration,Number(body.verified),actor.id,now(),body.revision+1);await audit(actor,null,'nutrition.credential.'+(body.verified?'verified':'revoked')+':'+body.userId);return {status:200,data:{verified:body.verified,revision:body.revision+1}};});
  }
  if(foodsRoute){await qualified(actor);if(req.method==='GET')return {status:200,data:{foods:(await store.all('SELECT * FROM nutrition_foods WHERE org_id=? ORDER BY created_at DESC LIMIT 200',actor.org_id)).map(foodDTO),automaticCatalog:false}};
   if(req.method!=='POST')deny(405,'Método não permitido.');const body=await read(req);exact(body,['name','preparation','per100g','allergens','mayContain','provenance']);if(!['raw','cooked','as-sold'].includes(body.preparation))deny(400,'Declare cru, cozido ou como vendido.');exact(body.per100g,['energyKcal','proteinG','carbsG','fatG']);const composition=Object.fromEntries(Object.entries(body.per100g).map(([k,v])=>[k,scaled(v,k==='energyKcal'?1000:100,100)]));if(composition.proteinG+composition.carbsG+composition.fatG>10000)deny(400,'Macronutrientes excedem 100 g.');const allergens=tags(body.allergens),mayContain=tags(body.mayContain);exact(body.provenance,['source','reference','version']);const provenance={source:text(body.provenance.source,3,100),reference:text(body.provenance.reference,3,300),version:text(body.provenance.version,1,80)};const name=text(body.name,2,100);
   return await mutation(actor,req,body,async()=>{await qualified(actor);const id=randomUUID();await store.run('INSERT INTO nutrition_foods(id,org_id,author_id,name,preparation,composition,allergens,may_contain,provenance,status,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?)',id,actor.org_id,actor.id,name,body.preparation,JSON.stringify(composition),JSON.stringify(allergens),JSON.stringify(mayContain),JSON.stringify(provenance),'draft',now());await audit(actor,null,'nutrition.food.drafted');return {status:201,data:{food:foodDTO(await store.get('SELECT * FROM nutrition_foods WHERE id=?',id))}};});
  }
  if(foodApproval){await qualified(actor);if(req.method!=='POST')deny(405,'Método não permitido.');const body=await read(req);exact(body,['revision','sourceVerified']);revision(body.revision);if(body.sourceVerified!==true)deny(400,'Confira composição, estado, fonte e alergênicos.');
   return await mutation(actor,req,body,async()=>{await qualified(actor);const row=await store.get('SELECT * FROM nutrition_foods WHERE id=? AND org_id=?',foodApproval[1],actor.org_id);if(!row)deny(404,'Alimento não encontrado.');if(row.revision!==body.revision||row.status!=='draft')deny(409,'Catálogo mudou.');const update=await store.run("UPDATE nutrition_foods SET status='approved',approved_by=?,revision=revision+1 WHERE id=? AND revision=? AND status='draft'",actor.id,row.id,body.revision);if(update.changes!==1)deny(409,'Catálogo mudou.');await audit(actor,null,'nutrition.food.approved');return {status:200,data:{food:foodDTO(await store.get('SELECT * FROM nutrition_foods WHERE id=?',row.id))}};});
  }
  if(studentRoute){const id=studentRoute[1];await access(actor,id);
   if(studentRoute[2]==='requests'){
    if(req.method==='GET'){const rows=await store.all('SELECT * FROM nutrition_requests WHERE student_id=? AND org_id=? ORDER BY created_at DESC LIMIT 50',id,actor.org_id);return {status:200,data:{requests:rows.map(r=>actor.role==='admin'?{id:r.id,status:r.status,revision:r.revision}:{id:r.id,planId:r.plan_id,mealIndex:r.meal_index,itemIndex:r.item_index,request:r.request,response:r.response,status:r.status,revision:r.revision})}};}
    if(req.method!=='POST'||actor.role!=='student')deny(403,'Solicitação pertence ao aluno.');const body=await read(req);exact(body,['planId','mealIndex','itemIndex','request']);const request=text(body.request,3,500);
    return await mutation(actor,req,body,async()=>{await store.lockStudent(id);await student(actor,id);const p=await plan(actor,body.planId);if(p.student_id!==id||p.status!=='published')deny(404,'Plano não encontrado.');const c=JSON.parse(p.content);if(!Number.isInteger(body.mealIndex)||!Number.isInteger(body.itemIndex)||!c.meals[body.mealIndex]?.items[body.itemIndex])deny(400,'Item inválido.');const rid=randomUUID();await store.run('INSERT INTO nutrition_requests(id,org_id,student_id,plan_id,meal_index,item_index,request,status,created_at) VALUES (?,?,?,?,?,?,?,?,?)',rid,actor.org_id,id,p.id,body.mealIndex,body.itemIndex,request,'pending',now());await audit(actor,id,'nutrition.change.requested');return {status:201,data:{requestId:rid,status:'pending',prescriptionChanged:false}};});
   }
   if(req.method==='GET'){const rows=await store.all('SELECT * FROM nutrition_plans WHERE student_id=? AND org_id=?'+(actor.role==='student'?" AND status='published'":'')+' ORDER BY created_at DESC LIMIT 20',id,actor.org_id);return {status:200,data:{plans:await Promise.all(rows.map(p=>planDTO(p,actor)))}};}
   if(req.method!=='POST')deny(405,'Método não permitido.');await manager(actor,id);const body=await read(req);const title=text(body.title,2,100);
   return await mutation(actor,req,body,async()=>{await lockingManager(actor,id);const c=await content(actor,body),pid=randomUUID();await store.run('INSERT INTO nutrition_plans(id,org_id,student_id,author_id,title,content,status,created_at) VALUES (?,?,?,?,?,?,?,?)',pid,actor.org_id,id,actor.id,title,JSON.stringify(c),'draft',now());await audit(actor,id,'nutrition.plan.drafted');return {status:201,data:{plan:await planDTO(await store.get('SELECT * FROM nutrition_plans WHERE id=?',pid),actor)}};});
  }
  if(planRoute){const p=await plan(actor,planRoute[1]),action=planRoute[2];
   if(!action&&req.method==='GET')return {status:200,data:{plan:await planDTO(p,actor)}};
   if(!action&&req.method==='PUT'){await manager(actor,p.student_id);const body=await read(req);exact(body,['title','allergies','allergiesChecked','meals','revision']);revision(body.revision);
    return await mutation(actor,req,body,async()=>{await lockingManager(actor,p.student_id);const current=await plan(actor,p.id);if(current.status==='published'||current.revision!==body.revision)deny(409,'Plano publicado é imutável; crie nova versão.');const {revision:ignored,...input}=body;void ignored;const c=await content(actor,input);const update=await store.run("UPDATE nutrition_plans SET title=?,content=?,status='draft',approved_by=NULL,approved_revision=NULL,revision=revision+1 WHERE id=? AND revision=?",text(body.title,2,100),JSON.stringify(c),p.id,body.revision);if(update.changes!==1)deny(409,'Plano mudou.');await audit(actor,p.student_id,'nutrition.plan.edited');return {status:200,data:{plan:await planDTO(await plan(actor,p.id),actor)}};});
   }
   if(action==='choices'){
    if(actor.role!=='student'||req.method!=='POST')deny(403,'Escolha pertence ao aluno.');const body=await read(req);exact(body,['mealIndex','itemIndex','optionIndex','planRevision','revision']);revision(body.revision);
    return await mutation(actor,req,body,async()=>{await store.lockStudent(p.student_id);const current=await plan(actor,p.id);if(current.status!=='published'||current.revision!==body.planRevision)deny(409,'Plano mudou.');const c=JSON.parse(current.content);if(![body.mealIndex,body.itemIndex,body.optionIndex].every(Number.isInteger))deny(400,'Opção inválida.');const item=c.meals[body.mealIndex]?.items[body.itemIndex];if(!item||body.optionIndex<0||body.optionIndex>item.alternatives.length)deny(400,'Só alternativas previamente aprovadas. Solicite revisão para outra opção.');const old=await store.get('SELECT revision FROM nutrition_choices WHERE plan_id=? AND student_id=? AND meal_index=? AND item_index=?',p.id,p.student_id,body.mealIndex,body.itemIndex);if((old?.revision||0)!==body.revision)deny(409,'Escolha mudou.');await store.run('INSERT INTO nutrition_choices VALUES (?,?,?,?,?,?) ON CONFLICT(plan_id,student_id,meal_index,item_index) DO UPDATE SET option_index=excluded.option_index,revision=excluded.revision',p.id,p.student_id,body.mealIndex,body.itemIndex,body.optionIndex,body.revision+1);await audit(actor,p.student_id,'nutrition.option.selected');return {status:200,data:{plan:await planDTO(current,actor),prescriptionChanged:false}};});
   }
   if(!['submit','approve','publish'].includes(action)||req.method!=='POST')deny(405,'Método não permitido.');await manager(actor,p.student_id);const body=await read(req);exact(body,action==='approve'?['revision','reviewed']:['revision']);revision(body.revision);if(action==='approve'&&body.reviewed!==true)deny(400,'Revisão profissional explícita obrigatória.');
   return await mutation(actor,req,body,async()=>{await lockingManager(actor,p.student_id);const current=await plan(actor,p.id),required={submit:'draft',approve:'review',publish:'approved'}[action];if(current.status!==required||current.revision!==body.revision)deny(409,'Estado/revisão mudou.');if(action==='publish'&&(!current.approved_by||current.approved_by!==actor.id||current.approved_revision!==current.revision-1))deny(409,'Aprovação profissional desatualizada.');let update;
    if(action==='approve')update=await store.run("UPDATE nutrition_plans SET status='approved',approved_by=?,approved_revision=revision,revision=revision+1 WHERE id=? AND revision=? AND status=?",actor.id,p.id,body.revision,required);
    else if(action==='publish')update=await store.run("UPDATE nutrition_plans SET status='published',published_at=?,revision=revision+1 WHERE id=? AND revision=? AND status=?",now(),p.id,body.revision,required);
    else update=await store.run("UPDATE nutrition_plans SET status='review',revision=revision+1 WHERE id=? AND revision=? AND status=?",p.id,body.revision,required);
    if(update.changes!==1)deny(409,'Plano mudou.');await audit(actor,p.student_id,'nutrition.plan.'+action);return {status:200,data:{plan:await planDTO(await plan(actor,p.id),actor)}};});
  }
  if(requestReview){await qualified(actor);if(req.method!=='POST')deny(405,'Método não permitido.');const body=await read(req);exact(body,['revision','decision','response']);revision(body.revision);if(!['reviewed','declined'].includes(body.decision))deny(400,'Decisão inválida.');const response=text(body.response,3,500),r=await store.get('SELECT * FROM nutrition_requests WHERE id=? AND org_id=?',requestReview[1],actor.org_id);if(!r)deny(404,'Solicitação não encontrada.');await manager(actor,r.student_id);
   return await mutation(actor,req,body,async()=>{await lockingManager(actor,r.student_id);const update=await store.run("UPDATE nutrition_requests SET status=?,response=?,reviewed_by=?,revision=revision+1 WHERE id=? AND revision=? AND status='pending'",body.decision,response,actor.id,r.id,body.revision);if(update.changes!==1)deny(409,'Solicitação mudou.');await audit(actor,r.student_id,'nutrition.change.'+body.decision);return {status:200,data:{status:body.decision,prescriptionChanged:false,requiresNewReviewedPlan:true}};});
  }
 }};
}
