import {createHash,randomUUID} from 'node:crypto';
import {hashPassword,newToken,tokenHash} from './auth.mjs';
import {ACCESS_LEVELS} from './access-policy.mjs';
const mark=kind=>createHash('sha256').update('sim-password-access:'+kind+':v1').digest('hex');
const MAIL=mark('mail'),TOKEN=mark('token'),TTL=15*60*1000;
const generic={message:'Se o endereço estiver autorizado, você receberá as instruções por e-mail. Confira também a pasta de spam.'};
export function passwordAccessFlow({store,now,deny,exact,email,read,audit,mutation,student,policy,security,configuration={}}){
 let closed=false,draining=null;const abort=new AbortController();
 function available(){try{const url=new URL(configuration.publicOrigin);return configuration.enabled===true&&configuration.reviewed===true&&typeof configuration.transport?.send==='function'&&(['smtp','resend'].includes(configuration.transport.kind)||!security.production&&configuration.transport.kind==='mock')&&url.origin===configuration.publicOrigin&&!url.username&&!url.password&&(url.protocol==='https:'||!security.production&&configuration.transport.kind==='mock'&&url.protocol==='http:'&&['127.0.0.1','localhost'].includes(url.hostname))&&(!security.production||url.origin===security.origin);}catch{return false;}}
 const decode=r=>({...JSON.parse(r.result),ownerId:r.actor_id});
 const same=(a,b)=>a.orgId===b.orgId&&a.email===b.email&&(a.userId&&b.userId?a.userId===b.userId:a.studentId===b.studentId);
 async function throttle(bucket,limit){await store.transaction(async()=>{const a=await store.get('INSERT INTO login_attempts(bucket,count,reset_at) VALUES (?,?,?) ON CONFLICT(bucket) DO UPDATE SET count=CASE WHEN login_attempts.reset_at<=? THEN 1 ELSE login_attempts.count+1 END,reset_at=CASE WHEN login_attempts.reset_at<=? THEN ? ELSE login_attempts.reset_at END RETURNING count',bucket,1,now()+TTL,now(),now(),now()+TTL);if(a.count>limit)deny(429,'Aguarde antes de tentar novamente.');});}
 async function resolve(kind,address){
  const user=await store.get('SELECT * FROM users WHERE email=?',address);
  if(kind==='reset'){if(!user?.active)return null;return {kind,email:address,userId:user.id,studentId:(await store.get('SELECT id FROM students WHERE user_id=?',user.id))?.id||null,orgId:user.org_id,ownerId:user.id,ownerRole:user.role,userRole:user.role};}
  if(user&&!user.active)return null;const rows=await store.all('SELECT * FROM students WHERE email=? AND user_id IS NULL',address),targets=[];
  for(const row of rows){const g=await policy.state(row);if(g.mode!=='manual'||!g.active)continue;if(user&&(user.role!=='student'||user.org_id!==row.org_id||await store.get('SELECT id FROM students WHERE user_id=?',user.id)))continue;const issuer=await store.get("SELECT id FROM users WHERE id=? AND org_id=? AND role='admin' AND active=1",g.issuedBy,row.org_id);if(issuer)targets.push({kind,email:address,userId:user?.id||null,studentId:row.id,orgId:row.org_id,ownerId:issuer.id,ownerRole:'admin',userRole:'student',grantSequence:g.sequence});}
  return targets.length===1?targets[0]:null;
 }
 async function validTarget(t){const owner=await store.get('SELECT * FROM users WHERE id=?',t.ownerId);if(!owner?.active||owner.org_id!==t.orgId||owner.role!==t.ownerRole)return false;
  if(t.kind==='reset'){const u=await store.get('SELECT * FROM users WHERE id=?',t.userId);return !!u?.active&&u.email===t.email&&u.org_id===t.orgId&&u.role===t.userRole;}
  const row=await store.get('SELECT * FROM students WHERE id=?',t.studentId);if(!row||row.org_id!==t.orgId||row.email!==t.email)return false;const g=await policy.state(row);if(g.mode!=='manual'||!g.active||g.sequence!==t.grantSequence)return false;if(t.kind==='welcome')return true;
  if(row.user_id)return false;const u=await store.get('SELECT * FROM users WHERE email=?',t.email);return t.userId?!!u?.active&&u.id===t.userId&&u.org_id===t.orgId&&u.role==='student'&&!await store.get('SELECT id FROM students WHERE user_id=?',u.id):!u;
 }
 async function change(r,status,value){return (await store.run('UPDATE operations SET status=?,result=? WHERE actor_id=? AND operation_key=? AND status=? AND result=?',status,JSON.stringify(value),r.actor_id,r.operation_key,r.status,r.result)).changes===1;}
 async function revokeLocked(target){for(const r of await store.all('SELECT * FROM operations WHERE request_hash=? AND status=?',TOKEN,202)){const v=decode(r);if(same(v.target,target))await change(r,409,{...v,revokedAt:now()});}for(const r of await store.all('SELECT * FROM operations WHERE request_hash=? AND status IN (202,102)',MAIL)){const v=decode(r);if(v.kind!=='welcome'&&same(v.target,target))await change(r,409,{...v,state:'cancelled'});}}
 async function queueLocked(target,kind){const id=randomUUID(),job={id,kind,target,createdAt:now(),expiresAt:now()+TTL,state:'pending'};await store.run('INSERT INTO operations VALUES (?,?,?,?,?)',target.ownerId,'access-mail-'+id,MAIL,202,JSON.stringify(job));return id;}
 async function welcomeLocked(actor,row,grant){if(!available())return false;await queueLocked({kind:'welcome',email:row.email,userId:row.user_id||null,studentId:row.id,orgId:row.org_id,ownerId:actor.id,ownerRole:'admin',userRole:'student',grantSequence:grant.sequence},'welcome');return true;}
 async function deliver(r){const rawToken=newToken();let claimed;
  await store.transaction(async()=>{await store.lockActor(r.actor_id);const current=await store.get('SELECT * FROM operations WHERE actor_id=? AND operation_key=?',r.actor_id,r.operation_key);if(!current||current.status!==202)return;const v=decode(current);if(v.target.studentId)await store.lockStudent(v.target.studentId);if(!available()||v.expiresAt<=now()||!await validTarget(v.target)){await change(current,409,{...v,state:'cancelled'});return;}claimed={...v,state:'sending',leaseUntil:now()+30000};if(!await change(current,102,claimed)){claimed=null;return;}if(v.kind!=='welcome')await store.run('INSERT INTO operations VALUES (?,?,?,?,?)',v.ownerId,'password-token-'+tokenHash(rawToken),TOKEN,202,JSON.stringify({target:v.target,jobId:v.id,expiresAt:now()+TTL,createdAt:now()}));});
  if(!claimed)return;const normal=configuration.publicOrigin+'/local',link=normal+'#password='+rawToken;let accepted=false;
  let deliveryTimer;const deliveryAbort=new AbortController();try{const reply=await Promise.race([configuration.transport.send({to:claimed.target.email,subject:claimed.kind==='welcome'?'Seu acesso ao Shape IS Money':claimed.kind==='signup'?'Confirme seu e-mail e crie sua conta':'Redefina sua senha do Shape IS Money',text:claimed.kind==='welcome'?'Seu cadastro foi autorizado pelo responsável. Acesse '+normal+' e escolha Criar conta usando este endereço de e-mail. Você definirá sua própria senha após confirmar a titularidade.':'Para '+(claimed.kind==='signup'?'confirmar seu e-mail e definir':'redefinir')+' sua senha, abra este link de uso único (válido por 15 minutos):\n'+link+'\nSe você não solicitou, ignore esta mensagem. Nenhum plano ou informação de saúde é enviado neste e-mail.',idempotencyKey:'access-mail-'+claimed.id,signal:AbortSignal.any([abort.signal,deliveryAbort.signal])}),new Promise((_,reject)=>{deliveryTimer=setTimeout(()=>{deliveryAbort.abort();reject(Error('Delivery timeout'));},10000);})]);accepted=reply?.accepted===true;}catch{/* Deliberately discard provider diagnostics, recipient, link and credentials. */}finally{clearTimeout(deliveryTimer);}
  await store.transaction(async()=>{await store.lockActor(r.actor_id);const current=await store.get('SELECT * FROM operations WHERE actor_id=? AND operation_key=?',r.actor_id,r.operation_key);if(current?.status!==102)return;const v=decode(current);await change(current,accepted?200:502,{...v,state:accepted?'accepted':'failed',finishedAt:now(),...(accepted?{}:{failure:'provider-unavailable'})});if(!accepted&&v.kind!=='welcome'){const token=await store.get('SELECT * FROM operations WHERE actor_id=? AND operation_key=?',r.actor_id,'password-token-'+tokenHash(rawToken));if(token?.status===202)await change(token,409,{...decode(token),revokedAt:now()});}});
 }
 async function flush(){if(closed||!available())return;if(draining)return draining;draining=(async()=>{for(const r of await store.all('SELECT * FROM operations WHERE request_hash=? AND status=?',MAIL,102)){const v=decode(r);if(v.leaseUntil<=now())await change(r,502,{...v,state:'failed',failure:'delivery-unknown'});}for(const r of await store.all('SELECT * FROM operations WHERE request_hash=? AND status=? ORDER BY operation_key LIMIT 20',MAIL,202)){if(closed)break;await deliver(r);}})();try{await draining;}finally{draining=null;}}
 const timer=configuration.autoDispatch!==false?setInterval(()=>{flush().catch(()=>{});},2000):null;timer?.unref?.();
 async function handlePublic(req,connection,route){
  if(route==='/api/local/password-access/capabilities'&&req.method==='GET')return {status:200,data:{emailAvailable:available(),manualInvitationsAvailable:true}};
  const request=/^\/api\/local\/password-access\/(signup|reset)\/request$/.exec(route);
  if(request&&req.method==='POST'){const started=performance.now();await throttle('access-request-ip:'+connection.clientIP,8);const body=await read(req);exact(body,['email']);const address=email(body.email);await throttle('access-request-email:'+tokenHash(address),3);if(!available())deny(503,'Acesso por e-mail ainda indisponível. Use um convite privado ou procure o responsável.');const target=await resolve(request[1],address);if(target)await store.transaction(async()=>{await store.lockActor(target.ownerId);if(target.studentId)await store.lockStudent(target.studentId);if(await validTarget(target)){await revokeLocked(target);await queueLocked(target,request[1]);}});const minimum=security.production?250:(configuration.minimumResponseMs??250);await new Promise(r=>setTimeout(r,Math.max(0,minimum-(performance.now()-started))));return {status:202,data:generic};}
  if(route==='/api/local/password-access/confirm'&&req.method==='POST'){await throttle('access-confirm-ip:'+connection.clientIP,8);const body=await read(req);exact(body,['token','email','password']);const address=email(body.email);if(typeof body.token!=='string'||! /^[A-Za-z0-9_-]{43}$/.test(body.token)||typeof body.password!=='string'||body.password.length<14||body.password.length>128)deny(400,'Link e senha de 14–128 caracteres obrigatórios.');if(!available())deny(503,'Acesso por e-mail indisponível.');const password=await hashPassword(body.password),key='password-token-'+tokenHash(body.token),invalid=()=>deny(400,'Link inválido, expirado ou já utilizado. Solicite outro pelo seu e-mail.');
   await store.transaction(async()=>{let r=await store.get('SELECT * FROM operations WHERE request_hash=? AND operation_key=?',TOKEN,key);if(!r)return invalid();await store.lockActor(r.actor_id);r=await store.get('SELECT * FROM operations WHERE actor_id=? AND operation_key=?',r.actor_id,key);const v=decode(r),t=v.target;if(t.studentId)await store.lockStudent(t.studentId);if(r.status!==202||v.expiresAt<=now()||t.email!==address||!await validTarget(t))return invalid();if(!await change(r,200,{...v,consumedAt:now()}))return invalid();let id=t.userId;
    if(t.kind==='signup'){const row=await store.get('SELECT * FROM students WHERE id=?',t.studentId);if(!id){id=randomUUID();await store.run('INSERT INTO users(id,org_id,email,name,role,password_hash) VALUES (?,?,?,?,?,?)',id,t.orgId,t.email,row.name,'student',password);}else if((await store.run('UPDATE users SET password_hash=? WHERE id=? AND active=1 AND org_id=? AND role=? AND email=?',password,id,t.orgId,'student',address)).changes!==1)return invalid();if((await store.run('UPDATE students SET user_id=?,revision=revision+1 WHERE id=? AND org_id=? AND email=? AND user_id IS NULL',id,row.id,t.orgId,address)).changes!==1)return invalid();await store.run('UPDATE invitations SET consumed_at=? WHERE org_id=? AND email=? AND consumed_at IS NULL',now(),t.orgId,address);}
    else if((await store.run('UPDATE users SET password_hash=? WHERE id=? AND active=1 AND org_id=? AND role=? AND email=?',password,id,t.orgId,t.userRole,address)).changes!==1)return invalid();
    await store.run('DELETE FROM sessions WHERE user_id=?',id);await revokeLocked(t);await audit({id,org_id:t.orgId},t.studentId,'password-access.'+(t.kind==='signup'?'account-created':'password-reset'));});
   return {status:200,data:{completed:true,message:'Senha definida. Entre com seu e-mail e a senha que você escolheu.'},clearSession:true};
  }return null;
 }
 async function handle(actor,req,route){if(route==='/api/local/access/capabilities'&&req.method==='GET'){if(actor.role!=='admin')deny(403,'Autorizações restritas à administração.');return {status:200,data:{levels:ACCESS_LEVELS,emailAvailable:available(),source:'manual'}};}
  const m=/^\/api\/local\/students\/([a-f0-9-]{36})\/access$/.exec(route);if(!m)return null;if(actor.role!=='admin')deny(403,'Autorizações restritas à administração.');const row=await student(actor,m[1]);
  if(req.method==='GET'){const state=await policy.state(row),jobs=await store.all('SELECT * FROM operations WHERE request_hash=?',MAIL);const latest=jobs.map(decode).filter(j=>j.target.orgId===row.org_id&&j.target.studentId===row.id).sort((a,b)=>b.createdAt-a.createdAt)[0];return {status:200,data:{access:state,delivery:latest?{state:latest.state,kind:latest.kind,createdAt:latest.createdAt}:null}};}
  if(req.method==='PUT'){const body=await read(req);exact(body,['level','expiresAt','enabled','sequence','confirmed']);if(body.confirmed!==true)deny(400,'Confirme a autorização manual.');return mutation(actor,req,body,async()=>{await store.lockStudent(row.id);const current=await student(actor,row.id),g=await policy.grantLocked(actor,current,body);await revokeLocked({orgId:row.org_id,email:row.email,studentId:row.id,userId:row.user_id});return {status:200,data:{access:g}};});}deny(405,'Método não permitido.');
 }
 return {available,handlePublic,handle,welcomeLocked,flush,throttleRegistration:actor=>throttle('access-register-admin:'+actor.id,10),async close(){closed=true;clearInterval(timer);abort.abort();try{await draining;}catch{/* No provider errors in logs. */}}};
}
