import {INTAKE_VERSION,CONSENT_VERSION,validateIntake} from '../public/sim/intake-fields.js';
export const TRAINING_INPUT_FIELDS=Object.freeze(['age','height_m','weight_kg','main_goal','training_history','current_training','environment','days','schedule','liked_exercises','difficult_exercises','injuries','fractures','restrictions']);
export function proposalSpecs({store,deny,exact,text,student,safety,configuration}){
 const mode=()=>configuration.mode||'local-simulation';
 const method=kind=>configuration.methodologies?.[kind]||configuration.methodology;
 async function intakeFor(row){const a=await store.get('SELECT * FROM anamneses WHERE student_id=? AND org_id=?',row.id,row.org_id);if(!a?.training_consent||a.version!==INTAKE_VERSION||a.status!=='complete'||a.reviewed_revision!==a.revision)deny(409,'Conclua e revise a anamnese atual antes de preparar uma proposta.');let answers;try{answers=validateIntake(JSON.parse(a.answers),{complete:true});}catch{deny(409,'Respostas atuais incompletas ou inválidas.');}const c=await safety.consent(row,{kind:'training',mode:mode()});return {a,answers,c};}
 async function trainingCurrent(actor,id){const row=await student(actor,id),reviewer=await store.get("SELECT id FROM users WHERE id=? AND org_id=? AND role='coach' AND active=1",row.coach_id,row.org_id);
  if(!reviewer||!(actor.role==='coach'&&actor.id===row.coach_id||actor.role==='admin'))deny(403,'Proposta exige personal vinculado ativo ou supervisão administrativa autorizada.');
  const {a,answers,c}=await intakeFor(row);if(a.reviewed_by!==reviewer.id)deny(409,'Revisão exige o personal atualmente vinculado.');if(actor.role==='admin'&&a.consent_version!==CONSENT_VERSION)deny(403,'Supervisão administrativa da anamnese não autorizada.');if(c.enabled!==true||c.anamnesisRevision!==a.revision)deny(409,'O aluno precisa escolher a finalidade específica desta proposta.');
  const risk=await safety.risk(row,a);if(mode()==='external-reviewed'&&risk.required&&!risk.resolved)deny(409,'Resolva o sinal com decisão profissional antes de geração externa.');
  return {row,intake:a,consent:c,risk,facts:Object.fromEntries(TRAINING_INPUT_FIELDS.filter(k=>k in answers).map(k=>[k,answers[k]])),references:{studentRevision:row.revision,coach:row.coach_id,user:row.user_id,intakeRevision:a.revision,reviewer:a.reviewed_by,consentSequence:c.sequence,riskSequence:risk.sequence||0,riskResolved:risk.resolved}};
 }
 function trainingValidate(payload,c){
  const canonical=Object.hasOwn(payload||{},'sessions');exact(payload,canonical?['title','daysPerWeek','sessions']:['title','daysPerWeek','exercises']);text(payload.title,2,100);
  if(!canonical&&mode()!=='local-simulation')deny(400,'Proposta externa exige sessões completas.');
  if(!Number.isInteger(payload.daysPerWeek)||payload.daysPerWeek<1||payload.daysPerWeek>c.facts.days)deny(400,'Frequência deve respeitar os dias disponíveis informados.');
  const sessions=canonical?payload.sessions:[{id:'session-1',name:'Sessão de teste',weekday:1,exercises:payload.exercises}];
  if(!Array.isArray(sessions)||sessions.length<1||sessions.length>7||canonical&&sessions.length!==payload.daysPerWeek||new Set(sessions.map(s=>s.id)).size!==sessions.length||new Set(sessions.map(s=>s.weekday)).size!==sessions.length)deny(400,'Cada dia prescrito exige uma sessão única.');
  const output=sessions.map(s=>{if(canonical)exact(s,['id','name','weekday','exercises']);if(typeof s.id!=='string'||! /^[a-zA-Z0-9_-]{1,80}$/.test(s.id)||!Number.isInteger(s.weekday)||s.weekday<1||s.weekday>7)deny(400,'Sessão ou dia semanal inválido.');text(s.name,2,100);
   if(!Array.isArray(s.exercises)||s.exercises.length<1||s.exercises.length>12)deny(400,'Use 1-12 exercícios por sessão.');
   const exercises=s.exercises.map(e=>{exact(e,['exerciseId','sets','reps','restSeconds','rir','reason','evidence','ruleId',...(canonical?['alternatives']:[])]);const item=method('training').exercises.find(x=>x.id===e.exerciseId&&x.status==='approved');if(!item||!item.environments.some(v=>c.facts.environment.includes(v)))deny(400,'Exercício não aprovado ou incompatível com o ambiente informado.');
    if(!Number.isInteger(e.sets)||e.sets<1||e.sets>10||!Number.isInteger(e.reps)||e.reps<1||e.reps>50||!Number.isInteger(e.restSeconds)||e.restSeconds<0||e.restSeconds>600||!Number.isInteger(e.rir)||e.rir<0||e.rir>10)deny(400,'Parâmetros de exercício inválidos.');
    if(!Array.isArray(e.evidence)||e.evidence.length<1||e.evidence.length>5||e.evidence.some(k=>!Object.hasOwn(c.facts,k))||!method('training').rules.some(r=>r.id===e.ruleId))deny(400,'Justifique cada exercício com evidências e referência disponíveis.');const rule=method('training').rules.find(r=>r.id===e.ruleId),source=method('training').sources?.find(s=>s.id===rule.sourceId);if(canonical&&(!source||! /^[a-f0-9]{64}$/.test(source.sha256)||!source.version||!rule.section))deny(400,'Source provenance unavailable');const reference=source?{ruleId:rule.id,sourceId:source.id,sourceVersion:source.version,sourceSha256:source.sha256,section:rule.section}:undefined;
    let alternatives;if(canonical){if(!Array.isArray(e.alternatives)||e.alternatives.length>4||new Set(e.alternatives.map(a=>a.exerciseId)).size!==e.alternatives.length)deny(400,'Alternatives require distinct catalog IDs');alternatives=e.alternatives.map(a=>{exact(a,['exerciseId','reason','evidence','ruleId']);const alternative=method('training').exercises.find(x=>x.id===a.exerciseId&&x.status==='approved');if(!alternative||a.exerciseId===e.exerciseId||!item.allowedAlternativeIds?.includes(a.exerciseId)||!alternative.environments.some(v=>c.facts.environment.includes(v))||a.ruleId!==e.ruleId||!Array.isArray(a.evidence)||!a.evidence.length||a.evidence.some(k=>!Object.hasOwn(c.facts,k)))deny(400,'Alternative is not explicitly reviewed for this exercise and context');return {...a,name:text(alternative.name,2,100),reason:text(a.reason,8,500),reference};});}
    return {...e,name:text(item.name,2,100),reason:text(e.reason,8,500),...(reference?{reference}:{}),...(canonical?{alternatives}: {})};
   });return {...s,exercises};
  });return {title:payload.title.trim(),daysPerWeek:payload.daysPerWeek,sessions:output,exercises:output.flatMap(s=>s.exercises),canonical};
 }
 const trainingEditable=v=>{const strip=exercises=>exercises.map(({name,reference,...e})=>{void name;void reference;return {...e,...(e.alternatives?{alternatives:e.alternatives.map(({name,reference,...a})=>{void name;void reference;return a;})}: {})};});return v.canonical?{title:v.title,daysPerWeek:v.daysPerWeek,sessions:v.sessions.map(s=>({...s,exercises:strip(s.exercises)}))}:{title:v.title,daysPerWeek:v.daysPerWeek,exercises:strip(v.exercises)};};
 return {training:{current:trainingCurrent,validate:trainingValidate,editable:trainingEditable}};
}
