export const SERVICE_HOUR=3600000;
export const serviceDeadlines=start=>({targetAt:start+48*SERVICE_HOUR,promisedAt:start+72*SERVICE_HOUR,timeZone:'America/Sao_Paulo'});
export const completeOnboarding=o=>!!o&&['Hipertrofia','Condicionamento','Qualidade de vida'].includes(o.goal)&&Number.isInteger(o.days)&&o.days>=1&&o.days<=7&&['Iniciante','Intermediário','Avançado'].includes(o.experience)&&typeof o.context==='string'&&o.context.length<=1000;
export function serviceFlow({store,now,deny,exact,text,read,mutation,student,audit,intakeState}){
 const admin=actor=>{if(actor.role!=='admin')deny(403,'Central restrita ao administrador da organização.');};
 async function changed(actor,id,revision,kind='onboarding'){const c=await store.get('SELECT * FROM service_cases WHERE student_id=? AND org_id=?',id,actor.org_id);if(!c)return;await store.run("UPDATE service_cases SET onboarding_revision=?,reviewed_revision=NULL,status='needs_info',delivered_at=NULL,revision=revision+1,updated_at=? WHERE student_id=? AND org_id=?",revision,now(),id,actor.org_id);await audit(actor,id,'service.'+kind+'.changed:'+c.onboarding_revision+'>'+revision);}
 async function snapshot(row,actor){
  const c=await store.get('SELECT * FROM service_cases WHERE student_id=? AND org_id=?',row.id,actor.org_id);const intake=await intakeState(row.id,actor.org_id);if(!c)return {started:false,timeZone:'America/Sao_Paulo',anamnesisComplete:intake.complete,anamnesisReviewPending:intake.reviewPending};
  const training=await store.all('SELECT id,title,status,revision,published_at FROM plans WHERE student_id=? ORDER BY published_at DESC,id DESC',row.id),nutrition=await store.all('SELECT id,title,status,revision,published_at FROM nutrition_plans WHERE student_id=? AND org_id=? ORDER BY published_at DESC,id DESC',row.id,actor.org_id);
  const r={anamnesisComplete:intake.complete,anamnesisReviewPending:intake.reviewPending,started:true,startedAt:c.started_at,targetAt:c.target_at,promisedAt:c.promised_at,timeZone:'America/Sao_Paulo',status:c.status,revision:c.revision,onboardingRevision:c.onboarding_revision,reviewPending:c.reviewed_revision!==c.onboarding_revision,deliveredAt:c.delivered_at,trainingAvailable:training.some(p=>p.status==='published'&&p.published_at>=c.started_at),nutritionAvailable:nutrition.some(p=>p.status==='published'&&p.published_at>=c.started_at),targetLate:c.status!=='delivered'&&now()>=c.target_at,promiseLate:c.status!=='delivered'&&now()>=c.promised_at};
  if(actor.role!=='student'){r.responsibleId=c.responsible_id;r.note=c.note;r.plans={training,nutrition};r.pending=[];if(!intake.complete)r.pending.push('Complementar e concluir anamnese original');if(intake.reviewPending)r.pending.push('Revisão humana da anamnese pelo personal');if(r.reviewPending)r.pending.push('Revisar respostas da anamnese');if(!c.responsible_id)r.pending.push('Definir responsável pelo atendimento');if(!r.trainingAvailable)r.pending.push('Publicar treino após revisão profissional');if(!r.nutritionAvailable)r.pending.push('Publicar alimentação após revisão do nutricionista');const q=await store.get("SELECT COUNT(*) AS n FROM nutrition_requests WHERE student_id=? AND org_id=? AND status='pending'",row.id,actor.org_id);r.pendingNutritionRequests=Number(q.n);if(r.pendingNutritionRequests)r.pending.push('Responder solicitações de alimentação');}
  return r;
 }
 async function startCase(actor,s){if(await store.get('SELECT student_id FROM service_cases WHERE student_id=?',s.id))return {status:200,data:{service:await snapshot(s,actor),startedNow:false}};const start=now(),due=serviceDeadlines(start);await store.run('INSERT INTO service_cases(student_id,org_id,started_at,target_at,promised_at,onboarding_revision,status,updated_at) VALUES (?,?,?,?,?,?,?,?)',s.id,actor.org_id,start,due.targetAt,due.promisedAt,s.revision,'waiting',start);await audit(actor,s.id,'service.started:revision='+s.revision);return {status:201,data:{service:await snapshot(s,actor),startedNow:true}};}
 async function handle(actor,req,route){
  if(route==='/api/local/crm'&&req.method==='GET'){admin(actor);const rows=await store.all('SELECT * FROM students WHERE org_id=? ORDER BY name',actor.org_id),entries=[];for(const row of rows)entries.push({id:row.id,name:row.name,email:row.email,coachId:row.coach_id,nutritionId:row.nutrition_id,internalNote:row.internal_note,service:await snapshot(row,actor)});const history=await store.all('SELECT id,actor_id,student_id,event,created_at FROM audit WHERE org_id=? ORDER BY created_at DESC,id DESC LIMIT 200',actor.org_id);return {status:200,data:{entries,history,timeZone:'America/Sao_Paulo',targetHours:48,promiseHours:72}};}
  const m=/^\/api\/local\/students\/([a-f0-9-]{36})\/(service|onboarding\/complete)$/.exec(route);if(!m)return null;const row=await student(actor,m[1]);
  if(m[2]==='service'&&req.method==='GET')return {status:200,data:{service:await snapshot(row,actor)}};
  if(m[2]==='onboarding/complete'&&req.method==='POST'){
   if(!['admin','coach','student'].includes(actor.role))deny(403,'Conclusão exige aluno ou responsável pelo cadastro.');const b=await read(req);exact(b,['revision','confirmed']);if(b.confirmed!==true||!Number.isInteger(b.revision))deny(400,'Confirme a conclusão das respostas.');
   return await mutation(actor,req,b,async()=>{await store.lockStudent(row.id);const s=await student(actor,row.id);if(b.revision!==s.revision)deny(409,'Respostas mudaram. Recarregue.');if(!completeOnboarding(JSON.parse(s.onboarding)))deny(400,'Preencha e salve todas as respostas antes de concluir.');if(!(await intakeState(s.id,actor.org_id)).complete)deny(400,'Conclua a anamnese original; quatro campos básicos não são suficientes.');return startCase(actor,s);});
  }
  if(m[2]==='service'&&req.method==='PUT'){
   admin(actor);const b=await read(req);exact(b,['revision','status','responsibleId','note','confirmed','reviewedOnboarding']);if(b.confirmed!==true||typeof b.reviewedOnboarding!=='boolean'||!Number.isInteger(b.revision)||!['waiting','in_progress','needs_info','delivered'].includes(b.status))deny(400,'Confirme estado e revisão do atendimento.');const note=text(b.note,0,1000);if(b.responsibleId!==null&&(typeof b.responsibleId!=='string'||! /^[a-f0-9-]{36}$/.test(b.responsibleId)))deny(400,'Responsável inválido.');
   return await mutation(actor,req,b,async()=>{await store.lockStudent(row.id);const s=await student(actor,row.id),c=await store.get('SELECT * FROM service_cases WHERE student_id=? AND org_id=?',s.id,actor.org_id);if(!c)deny(409,'Conclua a anamnese antes de iniciar atendimento.');if(c.revision!==b.revision)deny(409,'Atendimento mudou. Recarregue.');if(b.responsibleId&&!await store.get("SELECT id FROM users WHERE id=? AND org_id=? AND active=1 AND role IN ('admin','coach','nutrition')",b.responsibleId,actor.org_id))deny(400,'Responsável ativo da mesma organização obrigatório.');const reviewed=b.reviewedOnboarding?c.onboarding_revision:c.reviewed_revision;
    if(b.status==='delivered'){const state=await snapshot(s,actor);if(!state.anamnesisComplete||state.anamnesisReviewPending||!b.responsibleId||reviewed!==c.onboarding_revision||!state.trainingAvailable||!state.nutritionAvailable||state.pendingNutritionRequests)deny(409,'Entrega exige respostas revisadas, responsável, ambos os planos publicados e solicitações resolvidas.');}
    await store.run('UPDATE service_cases SET status=?,responsible_id=?,note=?,reviewed_revision=?,delivered_at=?,revision=revision+1,updated_at=? WHERE student_id=? AND org_id=? AND revision=?',b.status,b.responsibleId,note,reviewed,b.status==='delivered'?(c.delivered_at||now()):null,now(),s.id,actor.org_id,b.revision);await audit(actor,s.id,'service.updated:'+JSON.stringify({before:{status:c.status,responsibleId:c.responsible_id,revision:c.revision},after:{status:b.status,responsibleId:b.responsibleId,revision:c.revision+1,reviewedRevision:reviewed},noteChanged:note!==c.note}));return {status:200,data:{service:await snapshot(s,actor)}};});
  }
  return null;
 }
 return {handle,changed,snapshot,start:startCase};
}
