import {createHash} from 'node:crypto';
import {readFileSync,realpathSync,statSync,createReadStream} from 'node:fs';
import path from 'node:path';
// Programmatic opt-in only. A reviewed association is independent of exercise prescription.
export function trainingVideoFlow({store,now,deny,student,access,security,configuration={},methodology,exact,text,read,mutation,audit}){
 const enabled=()=>!security.production&&configuration.enabled===true&&configuration.expiresAt>now()&&configuration.expiresAt-now()<=86400000;
 const fixtureOnly=configuration.fixtureOnly===true;
 const sha=value=>createHash('sha256').update(value).digest('hex');
 function media(id){const item=configuration.media?.find(v=>v.id===id);if(!item||! /^[a-f0-9-]{36}$/.test(id)||! /^[a-f0-9]{64}$/.test(item.sha256)||typeof item.filename!=='string'||path.basename(item.filename)!==item.filename||!item.filename.endsWith('.mp4'))return null;
  try{const root=realpathSync(configuration.directory),filename=realpathSync(path.join(root,item.filename)),stat=statSync(filename);if(!filename.startsWith(root+path.sep)||!stat.isFile()||stat.size<1||stat.size>50000000||sha(readFileSync(filename))!==item.sha256)return null;return {...item,filename,size:stat.size};}catch{return null;}
 }
 const catalogStamp=()=>sha(JSON.stringify({methodology,media:configuration.media,fixtureOnly}));
 const reviewedExercises=()=>methodology?.exercises?.filter(e=>e.status==='approved'&&/^[a-f0-9-]{36}$/.test(e.id))||[];
 async function decisions(org){const rows=await store.all("SELECT result FROM operations WHERE request_hash='training-video-review-v1'");const result=new Map();for(const r of rows){const v=JSON.parse(r.result);if(v.orgId===org&&(!result.has(v.exerciseId)||result.get(v.exerciseId).revision<v.revision))result.set(v.exerciseId,v);}return result;}
 async function editor(actor,req,route){if(route!=='/api/local/training-videos/catalog'&&route!=='/api/local/training-videos/review')return null;if(actor.role!=='admin')deny(403,'Revisão de associação exige administrador.');const scoped=methodology?.orgId===actor.org_id;
  if(route.endsWith('/catalog')){if(req.method!=='GET')deny(405,'Use consulta de catálogo.');if(!enabled()||!scoped)return {status:200,data:{available:false,fixtureOnly,exercises:[],media:[],associations:[]}};const associations=[...(await decisions(actor.org_id)).values()].map(v=>({...v,currentCatalog:v.catalogStamp===catalogStamp()}));return {status:200,data:{available:true,fixtureOnly,exercises:reviewedExercises().map(e=>({id:e.id,name:e.name})),media:(configuration.media||[]).filter(v=>media(v.id)).map(v=>({id:v.id,label:v.label||'Vídeo do catálogo local',sha256:v.sha256,url:'/api/local/training-videos/preview/'+v.id})),associations}};}
  if(req.method!=='PUT')deny(405,'Use revisão explícita.');if(!enabled())deny(503,'Catálogo de vídeos desativado.');if(!scoped)deny(404,'Catálogo não encontrado.');const body=await read(req);exact(body,['exerciseId','videoId','revision','decision','note','confirmed']);if(body.confirmed!==true||!Number.isInteger(body.revision)||body.revision<0||!['pending','approved','rejected'].includes(body.decision))deny(400,'Confirme a decisão e revisão atuais.');const note=text(body.note,8,500),stamp=catalogStamp();
  const validate=()=>{if(!enabled()||stamp!==catalogStamp())deny(409,'Catálogo ou gate mudou. Recarregue.');if(!reviewedExercises().some(e=>e.id===body.exerciseId)||!media(body.videoId))deny(400,'Use IDs existentes do catálogo conferido.');};validate();return mutation(actor,req,body,async()=>{await store.lockEmail('training-video-review:'+actor.org_id+':'+body.exerciseId);validate();const prior=(await decisions(actor.org_id)).get(body.exerciseId);if((prior?.revision||0)!==body.revision)deny(409,'Associação mudou. Recarregue antes de decidir.');const association={orgId:actor.org_id,exerciseId:body.exerciseId,videoId:body.videoId,revision:body.revision+1,decision:body.decision,note,reviewedBy:actor.id,reviewedAt:now(),catalogStamp:stamp,fixtureOnly};await store.run('INSERT INTO operations VALUES (?,?,?,?,?)',actor.id,'training-video-review-'+sha(JSON.stringify(association)),'training-video-review-v1',200,JSON.stringify(association));await audit(actor,null,'training.video.association.'+body.decision);return {status:200,data:{association,publicationChanged:false}};});
 }
 async function snapshot(actor,plan,row){if(!enabled())return;const content=JSON.parse(plan.content),ids=new Set((content.exercises||[]).map(e=>e.exerciseId)),decided=await decisions(row.org_id);const associations=[];
  const candidates=[...decided.values()].filter(v=>v.decision==='approved'&&v.catalogStamp===catalogStamp()).map(v=>({...v,approved:true}));
  // Legacy programmatic associations are only retained for explicitly fictitious tests.
  if(fixtureOnly)for(const a of configuration.associations||[])if(!decided.has(a.exerciseId))candidates.push(a);
  for(const a of candidates){if(a.orgId!==row.org_id||a.approved!==true||!a.reviewedAt||a.reviewedAt>now()||!ids.has(a.exerciseId))continue;const reviewer=await store.get("SELECT id,role FROM users WHERE id=? AND org_id=? AND role IN ('admin','coach') AND active=1",a.reviewedBy,row.org_id),m=media(a.videoId);if(!reviewer||reviewer.role==='coach'&&a.reviewedBy!==row.coach_id||!m)continue;associations.push({exerciseId:a.exerciseId,videoId:m.id,sha256:m.sha256,reviewedBy:a.reviewedBy,reviewedAt:a.reviewedAt,fixtureOnly});}
  const result={marker:'training-video-snapshot-v1',planId:plan.id,studentId:row.id,orgId:row.org_id,associations,at:now()};await store.run('INSERT INTO operations VALUES (?,?,?,?,?)',actor.id,'training-videos-'+plan.id,sha(JSON.stringify(result)),200,JSON.stringify(result));
 }
 function sendMedia(req,res,m){let start=0,end=m.size-1,status=200;const range=req.headers.range;if(range){const parsed=/^bytes=(\d+)-(\d*)$/.exec(range);if(!parsed){res.writeHead(416,{'Content-Range':'bytes */'+m.size});res.end();return true;}start=Number(parsed[1]);end=parsed[2]?Number(parsed[2]):end;if(!Number.isSafeInteger(start)||!Number.isSafeInteger(end)||start>end||end>=m.size){res.writeHead(416,{'Content-Range':'bytes */'+m.size});res.end();return true;}status=206;}
  res.writeHead(status,{'Content-Type':'video/mp4','Content-Length':end-start+1,'Accept-Ranges':'bytes','Cache-Control':'no-store',...(status===206?{'Content-Range':'bytes '+start+'-'+end+'/'+m.size}:{})});const stream=createReadStream(m.filename,{start,end});stream.on('error',()=>res.destroy());res.on('close',()=>stream.destroy());stream.pipe(res);return true;}
 async function handle(actor,req,res,route){const preview=/^\/api\/local\/training-videos\/preview\/([a-f0-9-]{36})$/.exec(route);if(preview){if(req.method!=='GET')deny(405,'Use consulta de vídeo.');if(actor.role!=='admin')deny(403,'Prévia restrita à revisão administrativa.');if(!enabled()||methodology?.orgId!==actor.org_id)deny(404,'Catálogo não encontrado.');const item=media(preview[1]);if(!item)deny(404,'Vídeo não encontrado.');return sendMedia(req,res,item);}
  const match=/^\/api\/local\/plans\/([a-f0-9-]{36})\/videos(?:\/([a-f0-9-]{36}))?$/.exec(route);if(!match)return false;if(req.method!=='GET')deny(405,'Use consulta de vídeo.');if(!['student','coach','admin'].includes(actor.role))deny(403,'Vídeos exigem acesso ao treino.');const plan=await store.get('SELECT * FROM plans WHERE id=?',match[1]);if(!plan)deny(404,'Treino não encontrado.');const row=await student(actor,plan.student_id);if(actor.role==='student'){await access.assertActive(row,'training');if(plan.status!=='published')deny(404,'Treino não publicado.');}
  const saved=await store.get('SELECT result FROM operations WHERE operation_key=?','training-videos-'+plan.id);let data;try{data=JSON.parse(saved?.result||'null');}catch{data=null;}const valid=data?.marker==='training-video-snapshot-v1'&&data.orgId===actor.org_id&&data.studentId===row.id&&data.planId===plan.id;
  const available=enabled()&&valid;const current=available?await decisions(row.org_id):new Map();const associations=available?data.associations.filter(a=>{const d=current.get(a.exerciseId);return a.fixtureOnly===fixtureOnly&&(!d||d.decision==='approved'&&d.videoId===a.videoId&&d.catalogStamp===catalogStamp()&&d.fixtureOnly===fixtureOnly);}):[];
  if(!match[2]){res.writeHead(200,{'Content-Type':'application/json; charset=utf-8'});res.end(JSON.stringify({available,associations:associations.map(a=>({...a,url:'/api/local/plans/'+plan.id+'/videos/'+a.videoId})),notice:fixtureOnly?'ASSOCIAÇÕES FICTÍCIAS DE TESTE — validação técnica, sem aprovação real de Bruno.':'Somente associações explicitamente conferidas; catálogo de vídeos desligado por padrão.'}));return true;}
  const association=associations.find(a=>a.videoId===match[2]),m=association&&media(match[2]);if(!m||m.sha256!==association.sha256)deny(404,'Vídeo não autorizado para este treino.');return sendMedia(req,res,m);
 }
 return {snapshot,handle,editor};
}
