import test from 'node:test';
import assert from 'node:assert/strict';
import {JSDOM} from 'jsdom';
import {sessionsFixture} from './training-sessions-fixtures.mjs';
import {FIXTURE_PASSWORD} from './backend-fixtures.mjs';
import {mountPersistent} from '../public/sim/persistent.js';
test('UI complete sessions: prepare, adjust frequency, confirm, create immutable version, publish and execute one selected session',async()=>{
 const f=await sessionsFixture();await f.consent();const dom=new JSDOM('<div id="local-app"></div><p id="local-status"></p>',{url:f.origin+'/local'}),originalFetch=globalThis.fetch,originalForm=globalThis.FormData;globalThis.FormData=dom.window.FormData;let cookie='',unmount;globalThis.fetch=async(url,options)=>{const r=await originalFetch(String(url).startsWith('http')?url:f.origin+url,{...options,headers:{...options?.headers,...(options?.body?{Origin:f.origin}:{}),...(cookie?{Cookie:cookie}:{})}});if(r.headers.get('set-cookie'))cookie=r.headers.get('set-cookie').split(';')[0];return r;};const q=selector=>{const node=dom.window.document.querySelector(selector);assert.ok(node,selector);return node;};const wait=async predicate=>{for(let i=0;i<200;i++){if(predicate())return;await new Promise(r=>setTimeout(r,15));}assert.fail('UI did not settle: '+dom.window.document.querySelector('#local-status')?.textContent);};const submit=form=>q(form).dispatchEvent(new dom.window.Event('submit',{bubbles:true,cancelable:true}));const login=async role=>{q('#login [name=email]').value=role+'@fixture.invalid';q('#login [name=password]').value=FIXTURE_PASSWORD;submit('#login');await wait(()=>dom.window.document.querySelector('[data-action=logout]'));};
 try{unmount=await mountPersistent(dom.window.document);await login('coach');q('[data-view=training]').click();q('.training-proposal-prepare [name=confirmed]').checked=true;submit('.training-proposal-prepare');await wait(()=>dom.window.document.querySelector('.training-proposal-confirm'));assert.equal(dom.window.document.querySelectorAll('.training-proposal-confirm .proposal-session').length,3);assert.equal(dom.window.document.querySelectorAll('.training-proposal-confirm select[name^=alternative-]').length,12);assert.equal(f.store.get('SELECT COUNT(*) AS n FROM plans').n,0);q('.training-proposal-confirm [name=daysPerWeek]').value='2';q('.training-proposal-confirm [name=sessionEnabled-2]').checked=false;q('.training-proposal-confirm [name=sets-0-0]').value='3';q('.training-proposal-confirm [name=confirmed]').checked=true;submit('.training-proposal-confirm');await wait(()=>f.store.get('SELECT COUNT(*) AS n FROM plans').n===1&&dom.window.document.querySelector('.training-draft-edit'));const original={...f.store.get('SELECT * FROM plans')};assert.equal(JSON.parse(original.content).sessions.length,2);assert.equal(JSON.parse(original.content).sessions[0].exercises[0].sets,3);assert.match(q('.training-draft-edit').textContent,/fixture-source/);
  q('.training-draft-edit [name=title]').value='Nova versão por edição UI';q('.training-draft-edit [name=changeReason]').value='Ajuste fictício conferido no editor de sessões.';q('.training-draft-edit [name=confirmed]').checked=true;submit('.training-draft-edit');await wait(()=>f.store.get('SELECT COUNT(*) AS n FROM plans').n===2);const latest=f.store.get('SELECT * FROM plans WHERE id<>?',original.id);assert.deepEqual({...f.store.get('SELECT * FROM plans WHERE id=?',original.id)},original);for(const [action,status] of [['submit','review'],['approve','approved'],['publish','published']]){await wait(()=>dom.window.document.querySelector('[data-plan="'+latest.id+'"][data-action="'+action+'"]'));q('[data-plan="'+latest.id+'"][data-action="'+action+'"]').click();await wait(()=>f.store.get('SELECT status FROM plans WHERE id=?',latest.id).status===status&&q('#local-status').textContent==='Operação concluída no servidor.');}
  q('[data-action=logout]').click();await wait(()=>dom.window.document.querySelector('#login'));await login('student');q('[data-view=training]').click();assert.equal(dom.window.document.querySelectorAll('[data-start-workout][data-session]').length,2);const selected=q('[data-start-workout][data-session]').dataset.session;q('[data-start-workout][data-session]').click();await wait(()=>f.store.get('SELECT COUNT(*) AS n FROM workouts').n===1&&dom.window.document.querySelector('.workout-set'));const prescription=JSON.parse(f.store.get('SELECT prescription FROM workouts').prescription);assert.equal(prescription.sessionId,selected);assert.equal(prescription.exercises.length,1);assert.equal(dom.window.localStorage.length,0);
 }finally{unmount?.();dom.window.close();globalThis.fetch=originalFetch;globalThis.FormData=originalForm;await f.close();}
});
