import test from 'node:test';
import assert from 'node:assert/strict';
import {JSDOM} from 'jsdom';
import {accessUI} from '../public/sim/access-ui.js';
test('signup/reset UI erases token fragment, never stores it and submits no access role',async()=>{
 const token='a'.repeat(43),dom=new JSDOM('<main></main>',{url:'https://shape.example.test/local#password='+token}),root=dom.window.document,calls=[];let completed=false,user=null;const saved=globalThis.FormData;globalThis.FormData=dom.window.FormData;
 const ui=accessUI({root,esc:x=>String(x??''),getUser:()=>user,getStudent:()=>({id:'fixture-student'}),onPasswordComplete:()=>{completed=true;},perform:fn=>fn(),api:async(route,body)=>{calls.push({route,body});if(route==='password-access/capabilities')return {emailAvailable:true};if(route==='access/capabilities')return {emailAvailable:false,levels:[{id:'training',label:'Treino'},{id:'training-nutrition',label:'Treino e Nutrição'}]};if(route.endsWith('/access'))return {access:{mode:'manual',active:true,sequence:1,level:'training',expiresAt:null}};return {message:'Se autorizado, confira seu e-mail.'};}});
 try{assert.equal(dom.window.location.hash,'#define-password');assert.equal(dom.window.localStorage.length,0);root.querySelector('main').innerHTML=ui.passwordView();assert.ok(!root.body.innerHTML.includes(token));const form=root.querySelector('.access-password');form.elements.email.value='fixture@example.test';form.elements.password.value='Synthetic-password-only-2026!';form.elements.passwordConfirm.value=form.elements.password.value;await ui.submit({target:form,preventDefault(){}});assert.equal(completed,true);assert.deepEqual(Object.keys(calls.at(-1).body).sort(),['email','password','token']);assert.equal(calls.at(-1).body.token,token);assert.equal(ui.passwordView(),'');await ui.loadPublic();root.querySelector('main').innerHTML=ui.authForms();for(const kind of ['signup','reset']){const f=root.querySelector('.access-'+kind);f.elements.email.value='fixture@example.test';await ui.submit({target:f,preventDefault(){}});assert.deepEqual(calls.at(-1),{route:'password-access/'+kind+'/request',body:{email:'fixture@example.test'}});}user={role:'admin'};await ui.load();root.querySelector('main').innerHTML=ui.registrationFields();assert.equal(root.querySelector('select').options.length,2);assert.match(root.body.textContent,/Envio de e-mail pendente/);assert.match(ui.registrationMessage(),/use convite privado/);assert.equal(dom.window.localStorage.length,0);}finally{globalThis.FormData=saved;dom.window.close();}
});
test('disabled email UI keeps truthful unavailable copy and disabled buttons',async()=>{const dom=new JSDOM('<main></main>',{url:'http://127.0.0.1/local'});try{const ui=accessUI({root:dom.window.document,esc:String,getUser:()=>null,getStudent:()=>null,perform:fn=>fn(),api:async()=>({emailAvailable:false})});await ui.loadPublic();dom.window.document.querySelector('main').innerHTML=ui.authForms();assert.equal(dom.window.document.querySelectorAll('button:disabled').length,2);assert.match(dom.window.document.body.textContent,/convite privado/);}finally{dom.window.close();}});
