import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {rmSync} from 'node:fs';
import {isolatedFixture,FIXTURE_PASSWORD} from './backend-fixtures.mjs';
import {createLocalServer} from '../backend/server.mjs';
import {openLocalStore} from '../backend/store.mjs';
import {serviceDeadlines,SERVICE_HOUR} from '../backend/service-sla.mjs';
async function fixture(work){const f=await isolatedFixture();let clock=Date.parse('2026-10-31T23:30:00-03:00'),app,origin;async function start(){app=await createLocalServer({store:f.store,now:()=>clock,sessionMs:1000*SERVICE_HOUR,loginLimit:40});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));origin='http://127.0.0.1:'+app.server.address().port;}await start();const client=()=>{let cookie='';return {async request(path,body,method='POST',key=randomUUID()){const r=await fetch(origin+'/api/local/'+path,{method:body===undefined?'GET':method,headers:{Origin:origin,'Content-Type':'application/json','Idempotency-Key':key,Cookie:cookie},body:body===undefined?undefined:JSON.stringify(body)});if(r.headers.get('set-cookie'))cookie=r.headers.get('set-cookie').split(';')[0];return {status:r.status,data:await r.json()};},login(role){return this.request('login',{email:role.toLowerCase()+'@fixture.invalid',password:FIXTURE_PASSWORD});}};};try{await work({...f,client,advance:ms=>clock+=ms,get now(){return clock;},restart:async()=>{await app.close();f.store=openLocalStore(f.filename);await start();}});}finally{await app.close();rmSync(f.directory,{recursive:true,force:true});}}
const answers={goal:'Hipertrofia',days:3,experience:'Iniciante',context:'Synthetic answers only'};
const route=f=>'students/'+f.ids.studentRecord;
const update=(revision,extra={})=>({revision,status:'in_progress',responsibleId:null,note:'Synthetic case note',confirmed:true,reviewedOnboarding:true,...extra});
test('SLA uses elapsed UTC hours across São Paulo month/year boundaries',()=>{const start=Date.parse('2026-12-31T23:30:00-03:00'),d=serviceDeadlines(start);assert.equal(d.targetAt-start,48*SERVICE_HOUR);assert.equal(d.promisedAt-start,72*SERVICE_HOUR);assert.equal(d.timeZone,'America/Sao_Paulo');const format=new Intl.DateTimeFormat('en-CA',{timeZone:d.timeZone,year:'numeric',month:'2-digit',day:'2-digit'});assert.equal(format.format(d.targetAt),'2027-01-02');assert.equal(format.format(d.promisedAt),'2027-01-03');});
test('SLA starts only after explicit complete answers, is concurrent/idempotent and survives restart',async()=>fixture(async f=>{const s=f.client();await s.login('student');const r=route(f);assert.equal((await s.request(r+'/service')).data.service.started,false);assert.equal((await s.request(r+'/onboarding/complete',{revision:1,confirmed:true})).status,400);assert.equal((await s.request('onboarding',{...answers,revision:1},'PUT')).status,200);assert.equal((await s.request(r+'/service')).data.service.started,false);assert.equal((await s.request(r+'/onboarding/complete',{revision:2,confirmed:false})).status,400);const key=randomUUID(),b={revision:2,confirmed:true};const results=await Promise.all([s.request(r+'/onboarding/complete',b,'POST',key),s.request(r+'/onboarding/complete',b,'POST',key)]);assert.deepEqual(results.map(v=>v.status),[201,201]);assert.deepEqual(results[0].data,results[1].data);const start=results[0].data.service.startedAt;assert.equal(f.store.get('SELECT COUNT(*) n FROM service_cases').n,1);assert.equal(f.store.get("SELECT COUNT(*) n FROM audit WHERE event LIKE 'service.started:%'").n,1);assert.equal((await s.request(r+'/onboarding/complete',{...b,revision:1},'POST',key)).status,409);f.advance(48*SERVICE_HOUR);await f.restart();const after=await s.request(r+'/service');assert.equal(after.status,200);assert.equal(after.data.service.startedAt,start);assert.equal(after.data.service.targetLate,true);assert.equal(after.data.service.promiseLate,false);assert.equal((await s.request(r+'/onboarding/complete',b)).data.startedNow,false);f.advance(24*SERVICE_HOUR);assert.equal((await s.request(r+'/service')).data.service.promiseLate,true);}));
test('CRM admin scope, own student summary, responsible validation, CAS and answer edits preserve deadlines',async()=>fixture(async f=>{const a=f.client(),s=f.client(),c=f.client(),n=f.client(),o=f.client();for(const [x,role] of [[a,'admin'],[s,'student'],[c,'coach'],[n,'nutrition'],[o,'outsider']])await x.login(role);const r=route(f);for(const x of [s,c,n,o])assert.equal((await x.request('crm')).status,403);await s.request('onboarding',{...answers,revision:1},'PUT');const initial=(await s.request(r+'/onboarding/complete',{revision:2,confirmed:true})).data.service;assert.equal((await o.request(r+'/service')).status,404);assert.equal((await s.request('students/'+f.ids.otherRecord+'/service')).status,404);assert.equal((await c.request(r+'/service',update(1),'PUT')).status,403);assert.equal((await a.request(r+'/service',update(1,{responsibleId:f.ids.outsider}),'PUT')).status,400);let result=await a.request(r+'/service',update(1,{responsibleId:f.ids.coach}),'PUT');assert.equal(result.status,200,JSON.stringify(result.data));assert.equal(result.data.service.reviewPending,false);assert.equal((await a.request(r+'/service',update(1),'PUT')).status,409);const student=(await s.request(r+'/service')).data.service;assert.equal(student.note,undefined);assert.equal(student.plans,undefined);assert.equal(student.responsibleId,undefined);f.advance(SERVICE_HOUR);await s.request('onboarding',{...answers,context:'Changed synthetic answer',revision:2},'PUT');result=await a.request(r+'/service');assert.equal(result.data.service.reviewPending,true);assert.equal(result.data.service.status,'needs_info');assert.equal(result.data.service.targetAt,initial.targetAt);assert.equal(result.data.service.promisedAt,initial.promisedAt);assert.equal(result.data.service.onboardingRevision,3);const central=(await a.request('crm')).data;assert.equal(central.entries.length,2);assert.ok(central.history.some(e=>e.event.startsWith('service.onboarding.changed:')));f.store.run("UPDATE users SET role='admin' WHERE id=?",f.ids.outsider);await o.login('outsider');assert.deepEqual((await o.request('crm')).data.entries,[]);assert.ok(!(await o.request('crm')).data.history.some(e=>e.student_id===f.ids.studentRecord));}));
test('delivery cannot be forced before both reviewed plans; published history stays immutable after answer edit',async()=>fixture(async f=>{const a=f.client(),s=f.client();await a.login('admin');await s.login('student');const r=route(f);await s.request('onboarding',{...answers,revision:1},'PUT');await s.request(r+'/onboarding/complete',{revision:2,confirmed:true});const delivery=update(1,{status:'delivered',responsibleId:f.ids.coach});assert.equal((await a.request(r+'/service',delivery,'PUT')).status,409);const old=randomUUID();f.store.run("INSERT INTO plans(id,student_id,author_id,title,content,status,published_at) VALUES (?,?,?,?,?,'published',?)",old,f.ids.studentRecord,f.ids.coach,'Old synthetic plan','{}',f.now-1);assert.equal((await a.request(r+'/service',delivery,'PUT')).status,409);const fresh=randomUUID(),food=randomUUID();f.store.run("INSERT INTO plans(id,student_id,author_id,title,content,status,published_at) VALUES (?,?,?,?,?,'published',?)",fresh,f.ids.studentRecord,f.ids.coach,'Synthetic reviewed plan','{}',f.now);f.store.run("INSERT INTO nutrition_plans(id,org_id,student_id,author_id,title,content,status,created_at,published_at) VALUES (?,?,?,?,?,?,'published',?,?)",food,f.store.get('SELECT org_id FROM students WHERE id=?',f.ids.studentRecord).org_id,f.ids.studentRecord,f.ids.nutrition,'Synthetic nutrition metadata','{}',f.now,f.now);const key=randomUUID();let delivered=await a.request(r+'/service',delivery,'PUT',key);assert.equal(delivered.status,200,JSON.stringify(delivered.data));assert.equal(delivered.data.service.status,'delivered');assert.equal((await a.request(r+'/service',delivery,'PUT',key)).status,200);await s.request('onboarding',{...answers,context:'New synthetic answers',revision:2},'PUT');delivered=await a.request(r+'/service');assert.equal(delivered.data.service.status,'needs_info');assert.equal(delivered.data.service.deliveredAt,null);assert.equal(f.store.get('SELECT status FROM plans WHERE id=?',fresh).status,'published');assert.equal(f.store.get('SELECT status FROM nutrition_plans WHERE id=?',food).status,'published');}));
