import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {rmSync} from 'node:fs';
import {isolatedFixture,FIXTURE_PASSWORD} from './backend-fixtures.mjs';
import {createLocalServer} from '../backend/server.mjs';
import {nutritionTotals} from '../backend/nutrition.mjs';
async function fixture(run){const f=await isolatedFixture();const app=await createLocalServer({store:f.store,loginLimit:30});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+app.server.address().port;const client=()=>{let cookie='';return {async request(path,body,method='POST',key=randomUUID()){const r=await fetch(origin+'/api/local/'+path,{method:body===undefined?'GET':method,headers:{Origin:origin,'Content-Type':'application/json','Idempotency-Key':key,Cookie:cookie},body:body===undefined?undefined:JSON.stringify(body)});if(r.headers.get('set-cookie'))cookie=r.headers.get('set-cookie').split(';')[0];return {status:r.status,data:await r.json()};},login(role){return this.request('login',{email:role.toLowerCase()+'@fixture.invalid',password:FIXTURE_PASSWORD});}};};try{const moduleResponse=await fetch(origin+'/sim/nutrition-ui.js');assert.equal(moduleResponse.status,200);assert.match(await moduleResponse.text(),/export function nutritionUI/);await run({...f,client});}finally{await app.close();rmSync(f.directory,{recursive:true,force:true,maxRetries:10,retryDelay:100});}}
const foodBody={name:'Synthetic composition',preparation:'cooked',per100g:{energyKcal:120,proteinG:10,carbsG:15,fatG:2},allergens:[],mayContain:[],provenance:{source:'Synthetic test fixture',reference:'Not a real food or diet',version:'1'}};
async function approvedFood(n,changes={}){const made=await n.request('nutrition/foods',{...foodBody,...changes});assert.equal(made.status,201,JSON.stringify(made.data));const result=await n.request('nutrition/foods/'+made.data.food.id+'/approve',{revision:1,sourceVerified:true});assert.equal(result.status,200);return result.data.food;}
const planBody=(base,alt)=>({title:'Synthetic reviewed plan',allergies:[],allergiesChecked:true,meals:[{name:'Synthetic meal',items:[{foodId:base.id,grams:150,alternatives:alt?[{foodId:alt.id,grams:100}]:[]}]}]});
test('nutrition integer totals preserve units, sum before rounding and distinguish source energy',()=>{const item={gramsTenths:1500,composition:{energyKcal:12000,proteinG:1000,carbsG:1500,fatG:200},alternatives:[]};assert.deepEqual(nutritionTotals([{items:[item]}]),{energyKcal:180,proteinG:15,carbsG:22.5,fatG:3,macroEnergyKcal:177});assert.equal(nutritionTotals([{items:[{...item,gramsTenths:1},{...item,gramsTenths:1}]}]).proteinG,.02);});
test('nutrition qualified responsibility, isolation, review, immutable publication, choices and request workflow',async()=>fixture(async f=>{const a=f.client(),n=f.client(),s=f.client(),coach=f.client(),other=f.client(),outsider=f.client();for(const [c,role] of [[a,'admin'],[n,'nutrition'],[s,'student'],[coach,'coach'],[other,'otherStudent'],[outsider,'outsider']])assert.equal((await c.login(role)).status,200);
assert.equal((await n.request('nutrition/foods',foodBody)).status,403);assert.equal((await a.request('nutrition/foods',foodBody)).status,403);assert.equal((await s.request('nutrition/credentials')).status,403);
assert.equal((await a.request('nutrition/credentials',{userId:f.ids.nutrition,registration:'FICTITIOUS TEST ONLY',verified:true,checkedRegistration:true,revision:0},'PUT')).status,200);
const base=await approvedFood(n),alt=await approvedFood(n,{name:'Synthetic alternative',preparation:'raw',per100g:{energyKcal:200,proteinG:20,carbsG:20,fatG:4}});const body=planBody(base,alt),route='students/'+f.ids.studentRecord+'/nutrition';
for(const [c,status] of [[a,403],[coach,403],[s,403]])assert.equal((await c.request(route,body)).status,status);
assert.equal((await n.request('students/'+f.ids.otherRecord+'/nutrition',body)).status,404);
let made=await n.request(route,body);assert.equal(made.status,201,JSON.stringify(made.data));let p=made.data.plan;assert.equal(p.content.meals[0].items[0].preparation,'cooked');assert.equal(p.totals.energyKcal,180);assert.equal((await s.request('nutrition/plans/'+p.id)).status,404);
assert.equal((await n.request('nutrition/plans/'+p.id+'/publish',{revision:p.revision})).status,409);
for(const action of ['submit','approve','publish']){const result=await n.request('nutrition/plans/'+p.id+'/'+action,{revision:p.revision,...(action==='approve'?{reviewed:true}:{})});assert.equal(result.status,200,JSON.stringify(result.data));p=result.data.plan;}
assert.equal((await s.request('nutrition/plans/'+p.id)).status,200);for(const c of [other,outsider])assert.equal((await c.request('nutrition/plans/'+p.id)).status,404);assert.equal((await coach.request('nutrition/plans/'+p.id)).status,403);
const admin=(await a.request('nutrition/plans/'+p.id)).data.plan;assert.equal(admin.clinicalDetailsRestricted,true);assert.equal(admin.content,undefined);assert.equal((await n.request('nutrition/plans/'+p.id,{...body,revision:p.revision},'PUT')).status,409);
const choice={mealIndex:0,itemIndex:0,optionIndex:1,planRevision:p.revision,revision:0};assert.equal((await s.request('nutrition/plans/'+p.id+'/choices',{...choice,optionIndex:2})).status,400);const competing=await Promise.all([s.request('nutrition/plans/'+p.id+'/choices',choice),s.request('nutrition/plans/'+p.id+'/choices',choice)]);assert.deepEqual(competing.map(r=>r.status).sort(),[200,409]);assert.equal((await s.request('nutrition/plans/'+p.id)).data.plan.totals.energyKcal,200);
const request=await s.request(route+'/requests',{planId:p.id,mealIndex:0,itemIndex:0,request:'Synthetic outside option request'});assert.equal(request.status,201);assert.equal(request.data.prescriptionChanged,false);assert.equal((await a.request('nutrition/requests/'+request.data.requestId+'/review',{revision:1,decision:'reviewed',response:'Synthetic response'})).status,403);const reviewed=await n.request('nutrition/requests/'+request.data.requestId+'/review',{revision:1,decision:'reviewed',response:'Create a new professionally reviewed version'});assert.equal(reviewed.status,200);assert.equal(reviewed.data.requiresNewReviewedPlan,true);assert.equal((await s.request('nutrition/plans/'+p.id)).data.plan.revision,p.revision);
assert.equal((await a.request('nutrition/credentials',{userId:f.ids.nutrition,registration:'FICTITIOUS TEST ONLY',verified:false,checkedRegistration:true,revision:1},'PUT')).status,200);assert.equal((await n.request(route,body)).status,403);assert.equal((await s.request('nutrition/plans/'+p.id)).status,200);
}));
test('nutrition rejects precision, raw/cooked ambiguity, unsafe alternatives and unreviewed sources',async()=>fixture(async f=>{const a=f.client(),n=f.client();await a.login('admin');await n.login('nutrition');await a.request('nutrition/credentials',{userId:f.ids.nutrition,registration:'FICTITIOUS TEST ONLY',verified:true,checkedRegistration:true,revision:0},'PUT');for(const change of [{preparation:'unknown'},{per100g:{...foodBody.per100g,proteinG:1.001}},{per100g:{...foodBody.per100g,proteinG:90,carbsG:90}},{allergens:['milk','milk']},{provenance:{source:'x',reference:'x',version:''}}])assert.equal((await n.request('nutrition/foods',{...foodBody,...change})).status,400);
const base=await approvedFood(n),unsafe=await approvedFood(n,{mayContain:['milk']}),route='students/'+f.ids.studentRecord+'/nutrition';const body=planBody(base,unsafe);assert.equal((await n.request(route,{...body,allergies:['milk']})).status,400);assert.equal((await n.request(route,{...body,allergiesChecked:false})).status,400);for(const grams of [0,-1,1.01,2001,'100']){const bad=planBody(base);bad.meals[0].items[0].grams=grams;assert.equal((await n.request(route,bad)).status,400);}const draft=(await n.request('nutrition/foods',foodBody)).data.food;assert.equal((await n.request(route,planBody(draft))).status,400);
let p=(await n.request(route,planBody(base))).data.plan;p=(await n.request('nutrition/plans/'+p.id+'/submit',{revision:p.revision})).data.plan;assert.equal((await n.request('nutrition/plans/'+p.id+'/approve',{revision:p.revision,reviewed:false})).status,400);p=(await n.request('nutrition/plans/'+p.id+'/approve',{revision:p.revision,reviewed:true})).data.plan;const edit=await n.request('nutrition/plans/'+p.id,{...planBody(base),revision:p.revision},'PUT');assert.equal(edit.status,200);assert.equal(edit.data.plan.status,'draft');assert.equal((await n.request('nutrition/plans/'+p.id+'/publish',{revision:edit.data.plan.revision})).status,409);
}));