import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {JSDOM} from 'jsdom';
import {persistentJourneyFixture,completePersistentJourney} from './persistent-journey-fixtures.mjs';
import {trainingVideoAdminUI} from '../public/sim/training-proposals-ui.js';
const catalog=f=>f.a.req('training-videos/catalog');
const review=(f,c,b)=>c.req('training-videos/review',b,'PUT');
function body(c,extra={}){return {exerciseId:c.exercises[0].id,videoId:c.media[0].id,revision:0,decision:'pending',note:'Conferência totalmente fictícia para teste técnico.',confirmed:true,...extra};}
test('video admin editor scopes existing catalog/preview, requires explicit decision, CAS/audit and fixture label survives restart',async()=>{const f=await persistentJourneyFixture();try{
 const c=(await catalog(f)).data;assert.equal(c.available,true);assert.equal(c.fixtureOnly,true);assert.equal(c.associations.length,0);assert.equal(c.media.length,1);assert.ok(!JSON.stringify(c).includes(f.directory));
 for(const who of [f.s,f.coach,f.n,f.other,f.outsider]){assert.equal((await who.req('training-videos/catalog')).status,403);assert.equal((await review(f,who,body(c))).status,403);assert.equal((await who.raw('training-videos/preview/'+c.media[0].id)).status,403);}
 f.store.run("UPDATE users SET role='admin' WHERE id=?",f.ids.outsider);const scoped=(await f.outsider.req('training-videos/catalog')).data;assert.equal(scoped.available,false);assert.deepEqual(scoped.exercises,[]);assert.equal((await review(f,f.outsider,body(c))).status,404);
 assert.equal((await f.a.raw('training-videos/preview/'+c.media[0].id,{Range:'bytes=0-3'})).status,206);assert.equal((await review(f,f.a,body(c,{confirmed:false}))).status,400);assert.equal((await review(f,f.a,body(c,{videoId:randomUUID()}))).status,400);assert.equal((await review(f,f.a,{...body(c),fixtureOnly:false})).status,400);
 const pending=await review(f,f.a,body(c));assert.equal(pending.status,200);assert.equal(pending.data.association.decision,'pending');assert.equal(pending.data.publicationChanged,false);
 const approvals=await Promise.all([review(f,f.a,body(c,{revision:1,decision:'approved'})),review(f,f.a,body(c,{revision:1,decision:'rejected'}))]);assert.deepEqual(approvals.map(r=>r.status).sort(),[200,409]);const a=(await catalog(f)).data.associations[0];assert.equal(a.revision,2);assert.equal(a.fixtureOnly,true);assert.equal(f.store.get("SELECT COUNT(*) AS n FROM audit WHERE event LIKE 'training.video.association.%'").n,2);
 await f.restart();assert.equal((await catalog(f)).data.associations[0].revision,2);assert.equal((await catalog(f)).data.associations[0].fixtureOnly,true);f.videoConfig.enabled=false;assert.equal((await catalog(f)).data.available,false);assert.equal((await review(f,f.a,body(c,{revision:2}))).status,503);assert.equal((await f.a.raw('training-videos/preview/'+c.media[0].id)).status,404);
 }finally{await f.close();}});
test('rejecting/keeping pending revokes published video immediately without rewriting plan; fixture cannot become real by changing flag',async()=>{const f=await persistentJourneyFixture();try{const p=await completePersistentJourney(f),c=(await catalog(f)).data,route='plans/'+p.train.id+'/videos/'+p.video.videoId,prior=f.store.get('SELECT content FROM plans WHERE id=?',p.train.id).content;
 assert.equal((await review(f,f.a,body(c,{decision:'rejected'}))).status,200);assert.equal((await f.s.raw(route)).status,404);assert.equal(f.store.get('SELECT content FROM plans WHERE id=?',p.train.id).content,prior);
 assert.equal((await review(f,f.a,body(c,{revision:1,decision:'approved'}))).status,200);assert.equal((await f.s.raw(route)).status,200);f.videoConfig.fixtureOnly=false;assert.equal((await catalog(f)).data.fixtureOnly,true);assert.equal((await catalog(f)).data.associations[0].fixtureOnly,true);
 f.trainingConfig.methodology.version='changed-catalog';assert.equal((await catalog(f)).data.associations[0].currentCatalog,false);assert.equal((await f.s.raw(route)).status,404);
 }finally{await f.close();}});
test('video admin UI uses existing IDs, defaults pending, private preview and explicit audited review through HTTP',async()=>{const f=await persistentJourneyFixture(),dom=new JSDOM('<main></main>'),doc=dom.window.document,saved=globalThis.FormData;globalThis.FormData=dom.window.FormData;const esc=s=>String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));let role='admin';const ui=trainingVideoAdminUI({getUser:()=>({role}),esc,perform:async work=>work(),api:async(route,b,m,k)=>{const r=await f.a.req(route,b,m,k);if(r.status>=400)throw Error(JSON.stringify(r));return r.data;}});try{
 await ui.load();doc.querySelector('main').innerHTML=ui.render();assert.match(doc.body.textContent,/CATÁLOGO FICTÍCIO/);let form=doc.querySelector('form');assert.equal(form.elements.decision.value,'pending');ui.click({target:form.querySelector('[data-video-preview]')});assert.match(doc.querySelector('video').getAttribute('src'),/^\/api\/local\/training-videos\/preview\//);
 form=doc.querySelector('form');form.elements.decision.value='approved';form.elements.note.value='Revisão fictícia explícita feita por administrador.';form.elements.confirmed.checked=true;await ui.submit({target:form,preventDefault(){}});await ui.load();doc.querySelector('main').innerHTML=ui.render();assert.match(doc.body.textContent,/approved/);assert.equal((await catalog(f)).data.associations[0].fixtureOnly,true);role='student';assert.equal(ui.render(),'');
 }finally{globalThis.FormData=saved;ui.reset();dom.window.close();await f.close();}});
