import test from 'node:test';
import assert from 'node:assert/strict';
import {JSDOM} from 'jsdom';
import {crmUI} from '../public/sim/crm-ui.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const start=Date.parse('2026-10-31T23:30:00-03:00'),caseState={started:true,startedAt:start,targetAt:start+48*3600000,promisedAt:start+72*3600000,status:'waiting',revision:1,onboardingRevision:2,reviewPending:true,responsibleId:null,note:'<script>synthetic</script>',pending:['Revisar respostas'],plans:{training:[],nutrition:[]}};
test('CRM UI confirms explicit completion, scoped updates, filters, escapes notes and resets private state',async()=>{const dom=new JSDOM('<main></main>'),originalForm=globalThis.FormData;globalThis.FormData=dom.window.FormData;let service={started:false,anamnesisComplete:true},user={id:'admin-id',name:'Admin',role:'admin'};const calls=[],student={id:'student-id',revision:2};const ui=crmUI({esc,getUser:()=>user,getStudent:()=>student,getProfessionals:()=>[{id:'coach-id',name:'Coach'}],perform:async f=>f(),api:async(path,body,method,key)=>{if(body){calls.push({path,body,method,key});return {};}if(path==='crm')return {entries:[{id:student.id,name:'Synthetic',email:'synthetic@fixture.invalid',coachId:'coach-id',nutritionId:null,internalNote:'Private note',service}],history:[]};return {service};}});
try{await ui.load();dom.window.document.querySelector('main').innerHTML=ui.render();let form=dom.window.document.querySelector('.service-complete');assert.ok(form);assert.match(dom.window.document.body.textContent,/3 dias/);await ui.submit({target:form,preventDefault(){}});assert.equal(calls.length,0);form.querySelector('input').checked=true;await ui.submit({target:form,preventDefault(){}});assert.deepEqual(calls[0].body,{revision:2,confirmed:true});assert.equal(calls[0].path,'students/student-id/onboarding/complete');service={...caseState};await ui.load();dom.window.document.querySelector('main').innerHTML=ui.render();assert.equal(dom.window.document.querySelector('script'),null);assert.match(dom.window.document.body.textContent,/03\/11\/2026/);form=dom.window.document.querySelector('.service-update');form.querySelector('[name=confirmed]').checked=true;form.querySelector('[name=status]').value='in_progress';form.querySelector('[name=responsibleId]').value='coach-id';form.querySelector('[name=reviewedOnboarding]').checked=true;await ui.submit({target:form,preventDefault(){}});assert.equal(calls[1].method,'PUT');assert.equal(calls[1].body.responsibleId,'coach-id');assert.equal(calls[1].body.reviewedOnboarding,true);assert.equal(calls[1].body.revision,1);const filter=dom.window.document.querySelector('[data-crm-filter]');filter.value='not_started';ui.input({target:filter});assert.equal(dom.window.document.querySelector('.crm-entry').hidden,true);ui.reset();assert.equal(ui.render(),'');user=null;assert.equal(ui.render(),'');}finally{globalThis.FormData=originalForm;dom.window.close();}});
test('student SLA UI shows the 72-hour promise without administrative fields or clinical details',async()=>{const ui=crmUI({esc,getUser:()=>({role:'student'}),getStudent:()=>({id:'own',revision:2}),getProfessionals:()=>[],perform:async f=>f(),api:async()=>({service:caseState})});await ui.load();const html=ui.render();assert.match(html,/72 horas corridas/);assert.ok(!html.includes('Meta interna'));assert.ok(!html.includes('Private note'));assert.ok(!html.includes('service-update'));assert.ok(!html.includes('crm-section'));assert.ok(!html.includes('script'));});
