import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {rmSync} from 'node:fs';
import {isolatedFixture,FIXTURE_PASSWORD} from './backend-fixtures.mjs';
import {createLocalServer} from '../backend/server.mjs';
import {executionDay,executionWeek} from '../backend/execution.mjs';
async function fixture(run){const f=await isolatedFixture();let clock=Date.parse('2026-10-05T15:00:00Z');const app=await createLocalServer({store:f.store,now:()=>clock,sessionMs:14*86400000,loginLimit:30});await new Promise(resolve=>app.server.listen(0,'127.0.0.1',resolve));const origin='http://127.0.0.1:'+app.server.address().port;
 const client=()=>{let cookie='';return {async request(path,body,method='POST',key=randomUUID()){const r=await fetch(origin+'/api/local/'+path,{method:body===undefined?'GET':method,headers:{Origin:origin,'Content-Type':'application/json','Idempotency-Key':key,Cookie:cookie},body:body===undefined?undefined:JSON.stringify(body)});if(r.headers.get('set-cookie'))cookie=r.headers.get('set-cookie').split(';')[0];return {status:r.status,data:await r.json()};},login(role){return this.request('login',{email:role.toLowerCase()+'@fixture.invalid',password:FIXTURE_PASSWORD});}};};
 try{await run({...f,client,advance:()=>{clock+=86400000;}});}finally{await app.close();rmSync(f.directory,{recursive:true,force:true,maxRetries:10,retryDelay:100});}}
async function publish(coach,studentId,daysPerWeek=2){let p=(await coach.request('students/'+studentId+'/plans',{title:'Synthetic execution',daysPerWeek,exercises:[{name:'Synthetic exercise',sets:2,reps:10}]})).data.plan;for(const action of ['submit','approve','publish'])p=(await coach.request('plans/'+p.id+'/'+action,{revision:p.revision})).data.plan;return p;}
test('execution dates are server-derived in Sao Paulo and week begins Monday',()=>{assert.equal(executionDay(Date.parse('2026-10-06T01:00:00Z')),'2026-10-05');assert.equal(executionWeek('2026-10-11'),'2026-10-05');assert.equal(executionWeek('2026-10-12'),'2026-10-12');});
test('persistent prescribed sets, no duplicate scoring, audit and exact access after reassignment',async()=>fixture(async f=>{
 const s=f.client(),c=f.client(),a=f.client(),n=f.client(),other=f.client(),outsider=f.client(),replacement=f.client();for(const [who,role] of [[s,'student'],[c,'coach'],[a,'admin'],[n,'nutrition'],[other,'otherStudent'],[outsider,'outsider'],[replacement,'otherCoach']])assert.equal((await who.login(role)).status,200);
 const plan=await publish(c,f.ids.studentRecord),route='workouts';assert.equal((await s.request('workouts/current')).data.workout,null);assert.equal((await a.request(route,{planId:plan.id})).status,403);assert.equal((await other.request(route,{planId:plan.id})).status,404);assert.equal((await s.request(route,{planId:plan.id,day:'2099-01-01'})).status,400);
 const draft=(await c.request('students/'+f.ids.studentRecord+'/plans',{title:'Not published',daysPerWeek:2,exercises:[{name:'Synthetic',sets:1,reps:10}]})).data.plan;assert.equal((await s.request(route,{planId:draft.id})).status,404);
 const key=randomUUID(),started=await s.request(route,{planId:plan.id},'POST',key);assert.equal(started.status,201);let w=started.data.workout;assert.equal(w.day,'2026-10-05');assert.deepEqual((await s.request(route,{planId:plan.id},'POST',key)).data,started.data);assert.equal((await s.request(route,{planId:plan.id})).data.workout.id,w.id);assert.equal(f.store.get('SELECT COUNT(*) AS n FROM workouts').n,1);const alternate=await publish(c,f.ids.studentRecord);assert.equal((await s.request(route,{planId:alternate.id})).status,409);
 for(const [who,code] of [[other,404],[outsider,404],[n,403],[c,200],[a,200]])assert.equal((await who.request('workouts/'+w.id)).status,code);
 const setPath='workouts/'+w.id+'/sets',base={exerciseIndex:0,setIndex:0,reps:10,load:20,completed:true,revision:w.revision};
 for(const change of [{exerciseIndex:1},{setIndex:2},{reps:11},{reps:0},{load:-1},{load:501},{load:null},{completed:'yes'},{day:w.day}])assert.equal((await s.request(setPath,{...base,...change},'PUT')).status,400);
 assert.equal((await c.request(setPath,base,'PUT')).status,403);assert.equal((await other.request(setPath,base,'PUT')).status,404);
 assert.equal((await c.request('ranking')).data.entries.length,0);assert.equal((await s.request('ranking/preferences',{enabled:true,alias:'Runner',revision:0},'PUT')).status,200);
 const firstKey=randomUUID(),first=await s.request(setPath,base,'PUT',firstKey);assert.equal(first.status,200);w=first.data.workout;assert.equal(w.completed,false);assert.equal((await s.request('ranking')).data.entries[0].consistency,0);assert.deepEqual((await s.request(setPath,base,'PUT',firstKey)).data,first.data);
 assert.equal((await s.request(setPath,{...base,revision:w.revision},'PUT')).data.changed,false);assert.equal(f.store.get('SELECT COUNT(*) AS n FROM workout_edits').n,1);
 const competing=await Promise.all([s.request(setPath,{...base,setIndex:1,revision:w.revision},'PUT'),s.request(setPath,{...base,setIndex:0,load:30,revision:w.revision},'PUT')]);assert.deepEqual(competing.map(r=>r.status).sort(),[200,409]);w=(await s.request('workouts/current')).data.workout;
 if(!w.completed)w=(await s.request(setPath,{...base,setIndex:1,revision:w.revision},'PUT')).data.workout;assert.equal(w.completed,true);assert.equal((await s.request('ranking')).data.entries[0].consistency,50);
 w=(await s.request(setPath,{...base,load:200,revision:w.revision},'PUT')).data.workout;assert.equal((await s.request('ranking')).data.entries[0].consistency,50);
 w=(await s.request(setPath,{...base,completed:false,revision:w.revision},'PUT')).data.workout;assert.equal((await s.request('ranking')).data.entries[0].consistency,0);w=(await s.request(setPath,{...base,revision:w.revision},'PUT')).data.workout;
 const rank=(await a.request('ranking')).data;assert.deepEqual(Object.keys(rank.entries[0]).sort(),['alias','consistency']);assert.ok(!JSON.stringify(rank).includes(f.ids.student));assert.ok(!JSON.stringify(rank).includes('@fixture.invalid'));assert.ok(!JSON.stringify(rank).includes('load'));assert.equal((await outsider.request('ranking')).data.entries.length,0);
 assert.ok((await c.request('workouts/'+w.id+'/history')).data.edits.length>=3);assert.equal((await n.request('workouts/'+w.id+'/history')).status,403);
 const row=(await a.request('students/'+f.ids.studentRecord)).data.student;assert.equal((await a.request('students/'+row.id+'/assignments',{coachId:f.ids.otherCoach,nutritionId:f.ids.nutrition,revision:row.revision},'PUT')).status,200);assert.equal((await c.request('workouts/'+w.id+'/history')).status,404);assert.equal((await replacement.request('workouts/'+w.id+'/history')).status,200);
 f.advance();assert.equal((await s.request(setPath,{...base,revision:w.revision},'PUT')).status,409);assert.equal((await s.request('workouts/current')).data.workout,null);w=(await s.request('workouts',{planId:plan.id})).data.workout;for(let i=0;i<2;i++)w=(await s.request('workouts/'+w.id+'/sets',{...base,setIndex:i,revision:w.revision},'PUT')).data.workout;assert.equal((await s.request('ranking')).data.entries[0].consistency,100);
 f.advance();w=(await s.request('workouts',{planId:plan.id})).data.workout;for(let i=0;i<2;i++)w=(await s.request('workouts/'+w.id+'/sets',{...base,setIndex:i,revision:w.revision},'PUT')).data.workout;assert.equal((await s.request('ranking')).data.entries[0].consistency,100);
 assert.equal((await s.request('ranking/preferences',{enabled:false,alias:'',revision:1},'PUT')).status,200);assert.equal((await a.request('ranking')).data.entries.length,0);assert.equal((await s.request('ranking/preferences')).data.preferences.alias,'');
}));
