import test from 'node:test';
import assert from 'node:assert/strict';
import {JSDOM} from 'jsdom';
import {rmSync} from 'node:fs';
import {isolatedFixture,FIXTURE_PASSWORD} from './backend-fixtures.mjs';
import {createLocalServer} from '../backend/server.mjs';
import {mountPersistent} from '../public/sim/persistent.js';
test('UI admin: cadastro confirmado, onboarding manual, treino publicado, reload, logout e onboarding do aluno',async()=>{
  const fixture=await isolatedFixture();const backend=await createLocalServer({store:fixture.store,loginLimit:20});await new Promise(resolve=>backend.server.listen(0,'127.0.0.1',resolve));const origin='http://127.0.0.1:'+backend.server.address().port;
  const dom=new JSDOM('<div id="local-app"></div><p id="local-status"></p>',{url:origin+'/local'});const originalFetch=globalThis.fetch,originalForm=globalThis.FormData;globalThis.FormData=dom.window.FormData;let cookie='';
  globalThis.fetch=async(url,options)=>{const response=await originalFetch(origin+url,{...options,headers:{...options.headers,...(options.body?{Origin:origin}:{}),...(cookie?{Cookie:cookie}:{})}});if(response.headers.get('set-cookie'))cookie=response.headers.get('set-cookie').split(';')[0];return response;};
  let unmount;const query=s=>{const node=dom.window.document.querySelector(s);assert.ok(node,s);return node;};const field=(s,v)=>{query(s).value=v;};const submit=id=>query('#'+id).dispatchEvent(new dom.window.Event('submit',{bubbles:true,cancelable:true}));
  const wait=async(predicate)=>{for(let i=0;i<100;i++){if(predicate())return;await new Promise(resolve=>setTimeout(resolve,10));}assert.fail('UI did not settle');};
  const login=async role=>{field('[name=email]',role+'@fixture.invalid');field('[name=password]',FIXTURE_PASSWORD);submit('login');await wait(()=>dom.window.document.querySelector('[data-action=logout]'));};
  try{
    unmount=await mountPersistent(dom.window.document);await login('admin');assert.ok(query('#supervision-section'));for(const width of [320,390]){dom.window.innerWidth=width;query('[data-view=supervision]').click();assert.equal(query('[data-panel=supervision]').hidden,false);dom.window.dispatchEvent(new dom.window.PopStateEvent('popstate'));assert.equal(query('[data-panel=supervision]').hidden,false);assert.ok(query('#supervision-section').textContent.includes('Supervisão /'));assert.ok(!query('#supervision-section').textContent.includes('NaN'));query('[data-view=students]').click();assert.equal(query('[data-panel=students]').hidden,false);}field('#create-student [name=name]','Cadastro UI Fictício');field('#create-student [name=email]','ui@fixture.invalid');field('#create-student [name=internalNote]','Nota interna UI');submit('create-student');assert.ok(query('#confirm-student'));assert.equal(fixture.store.get("SELECT COUNT(*) AS n FROM students WHERE email='ui@fixture.invalid'").n,0);query('#confirm-student').click();await wait(()=>fixture.store.get("SELECT COUNT(*) AS n FROM students WHERE email='ui@fixture.invalid'").n===1&&query('#local-status').textContent==='Operação concluída no servidor.');
    unmount();unmount=await mountPersistent(dom.window.document);assert.match(query('#local-app').textContent,/Cadastro UI Fictício/);assert.equal(dom.window.localStorage.length,0);
    assert.ok(!dom.window.document.querySelector('#authenticated-ai'));
    query('[data-student="'+fixture.ids.studentRecord+'"]').click();await wait(()=>dom.window.document.querySelector('#onboarding')&&query('#local-status').textContent==='Operação concluída no servidor.');
    field('#onboarding [name=context]','Registrado pelo admin fictício');submit('onboarding');
    await wait(()=>fixture.store.get('SELECT revision FROM students WHERE id=?',fixture.ids.studentRecord).revision===2&&query('#local-status').textContent==='Operação concluída no servidor.');
    field('#create-plan [name=title]','Treino admin UI');field('#create-plan [name=exercise]','Exemplo manual UI');submit('create-plan');
    await wait(()=>fixture.store.get("SELECT COUNT(*) AS n FROM plans WHERE title='Treino admin UI'").n===1&&query('#local-status').textContent==='Operação concluída no servidor.');
    for(const [action,expected] of [['submit','review'],['approve','approved'],['publish','published']]){
      query('[data-plan][data-action="'+action+'"]').click();
      await wait(()=>fixture.store.get("SELECT status FROM plans WHERE title='Treino admin UI'").status===expected&&query('#local-status').textContent==='Operação concluída no servidor.');
    }
    unmount();unmount=await mountPersistent(dom.window.document);assert.match(query('#local-app').textContent,/Publicado/);
    const originalPlan=fixture.store.get("SELECT * FROM plans WHERE title='Treino admin UI'");
    query('.manual-plan-version').closest('details').open=true;field('.manual-plan-version [name=title]','Treino admin UI versão 2');field('.manual-plan-version [name=instructions]','Orientações manuais editadas, sem geração automática.');field('.manual-plan-version [name=changeReason]','Ajuste manual revisado pelo administrador.');query('.manual-plan-version [name=confirmed]').checked=true;query('.manual-plan-version').dispatchEvent(new dom.window.Event('submit',{bubbles:true,cancelable:true}));
    await wait(()=>fixture.store.get("SELECT COUNT(*) AS n FROM plans WHERE title='Treino admin UI versão 2'").n===1&&query('#local-status').textContent==='Operação concluída no servidor.');assert.deepEqual(fixture.store.get('SELECT * FROM plans WHERE id=?',originalPlan.id),originalPlan);assert.equal(fixture.store.get("SELECT status FROM plans WHERE title='Treino admin UI versão 2'").status,'draft');assert.match(query('#local-app').textContent,/histórico preservado/);assert.ok(query('.manual-training-pdf input[type=file]'));

    query('[data-action=logout]').click();await wait(()=>dom.window.document.querySelector('#login'));await login('student');assert.ok(!query('#local-app').textContent.includes('INTERNO'));field('#onboarding [name=context]','Fictício: três dias na semana');submit('onboarding');await wait(()=>fixture.store.get('SELECT revision FROM students WHERE id=?',fixture.ids.studentRecord).revision===3&&query('#local-status').textContent==='Operação concluída no servidor.');
    unmount();unmount=await mountPersistent(dom.window.document);assert.equal(query('#onboarding [name=context]').value,'Fictício: três dias na semana');assert.equal(dom.window.localStorage.length,0);
  }finally{unmount?.();dom.window.close();globalThis.fetch=originalFetch;globalThis.FormData=originalForm;await backend.close();rmSync(fixture.directory,{recursive:true,force:true});}
});

test('UI convite manual: código fora da URL/storage, ativação e primeiro onboarding',async()=>{
 const f=await isolatedFixture(),backend=await createLocalServer({store:f.store,loginLimit:30});await new Promise(resolve=>backend.server.listen(0,'127.0.0.1',resolve));const origin='http://127.0.0.1:'+backend.server.address().port;
 const dom=new JSDOM('<div id="local-app"></div><p id="local-status"></p>',{url:origin+'/local'}),doc=dom.window.document;const originalFetch=globalThis.fetch,originalForm=globalThis.FormData;globalThis.FormData=dom.window.FormData;let cookie='',unmount;
 globalThis.fetch=async(url,options)=>{assert.ok(!url.includes('token'));const response=await originalFetch(origin+url,{...options,headers:{...options.headers,...(options.body?{Origin:origin}:{}),Cookie:cookie}});if(response.headers.get('set-cookie'))cookie=response.headers.get('set-cookie').split(';')[0];return response;};
 const query=s=>{const n=doc.querySelector(s);assert.ok(n,s);return n;},field=(s,v)=>{query(s).value=v;},submit=id=>query('#'+id).dispatchEvent(new dom.window.Event('submit',{bubbles:true,cancelable:true}));const wait=async fn=>{for(let i=0;i<200;i++){if(fn())return;await new Promise(r=>setTimeout(r,10));}assert.fail('UI did not settle');};
 try{
  unmount=await mountPersistent(doc);field('#login [name=email]','admin@fixture.invalid');field('#login [name=password]',FIXTURE_PASSWORD);submit('login');await wait(()=>doc.querySelector('#create-student'));
  field('#create-student [name=name]','Convite UI');field('#create-student [name=email]','inviteui@fixture.invalid');submit('create-student');query('#confirm-student').click();await wait(()=>query('#local-status').textContent==='Operação concluída no servidor.');const row=f.store.get("SELECT * FROM students WHERE email='inviteui@fixture.invalid'");query('[data-student="'+row.id+'"]').click();await wait(()=>query('#local-status').textContent==='Operação concluída no servidor.');query('#invite-student [name=verifiedDelivery]').checked=true;submit('invite-student');await wait(()=>doc.querySelector('#invite-code'));const token=query('#invite-code').value;assert.match(token,/^[A-Za-z0-9_-]{43}$/);assert.match(query('#local-app').textContent,/Nenhum e-mail foi enviado/);assert.equal(dom.window.localStorage.length,0);assert.equal(dom.window.location.search,'');assert.equal(dom.window.location.hash,'');
  query('[data-action=logout]').click();await wait(()=>doc.querySelector('#activate'));assert.ok(!doc.documentElement.innerHTML.includes(token));field('#activate [name=email]',row.email);field('#activate [name=token]',token);field('#activate [name=password]',FIXTURE_PASSWORD);submit('activate');await wait(()=>query('#local-status').textContent==='Operação concluída no servidor.');assert.ok(!doc.documentElement.innerHTML.includes(token));
  field('#login [name=email]',row.email);field('#login [name=password]',FIXTURE_PASSWORD);submit('login');await wait(()=>doc.querySelector('#onboarding'));assert.ok(!doc.querySelector('#invite-professional'));field('#onboarding [name=context]','Primeiro onboarding fictício');submit('onboarding');await wait(()=>JSON.parse(f.store.get('SELECT onboarding FROM students WHERE id=?',row.id).onboarding).context==='Primeiro onboarding fictício');
 }finally{unmount?.();dom.window.close();globalThis.fetch=originalFetch;globalThis.FormData=originalForm;await backend.close();rmSync(f.directory,{recursive:true,force:true});}
});

test('UI admin assigns and revokes professionals; reassigned coach sees student without admin controls',async()=>{
 const f=await isolatedFixture(),backend=await createLocalServer({store:f.store,loginLimit:30});await new Promise(resolve=>backend.server.listen(0,'127.0.0.1',resolve));const origin='http://127.0.0.1:'+backend.server.address().port;
 const dom=new JSDOM('<div id="local-app"></div><p id="local-status"></p>',{url:origin+'/local'}),doc=dom.window.document,originalFetch=globalThis.fetch,originalForm=globalThis.FormData;globalThis.FormData=dom.window.FormData;let cookie='',unmount;
 globalThis.fetch=async(url,options)=>{const r=await originalFetch(origin+url,{...options,headers:{...options.headers,...(options.body?{Origin:origin}:{}),Cookie:cookie}});if(r.headers.get('set-cookie'))cookie=r.headers.get('set-cookie').split(';')[0];return r;};
 const query=s=>{const n=doc.querySelector(s);assert.ok(n,s);return n;},field=(s,v)=>{query(s).value=v;},submit=id=>query('#'+id).dispatchEvent(new dom.window.Event('submit',{bubbles:true,cancelable:true}));const wait=async fn=>{for(let i=0;i<250;i++){if(fn())return;await new Promise(r=>setTimeout(r,10));}assert.fail('UI did not settle');};
 const login=async role=>{field('#login [name=email]',role+'@fixture.invalid');field('#login [name=password]',FIXTURE_PASSWORD);submit('login');await wait(()=>doc.querySelector('[data-action=logout]'));};
 try{
  unmount=await mountPersistent(doc);await login('admin');query('[data-student="'+f.ids.studentRecord+'"]').click();await wait(()=>query('#local-status').textContent==='Operação concluída no servidor.');
  assert.equal(query('#assign-professionals [name=coachId]').value,f.ids.coach);assert.ok(!query('#assign-professionals').innerHTML.includes(f.ids.outsider));field('#assign-professionals [name=coachId]',f.ids.otherCoach);field('#assign-professionals [name=nutritionId]','');submit('assign-professionals');assert.match(query('#local-status').textContent,/Confirme/);assert.equal(f.store.get('SELECT revision FROM students WHERE id=?',f.ids.studentRecord).revision,1);
  query('#assign-professionals [name=confirmed]').checked=true;submit('assign-professionals');await wait(()=>f.store.get('SELECT coach_id FROM students WHERE id=?',f.ids.studentRecord).coach_id===f.ids.otherCoach&&query('#local-status').textContent==='Operação concluída no servidor.');
  unmount();unmount=await mountPersistent(doc);query('[data-student="'+f.ids.studentRecord+'"]').click();await wait(()=>query('#local-status').textContent==='Operação concluída no servidor.');assert.equal(query('#assign-professionals [name=coachId]').value,f.ids.otherCoach);assert.equal(dom.window.localStorage.length,0);
  query('[data-action=logout]').click();await wait(()=>doc.querySelector('#login'));await login('othercoach');assert.ok(doc.querySelector('[data-student="'+f.ids.studentRecord+'"]'));assert.ok(!doc.querySelector('#assign-professionals'));
  query('[data-action=logout]').click();await wait(()=>doc.querySelector('#login'));await login('admin');query('[data-student="'+f.ids.studentRecord+'"]').click();await wait(()=>query('#local-status').textContent==='Operação concluída no servidor.');field('#assign-professionals [name=coachId]','');query('#assign-professionals [name=confirmed]').checked=true;submit('assign-professionals');await wait(()=>f.store.get('SELECT coach_id FROM students WHERE id=?',f.ids.studentRecord).coach_id===f.ids.admin&&query('#local-status').textContent==='Operação concluída no servidor.');
  query('[data-action=logout]').click();await wait(()=>doc.querySelector('#login'));await login('othercoach');assert.ok(!doc.querySelector('[data-student="'+f.ids.studentRecord+'"]'));assert.ok(!doc.querySelector('#assign-professionals'));
 }finally{unmount?.();dom.window.close();globalThis.fetch=originalFetch;globalThis.FormData=originalForm;await backend.close();rmSync(f.directory,{recursive:true,force:true});}
});

test('UI execution saves once on repeated click, resumes after reload/back and removes ranking on opt-out',async()=>{
 const f=await isolatedFixture(),backend=await createLocalServer({store:f.store,loginLimit:30});await new Promise(resolve=>backend.server.listen(0,'127.0.0.1',resolve));const origin='http://127.0.0.1:'+backend.server.address().port;
 const originalFetch=globalThis.fetch,originalForm=globalThis.FormData;let coachCookie='';
 const coach=async(path,body)=>{const r=await originalFetch(origin+'/api/local/'+path,{method:'POST',headers:{Origin:origin,'Content-Type':'application/json','Idempotency-Key':crypto.randomUUID(),Cookie:coachCookie},body:JSON.stringify(body)});if(r.headers.get('set-cookie'))coachCookie=r.headers.get('set-cookie').split(';')[0];assert.equal(r.status,path==='students/'+f.ids.studentRecord+'/plans'?201:200);return await r.json();};
 await coach('login',{email:'coach@fixture.invalid',password:FIXTURE_PASSWORD});let plan=(await coach('students/'+f.ids.studentRecord+'/plans',{title:'UI execution',daysPerWeek:2,exercises:[{name:'Synthetic UI exercise',sets:2,reps:10}]})).plan;for(const action of ['submit','approve','publish'])plan=(await coach('plans/'+plan.id+'/'+action,{revision:plan.revision})).plan;
 const dom=new JSDOM('<div id="local-app"></div><p id="local-status"></p>',{url:origin+'/local'}),doc=dom.window.document;globalThis.FormData=dom.window.FormData;let cookie='',unmount;
 globalThis.fetch=async(url,options)=>{const r=await originalFetch(origin+url,{...options,headers:{...options.headers,...(options.body?{Origin:origin}:{}),Cookie:cookie}});if(r.headers.get('set-cookie'))cookie=r.headers.get('set-cookie').split(';')[0];return r;};
 const query=s=>{const n=doc.querySelector(s);assert.ok(n,s);return n;},field=(s,v)=>{query(s).value=v;},submit=node=>node.dispatchEvent(new dom.window.Event('submit',{bubbles:true,cancelable:true}));const wait=async fn=>{for(let i=0;i<250;i++){if(fn())return;await new Promise(r=>setTimeout(r,10));}assert.fail('UI did not settle');};const settled=()=>query('#local-status').textContent==='Operação concluída no servidor.';
 try{unmount=await mountPersistent(doc);field('#login [name=email]','student@fixture.invalid');field('#login [name=password]',FIXTURE_PASSWORD);submit(query('#login'));await wait(()=>doc.querySelector('[data-start-workout]'));
  const start=query('[data-start-workout]');start.click();start.click();await wait(()=>doc.querySelector('.workout-set')&&settled());assert.equal(f.store.get('SELECT COUNT(*) AS n FROM workouts').n,1);
  let form=query('.workout-set[data-set="0"]');form.querySelector('[name=load]').value='20';form.querySelector('[name=completed]').checked=true;submit(form);submit(form);await wait(()=>f.store.get('SELECT COUNT(*) AS n FROM workout_edits').n===1&&settled());assert.equal(f.store.get('SELECT COUNT(*) AS n FROM workout_sets').n,1);
  unmount();unmount=await mountPersistent(doc);assert.equal(query('.workout-set[data-set="0"] [name=load]').value,'20');assert.equal(query('.workout-set[data-set="0"] [name=completed]').checked,true);assert.equal(query('.workout-set[data-set="1"] [name=completed]').checked,false);assert.equal(dom.window.localStorage.length,0);
  query('a[href="#training-section"]').click();await wait(()=>dom.window.location.hash==='#training-section');dom.window.history.back();await wait(()=>dom.window.location.hash==='#execution-section');assert.equal(query('.workout-set[data-set="0"] [name=load]').value,'20');assert.equal(f.store.get('SELECT COUNT(*) AS n FROM workout_sets').n,1);
  form=query('.workout-set[data-set="1"]');form.querySelector('[name=completed]').checked=true;submit(form);await wait(()=>f.store.get('SELECT completed FROM workouts').completed===1&&settled());assert.equal(query('#ranking-section').textContent.includes('Aluno fictício'),false);
  field('#ranking-preferences [name=alias]','UI participant');query('#ranking-preferences [name=enabled]').checked=true;submit(query('#ranking-preferences'));await wait(()=>query('#ranking-section').textContent.includes('UI participant')&&settled());assert.match(query('#ranking-section').textContent,/50%/);assert.ok(!query('#ranking-section').textContent.includes('20 kg'));
  form=query('.workout-set[data-set="0"]');form.querySelector('[name=load]').value='200';submit(form);await wait(()=>f.store.get('SELECT load FROM workout_sets WHERE set_index=0').load===200&&settled());assert.match(query('#ranking-section').textContent,/50%/);
  query('[data-action=ranking-opt-out]').click();await wait(()=>!query('#ranking-section').textContent.includes('UI participant')&&settled());assert.equal(f.store.get('SELECT enabled FROM ranking_preferences').enabled,0);assert.equal(dom.window.localStorage.length,0);
 }finally{unmount?.();dom.window.close();globalThis.fetch=originalFetch;globalThis.FormData=originalForm;await backend.close();rmSync(f.directory,{recursive:true,force:true});}
});

test('premium navigation separates roles, preserves draft fields, filters only accessible students and disables unavailable AI',async()=>{
 const f=await isolatedFixture(),backend=await createLocalServer({store:f.store,loginLimit:30});await new Promise(resolve=>backend.server.listen(0,'127.0.0.1',resolve));const origin='http://127.0.0.1:'+backend.server.address().port;
 const dom=new JSDOM('<div id="local-app"></div><p id="local-status" role="status"></p>',{url:origin+'/local'}),doc=dom.window.document,originalFetch=globalThis.fetch,originalForm=globalThis.FormData;globalThis.FormData=dom.window.FormData;let cookie='',unmount,calls=0;
 globalThis.fetch=async(url,options)=>{calls++;const response=await originalFetch(origin+url,{...options,headers:{...options.headers,...(options.body?{Origin:origin}:{}),...(cookie?{Cookie:cookie}:{})}});if(response.headers.get('set-cookie'))cookie=response.headers.get('set-cookie').split(';')[0];return response;};
 const query=s=>{const node=doc.querySelector(s);assert.ok(node,s);return node;},wait=async fn=>{for(let i=0;i<250;i++){if(fn())return;await new Promise(r=>setTimeout(r,10));}assert.fail('UI did not settle');},nav=key=>query('.premium-sidebar [data-view="'+key+'"]').click(),login=async role=>{query('#login [name=email]').value=role+'@fixture.invalid';query('#login [name=password]').value=FIXTURE_PASSWORD;query('#login').dispatchEvent(new dom.window.Event('submit',{bubbles:true,cancelable:true}));await wait(()=>doc.querySelector('.premium-shell')&&query('#local-status').textContent==='Operação concluída no servidor.');};
 try{
  unmount=await mountPersistent(doc);assert.ok(query('.activation'));await login('admin');assert.ok(query('.team-shell'));assert.equal(doc.querySelectorAll('[data-panel]:not([hidden])').length,1);assert.equal(query('[data-panel=home]').hidden,false);
  nav('students');assert.equal(query('[data-panel=students]').hidden,false);assert.equal(query('[data-panel=home]').hidden,true);assert.equal(query('#create-student').parentElement.tagName,'DETAILS');assert.equal(query('#create-student').parentElement.open,false);
  query('#create-student').parentElement.open=true;query('#create-student [name=name]').value='Unsaved synthetic draft';const before=calls;nav('training');nav('students');assert.equal(query('#create-student [name=name]').value,'Unsaved synthetic draft');assert.equal(calls,before);
  const search=query('#student-search');search.value='no accessible match';search.dispatchEvent(new dom.window.Event('input',{bubbles:true}));assert.equal([...doc.querySelectorAll('#students-section [data-student]')].filter(button=>!button.hidden).length,0);search.value='';search.dispatchEvent(new dom.window.Event('input',{bubbles:true}));assert.ok([...doc.querySelectorAll('#students-section [data-student]')].some(button=>!button.hidden));assert.ok(!doc.querySelector('#authenticated-ai'));assert.ok(query('#crm-section').textContent.includes('Atendimento / SLA'));assert.ok(query('#service-section'));
  query('[data-action=logout]').click();await wait(()=>doc.querySelector('#login'));await login('student');assert.ok(query('.student-shell'));assert.ok(!doc.querySelector('#create-student'));assert.ok(!doc.querySelector('#assign-professionals'));assert.ok(!doc.querySelector('.premium-sidebar [data-view=team]'));nav('profile');query('#onboarding [name=context]').value='Private draft';nav('ranking');nav('profile');assert.equal(query('#onboarding [name=context]').value,'Private draft');assert.equal(doc.querySelectorAll('[data-panel]:not([hidden])').length,1);assert.equal(query('.premium-sidebar [data-view=profile]').getAttribute('aria-current'),'page');dom.window.history.back();await wait(()=>!query('[data-panel=ranking]').hidden);nav('profile');assert.equal(query('#onboarding [name=context]').value,'Private draft');nav('history');assert.match(query('[data-panel=history]').textContent,/Ainda não há execuções salvas/);assert.equal(dom.window.localStorage.length,0);
  query('[data-action=logout]').click();await wait(()=>doc.querySelector('#login'));await login('nutrition');assert.ok(!doc.querySelector('.premium-sidebar [data-view=training]'));assert.ok(!doc.querySelector('#assign-professionals'));assert.ok(!doc.querySelector('#authenticated-ai'));assert.match(query('#ai-section').textContent,/perfis autorizados no chat/);
 }finally{unmount?.();dom.window.close();globalThis.fetch=originalFetch;globalThis.FormData=originalForm;await backend.close();rmSync(f.directory,{recursive:true,force:true});}
});
