import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {rmSync} from 'node:fs';
import {JSDOM} from 'jsdom';
import {isolatedFixture,FIXTURE_PASSWORD} from './backend-fixtures.mjs';
import {createLocalServer} from '../backend/server.mjs';
import {INTAKE_VERSION,CONSENT_VERSION} from '../public/sim/intake-fields.js';
import {fullIntakeAnswers} from './intake-test-fixtures.mjs';
import {supervisionUI} from '../public/sim/supervision-ui.js';
async function fixture(work){const f=await isolatedFixture(),app=await createLocalServer({store:f.store,loginLimit:50});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+app.server.address().port;const clients={};async function req(role,path,body,method='POST',key=randomUUID()){const res=await fetch(origin+'/api/local/'+path,{method:body===undefined?'GET':method,headers:{Origin:origin,'Content-Type':'application/json','Idempotency-Key':key,Cookie:clients[role]||''},body:body===undefined?undefined:JSON.stringify(body)});if(res.headers.get('set-cookie'))clients[role]=res.headers.get('set-cookie').split(';')[0];return {status:res.status,data:await res.json()};}try{for(const role of ['admin','student','coach','nutrition','outsider'])assert.equal((await req(role,'login',{email:role+'@fixture.invalid',password:FIXTURE_PASSWORD})).status,200);await work({...f,req});}finally{await app.close();rmSync(f.directory,{recursive:true,force:true});}}
const save=(revision,answers,training=true)=>({version:INTAKE_VERSION,revision,answers,consentVersion:CONSENT_VERSION,consents:{training,nutrition:false}});
test('admin supervision is tenant-bound, consent-versioned, audited and does not grant clinical roles',async()=>fixture(async f=>{
 const path='students/'+f.ids.studentRecord+'/supervision',intake='students/'+f.ids.studentRecord+'/anamnesis';
 for(const role of ['student','coach','nutrition','outsider'])assert.equal((await f.req(role,path)).status,403);
 const org=randomUUID(),other=randomUUID();f.store.run('INSERT INTO organizations VALUES (?,?)',org,'Synthetic foreign');f.store.run('INSERT INTO students(id,org_id,coach_id,email,name) VALUES (?,?,?,?,?)',other,org,f.ids.outsider,'foreign@fixture.invalid','Foreign sentinel');assert.equal((await f.req('admin','students/'+other+'/supervision')).status,404);
 let d=(await f.req('admin',path)).data.dashboard;assert.equal(d.execution.weeklyAdherencePercent,null);assert.equal(d.execution.lastRecordedDay,null);assert.equal(d.execution.nutritionAdherence,null);assert.equal(d.anamnesis.answers,undefined);
 const answers={...fullIntakeAnswers(),personal_context:'PRIVATE_SENTINEL'};const stale=save(0,answers);delete stale.consentVersion;assert.equal((await f.req('student',intake,stale,'PUT')).status,400);assert.equal((await f.req('student',intake,{...save(0,answers),consentVersion:'SIM_INTAKE_PURPOSES_V1'},'PUT')).status,409);assert.equal((await f.req('student',intake,save(0,answers),'PUT')).status,200);d=(await f.req('admin',path)).data.dashboard;assert.equal(d.anamnesis.answers.personal_context,'PRIVATE_SENTINEL');assert.equal(d.anamnesis.consentVersion,CONSENT_VERSION);
 assert.ok(f.store.all('SELECT event FROM audit').some(e=>e.event==='supervision.dashboard.read:anamnesis=1'));assert.ok(!JSON.stringify(f.store.all('SELECT * FROM audit')).includes('PRIVATE_SENTINEL'));
 f.store.run('UPDATE anamneses SET consent_version=? WHERE student_id=?','SIM_INTAKE_PURPOSES_V1',f.ids.studentRecord);assert.equal((await f.req('admin',path)).data.dashboard.anamnesis.answers,undefined);assert.equal((await f.req('admin',intake)).data.anamnesis.answers,undefined);
 assert.equal((await f.req('student',intake,save(1,{},false),'PUT')).status,200);assert.equal((await f.req('admin',path)).data.dashboard.anamnesis.answers,undefined);assert.equal((await f.req('student',intake)).data.anamnesis.answers.personal_context,'PRIVATE_SENTINEL');assert.equal(f.store.get('SELECT role FROM users WHERE id=?',f.ids.admin).role,'admin');
}));
test('real execution metrics, CAS notes and plan returns preserve signatures and published versions',async()=>fixture(async f=>{
 const path='students/'+f.ids.studentRecord+'/supervision',org=f.store.get('SELECT org_id FROM students WHERE id=?',f.ids.studentRecord).org_id,plan=randomUUID(),draft=randomUUID(),diet=randomUUID(),work=randomUUID();const content=JSON.stringify({daysPerWeek:3,exercises:[{name:'Synthetic squat',sets:3,reps:10}]});
 f.store.run("INSERT INTO plans(id,student_id,author_id,title,content,status,revision,approved_by,approved_revision,published_at) VALUES (?,?,?,?,?,'published',4,?,2,?)",plan,f.ids.studentRecord,f.ids.coach,'Synthetic published',content,f.ids.coach,Date.now());
 f.store.run("INSERT INTO plans(id,student_id,author_id,title,content,status,revision,approved_by,approved_revision) VALUES (?,?,?,?,?,'approved',3,?,2)",draft,f.ids.studentRecord,f.ids.coach,'Synthetic draft',content,f.ids.coach);
 f.store.run("INSERT INTO nutrition_plans(id,org_id,student_id,author_id,title,content,status,approved_by,approved_revision,revision,created_at) VALUES (?,?,?,?,?,?,'approved',?,2,3,?)",diet,org,f.ids.studentRecord,f.ids.nutrition,'Synthetic diet','{}',f.ids.nutrition,Date.now());
 const initial=(await f.req('admin',path)).data.dashboard;
 f.store.run('INSERT INTO workouts(id,org_id,student_id,plan_id,day,prescription,weekly_target,completed,updated_at) VALUES (?,?,?,?,?,?,?,?,?)',work,org,f.ids.studentRecord,plan,initial.execution.day,content,3,1,Date.now());f.store.run('INSERT INTO workout_sets VALUES (?,?,?,?,?,?)',work,0,0,10,25,1);
 let d=(await f.req('admin',path)).data.dashboard;assert.equal(d.execution.completedThisWeek,1);assert.equal(d.execution.weeklyAdherencePercent,33);assert.equal(d.execution.history[0].sets[0].load,25);assert.equal(d.plans.nutrition[0].approved_by,f.ids.nutrition);assert.equal(d.plans.nutrition[0].content,undefined);const intakePath='students/'+f.ids.studentRecord+'/anamnesis';assert.equal((await f.req('student',intakePath,{version:INTAKE_VERSION,revision:0,answers:fullIntakeAnswers(),consentVersion:CONSENT_VERSION,consents:{training:true,nutrition:true}},'PUT')).status,200);let authorized=(await f.req('admin',path)).data.dashboard;assert.deepEqual(authorized.plans.nutrition[0].content,{});assert.equal(authorized.plans.nutrition[0].clinicalDetailsRestricted,false);assert.equal((await f.req('student',intakePath,{version:INTAKE_VERSION,revision:1,answers:fullIntakeAnswers(),consentVersion:CONSENT_VERSION,consents:{training:true,nutrition:false}},'PUT')).status,200);assert.equal((await f.req('admin',path)).data.dashboard.plans.nutrition[0].content,undefined);
 const note={revision:d.student.revision,note:'Synthetic next steps',confirmed:true},key=randomUUID();assert.equal((await f.req('admin',path,note,'PUT',key)).status,200);assert.equal((await f.req('admin',path,note,'PUT',key)).status,200);assert.equal((await f.req('admin',path,note,'PUT')).status,409);
 for(const [kind,id] of [['training',draft],['nutrition',diet]]){const body={kind,planId:id,revision:3,reason:'Synthetic adjustment request',confirmed:true};assert.equal((await f.req('coach',path+'/return-plan',body)).status,403);assert.equal((await f.req('admin',path+'/return-plan',body)).status,200);assert.equal((await f.req('admin',path+'/return-plan',body)).status,409);const p=f.store.get('SELECT * FROM '+(kind==='training'?'plans':'nutrition_plans')+' WHERE id=?',id);assert.equal(p.status,'draft');assert.equal(p.approved_by,null);assert.equal(p.revision,4);assert.ok(f.store.get('SELECT internal_note FROM students WHERE id=?',f.ids.studentRecord).internal_note.includes('Synthetic next steps'));}
 assert.equal((await f.req('admin',path+'/return-plan',{kind:'training',planId:plan,revision:4,reason:'Synthetic change',confirmed:true})).status,409);assert.equal(f.store.get('SELECT status FROM plans WHERE id=?',plan).status,'published');
 assert.equal((await f.req('admin','students/'+f.ids.studentRecord+'/nutrition',{title:'Illegal',allergies:[],allergiesChecked:true,meals:[]})).status,403);assert.ok(!JSON.stringify(f.store.all('SELECT * FROM audit')).includes('Synthetic next steps'));
}));
test('supervision UI has honest empty states, escaped narratives and mobile-safe controls',async()=>{
 let role='admin',selected=null,dashboard;const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const ui=supervisionUI({api:async()=>({dashboard}),esc,perform:()=>{},getUser:()=>({id:'admin',role,name:'Bruno'}),getStudent:()=>selected,getProfessionals:()=>[]});await ui.load();assert.ok(ui.render().includes('Nenhum aluno disponível'));selected={id:'student'};dashboard={student:{name:'Synthetic',revision:1,internalNote:'<script>bad</script>'},anamnesis:{revision:1,status:'draft',consentVersion:CONSENT_VERSION,consents:{training:false,nutrition:false}},execution:{week:'2026-10-05',day:'2026-10-08',completedThisWeek:0,weeklyAdherencePercent:null,weeklyTarget:null,lastRecordedDay:null,history:[]},service:{started:false},plans:{training:[],nutrition:[]},activity:[]};await ui.load();const dom=new JSDOM(ui.render()),doc=dom.window.document;assert.equal(doc.querySelectorAll('script').length,0);assert.ok(doc.body.textContent.includes('Alimentação: aderência não medida'));assert.ok(doc.body.textContent.includes('Sem execução registrada'));assert.ok(doc.body.textContent.includes('Consentimentos anteriores não são ampliados'));assert.equal(doc.querySelector('textarea').maxLength,1000);assert.equal(doc.querySelector('input[name=confirmed]').required,true);for(const width of [320,390]){dom.window.innerWidth=width;assert.equal(doc.querySelector('textarea').value,'<script>bad</script>');assert.equal(doc.querySelectorAll('table').length,0);}dom.window.close();role='coach';await ui.load();assert.equal(ui.render(),'');
});
