import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {PGlite} from '@electric-sql/pglite';
import {postgresMigrations} from '../backend/postgres.mjs';
const script=readFileSync(new URL('../deploy/manual-migrate-007.sh',import.meta.url),'utf8');
const sql=script.split("<<'SHAPE_SQL'\n")[1].split('SHAPE_SQL\n')[0];
const files=postgresMigrations();
async function legacy(count=6){const db=new PGlite();await db.exec('CREATE ROLE sim_app NOSUPERUSER NOCREATEDB NOCREATEROLE;CREATE ROLE sim_migrator NOSUPERUSER NOCREATEDB NOCREATEROLE;CREATE SCHEMA sim AUTHORIZATION sim_migrator;GRANT USAGE ON SCHEMA sim TO sim_app;SET ROLE sim_migrator;SET search_path=sim,pg_catalog;CREATE TABLE schema_migrations(name TEXT PRIMARY KEY,checksum TEXT NOT NULL);');for(const f of files.slice(0,count)){await db.exec(f.sql);await db.query('INSERT INTO schema_migrations VALUES ($1,$2)',[f.name,f.checksum]);}await db.exec('GRANT SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA sim TO sim_app;REVOKE INSERT,UPDATE,DELETE ON schema_migrations FROM sim_app;RESET ROLE');return db;}
test('007 packet matches committed SQL and requires fresh restore proof and stopped tasks',()=>{const last=files.find(f=>f.name==='007-anamnesis.sql');assert.equal(last.name,'007-anamnesis.sql');assert.equal(createHash('sha256').update(last.sql).digest('hex'),'eb04ff987300bfa10b3557a2c714d4c193f77646913b014942d91f1373ed12ca');assert.ok(sql.includes(last.sql.trim()));assert.ok(sql.includes(last.checksum));assert.ok(script.includes('restore-verified.sha256'));assert.ok(script.includes('"$AGE" -le 3600'));assert.ok(script.includes('wait for Shape app tasks to stop'));const backup=readFileSync(new URL('../deploy/backup-verify-007.sh',import.meta.url),'utf8');assert.ok(backup.includes('--network none'));assert.ok(backup.includes('--no-owner --no-privileges --exit-on-error'));assert.ok(backup.includes('[ "$LIVE" = "$RESTORED" ]'));assert.ok(!backup.includes('docker pull'));});
test('007 packet is repeatable, preserves legacy answers and SLA, and grants only anamnesis DML',async()=>{const db=await legacy();try{await db.exec("SET ROLE sim_migrator;INSERT INTO organizations VALUES ('o','Synthetic organization');INSERT INTO users(id,org_id,email,name,role,password_hash) VALUES ('u','o','synthetic@example.test','Synthetic','student','not-a-login-hash');INSERT INTO students(id,org_id,user_id,coach_id,email,name,internal_note,onboarding) VALUES ('s','o','u','u','synthetic@example.test','Synthetic','Synthetic note','{\"goal\":\"Synthetic legacy\"}');INSERT INTO service_cases(student_id,org_id,started_at,target_at,promised_at,onboarding_revision,status,updated_at) VALUES ('s','o',100,172800100,259200100,1,'waiting',100);RESET ROLE;");const before=(await db.query('SELECT s.onboarding,c.* FROM students s JOIN service_cases c ON c.student_id=s.id')).rows;await db.exec(sql);await db.exec('RESET ROLE');await db.exec(sql);assert.equal((await db.query('SELECT COUNT(*)::integer n FROM schema_migrations')).rows[0].n,7);assert.deepEqual((await db.query('SELECT s.onboarding,c.* FROM students s JOIN service_cases c ON c.student_id=s.id')).rows,before);assert.equal((await db.query('SELECT COUNT(*)::integer n FROM anamneses')).rows[0].n,0);await assert.rejects(()=>db.exec('CREATE TABLE forbidden(id INTEGER)'));await db.exec('ROLLBACK');await assert.rejects(()=>db.exec('DELETE FROM schema_migrations'));await db.exec('ROLLBACK');assert.equal((await db.query("SELECT has_table_privilege(current_user,'sim.anamneses','SELECT,INSERT,UPDATE,DELETE') ok")).rows[0].ok,true);}finally{await db.close();}});
test('007 packet rejects incomplete/corrupt catalogs and rolls back partial DDL',async()=>{for(const mode of ['prefix5','corrupt','ddl-failure','catalog-write']){const db=await legacy(mode==='prefix5'?5:6);try{if(mode==='corrupt')await db.exec("SET ROLE sim_migrator;UPDATE schema_migrations SET checksum='invalid' WHERE name='006-service-sla.sql';RESET ROLE");if(mode==='catalog-write')await db.exec('SET ROLE sim_migrator;GRANT INSERT ON schema_migrations TO sim_app;RESET ROLE');const input=mode==='ddl-failure'?sql.replace('GRANT SELECT,INSERT,UPDATE,DELETE ON anamneses TO sim_app;',"DO $fail$ BEGIN RAISE EXCEPTION 'synthetic injected failure'; END $fail$;"):sql;await assert.rejects(()=>db.exec(input));await db.exec('ROLLBACK;RESET ROLE');assert.equal((await db.query("SELECT to_regclass('sim.anamneses') t")).rows[0].t,null);assert.equal((await db.query('SELECT COUNT(*)::integer n FROM schema_migrations')).rows[0].n,mode==='prefix5'?5:6);}finally{await db.close();}}});
