import {trainingPDFBytes} from './manual-training-fixtures.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import {rmSync} from 'node:fs';
import {randomUUID} from 'node:crypto';
import {isolatedFixture,FIXTURE_PASSWORD} from './backend-fixtures.mjs';
import {createLocalServer} from '../backend/server.mjs';
import {validateTrainingPDF} from '../backend/manual-training.mjs';
const pdf=trainingPDFBytes();
const upload={title:'Treino PDF privado',daysPerWeek:2,filename:'treino.pdf',mime:'application/pdf',base64:pdf.toString('base64'),confirmed:true};
async function setup(){const f=await isolatedFixture(),app=await createLocalServer({store:f.store,loginLimit:30});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+app.server.address().port;return {...f,app,client(){let cookie='';return {async request(route,body,method='POST',key=randomUUID()){const res=await fetch(origin+'/api/local/'+route,{method:body===undefined?'GET':method,headers:{Cookie:cookie,...(body===undefined?{}:{Origin:origin,'Content-Type':'application/json','Idempotency-Key':key})},body:body===undefined?undefined:JSON.stringify(body)});if(res.headers.get('set-cookie'))cookie=res.headers.get('set-cookie').split(';')[0];return {status:res.status,headers:res.headers,data:res.headers.get('content-type')?.startsWith('application/pdf')?Buffer.from(await res.arrayBuffer()):await res.json()};},login(role){return this.request('login',{email:role.toLowerCase()+'@fixture.invalid',password:FIXTURE_PASSWORD});}};},async close(){await app.close();rmSync(f.directory,{recursive:true,force:true,maxRetries:10,retryDelay:100});}};}
test('PDF rejects wrong MIME, content, size, encoded active dictionaries and encrypted/object-stream files',()=>{const deny=()=>{throw Error('rejected');};assert.equal(validateTrainingPDF(upload,deny).bytes,pdf.length);for(const change of [{base64:Buffer.from('%PDF-1.4\n/Type /Catalog\n/Type /Page\n%%EOF\n').toString('base64')},{mime:'text/html'},{filename:'treino.html'},{base64:Buffer.from('<html>bad</html>').toString('base64')},{base64:'A'.repeat(1500000)},...['JavaScript','J#53','OpenAction','Encrypt','ObjStm','EmbeddedFile'].map(name=>({base64:trainingPDFBytes('/'+name+' 1').toString('base64')}))])assert.throws(()=>validateTrainingPDF({...upload,...change},deny));});
test('private PDF is persisted in existing DB, only authorized published download, no file bytes in listings or execution',async()=>{const f=await setup();try{const admin=f.client(),student=f.client(),nutrition=f.client(),outsider=f.client();for(const [c,role] of [[admin,'admin'],[student,'student'],[nutrition,'nutrition'],[outsider,'outsider']])await c.login(role);const route='students/'+f.ids.studentRecord+'/training-pdf';for(const c of [student,nutrition])assert.equal((await c.request(route,upload)).status,403);assert.equal((await outsider.request(route,upload)).status,404);const key=randomUUID(),created=await admin.request(route,upload,'POST',key);assert.equal(created.status,201);assert.deepEqual((await admin.request(route,upload,'POST',key)).data,created.data);let p=created.data.plan;assert.ok(!JSON.stringify(p).includes(upload.base64));assert.equal((await student.request('plans/'+p.id+'/file')).status,404);assert.equal((await outsider.request('plans/'+p.id+'/file')).status,404);assert.equal((await nutrition.request('plans/'+p.id+'/file')).status,404);assert.deepEqual((await admin.request('plans/'+p.id+'/file')).data,pdf);for(const action of ['submit','approve','publish']){const r=await admin.request('plans/'+p.id+'/'+action,{revision:p.revision});assert.equal(r.status,200);p=r.data.plan;}const downloaded=await student.request('plans/'+p.id+'/file');assert.deepEqual(downloaded.data,pdf);assert.match(downloaded.headers.get('content-disposition'),/^attachment; filename="treino-[a-f0-9-]+\.pdf"$/);assert.match(downloaded.headers.get('content-security-policy'),/sandbox/);assert.equal((await student.request('workouts',{planId:p.id})).status,409);assert.ok(!JSON.stringify((await student.request('students/'+f.ids.studentRecord+'/plans')).data).includes(upload.base64));assert.equal(f.store.get('SELECT COUNT(*) AS n FROM schema_migrations').n,7);assert.ok(f.store.get('SELECT content FROM plans WHERE id=?',p.id).content.includes(upload.base64));}finally{await f.close();}});
test('admin manually manages student without coach; new published-plan version resets approval and preserves workout snapshot',async()=>{const f=await setup();try{const admin=f.client(),student=f.client(),outsider=f.client();await admin.login('admin');await student.login('student');await outsider.login('outsider');const created=await admin.request('students',{name:'Aluno piloto manual',email:'manual@fixture.invalid',internalNote:''});assert.equal(created.status,201);const exercises=[{name:'Exercício inicial',sets:2,reps:10}],draft={title:'Treino manual',daysPerWeek:2,exercises,instructions:'Descanso e esforço definidos pelo responsável.'};let p=(await admin.request('students/'+f.ids.studentRecord+'/plans',draft)).data.plan;for(const action of ['submit','approve','publish'])p=(await admin.request('plans/'+p.id+'/'+action,{revision:p.revision})).data.plan;const original=f.store.get('SELECT * FROM plans WHERE id=?',p.id),workout=await student.request('workouts',{planId:p.id});assert.equal(workout.status,201);const body={revision:p.revision,title:'Treino ajustado',daysPerWeek:2,exercises:[{name:'Exercício ajustado',sets:3,reps:8}],instructions:'Esforço, descanso, alternativa e cuidado com dor revisados.',changeReason:'Revisão humana após acompanhamento.',confirmed:true},route='plans/'+p.id+'/version';assert.equal((await student.request(route,body)).status,403);assert.equal((await outsider.request(route,body)).status,404);assert.equal((await admin.request(route,{...body,revision:1})).status,409);const key=randomUUID(),r=await admin.request(route,body,'POST',key);assert.equal(r.status,201);assert.deepEqual((await admin.request(route,body,'POST',key)).data,r.data);let v=r.data.plan;assert.equal(v.status,'draft');const saved=f.store.get('SELECT * FROM plans WHERE id=?',v.id);assert.equal(saved.approved_by,null);assert.equal(saved.approved_revision,null);assert.deepEqual(f.store.get('SELECT * FROM plans WHERE id=?',p.id),original);assert.equal((await admin.request('plans/'+v.id+'/publish',{revision:v.revision})).status,409);assert.equal((await student.request('students/'+f.ids.studentRecord+'/plans')).data.plans.length,1);for(const action of ['submit','approve','publish']){const r=await admin.request('plans/'+v.id+'/'+action,{revision:v.revision});assert.equal(r.status,200);v=r.data.plan;}const oldWorkout=(await student.request('workouts/current')).data.workout;assert.equal(oldWorkout.planId,p.id);assert.deepEqual(oldWorkout.prescription.exercises,exercises);assert.equal((await student.request('students/'+f.ids.studentRecord+'/plans')).data.plans.length,2);let own=(await admin.request('students/'+created.data.student.id+'/plans',draft)).data.plan;for(const action of ['submit','approve','publish']){const r=await admin.request('plans/'+own.id+'/'+action,{revision:own.revision});assert.equal(r.status,200);own=r.data.plan;}}finally{await f.close();}});
