import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {sessionsFixture,fixtureSessionPayload,fixtureResponse} from './training-sessions-fixtures.mjs';
import {responsesProposalAdapter,trainingProposalSchema,validateSchema,PROPOSAL_MAX_OUTPUT_TOKENS} from '../backend/proposal-responses.mjs';
const clone=v=>structuredClone(v);

test('mock Responses integrates reviewed intake to complete sessions, provenance, confirmation, publication and immutable edited version',async()=>{
 let request;const f=await sessionsFixture({fetchImpl:async(url,options)=>{request={url,options};const input=JSON.parse(JSON.parse(options.body).input);return fixtureResponse(fixtureSessionPayload(input));}});try{
  await f.consent();const prepared=await f.prepare();assert.equal(prepared.status,200);assert.equal(prepared.data.externalCalls,false);assert.equal(prepared.data.writesPerformed,false);const p=prepared.data.proposal;assert.equal(p.payload.sessions.length,p.payload.daysPerWeek);assert.equal(p.payload.exercises,undefined);assert.ok(p.methodHash);assert.ok(p.catalogHash);assert.equal(p.sources[0].id,'fixture-source');assert.equal(f.store.get('SELECT COUNT(*) AS n FROM plans').n,0);
  assert.equal(request.url,'https://api.openai.com/v1/responses');const body=JSON.parse(request.options.body);assert.equal(body.store,false);assert.equal(body.max_output_tokens,PROPOSAL_MAX_OUTPUT_TOKENS);assert.equal(body.text.format.strict,true);assert.ok(body.text.format.schema.properties.sessions);for(const text of ['@fixture.invalid','full_name','whatsapp','letter','internal_note','studentId'])assert.ok(!body.input.includes(text));assert.ok(!JSON.stringify(f.store.all('SELECT * FROM operations')).includes('fixture-only-not-a-real-api-key'));
  const key=randomUUID(),saved=await f.confirm(p,p.payload,key);assert.equal(saved.status,201);let plan=saved.data.plan;assert.deepEqual((await f.confirm(p,p.payload,key)).data,saved.data);assert.equal(plan.content.sessions.length,3);assert.equal(plan.content.exercises.length,3);assert.equal(plan.content.sessions[0].exercises[0].reference.sourceSha256,p.sources[0].sha256);assert.equal(plan.content.sessions[0].exercises[0].alternatives[0].reference.section,'fixture-section');assert.equal(plan.content.proposalSource.reservationId,p.reservationId);
  for(const action of ['submit','approve','publish']){const r=await f.coach.req('plans/'+plan.id+'/'+action,{revision:plan.revision});assert.equal(r.status,200);plan=r.data.plan;}
  const original=clone(f.store.get('SELECT * FROM plans WHERE id=?',plan.id));assert.equal((await f.student.req('workouts',{planId:plan.id})).status,400);const sessionId=plan.content.sessions[1].id,started=await f.student.req('workouts',{planId:plan.id,sessionId});assert.equal(started.status,201);assert.equal(started.data.workout.prescription.sessionId,sessionId);assert.equal(started.data.workout.prescription.exercises.length,1);const workout=clone(f.store.get('SELECT * FROM workouts WHERE id=?',started.data.workout.id));assert.equal((await f.student.req('workouts',{planId:plan.id,sessionId:plan.content.sessions[0].id})).status,409);
  const updated=clone(p.payload);updated.title='Nova versão fictícia';updated.sessions[1].exercises[0].sets=3;const editKey=randomUUID(),edited=await f.coach.req('training-proposals/plans/'+plan.id,{revision:plan.revision,payload:updated,confirmed:true,changeReason:'Ajuste fictício explicitamente conferido.'},'PUT',editKey);assert.equal(edited.status,201);assert.notEqual(edited.data.plan.id,plan.id);assert.equal(edited.data.plan.status,'draft');assert.equal(edited.data.plan.content.previousVersion.id,plan.id);assert.deepEqual({...f.store.get('SELECT * FROM plans WHERE id=?',plan.id)},original);assert.deepEqual({...f.store.get('SELECT * FROM workouts WHERE id=?',workout.id)},workout);assert.equal(f.store.get('SELECT approved_by FROM plans WHERE id=?',edited.data.plan.id).approved_by,null);assert.equal(f.store.get('SELECT COUNT(*) AS n FROM ai_monthly_reservations').n,1);assert.equal(f.store.get('SELECT COUNT(*) AS n FROM schema_migrations').n,7);
 }finally{await f.close();}
});

test('complete session and alternative validation refuses flat payloads, frequencies, duplicate days, invented evidence and unreviewed alternatives; TTL retains ledger',async()=>{let now=Date.now();const f=await sessionsFixture({now:()=>now});try{await f.consent();const p=(await f.prepare()).data.proposal;const invalids=[v=>{delete v.sessions;v.exercises=[];},v=>{v.sessions.pop();},v=>{v.daysPerWeek=7;},v=>{v.sessions[1].weekday=v.sessions[0].weekday;},v=>{v.sessions[0].id=v.sessions[1].id;},v=>{v.sessions[0].exercises[0].alternatives[0].exerciseId='unknown';},v=>{v.sessions[0].exercises[0].alternatives[0].exerciseId=v.sessions[0].exercises[0].exerciseId;},v=>{v.sessions[0].exercises[0].evidence=['full_name'];},v=>{v.sessions[0].exercises[0].ruleId='invented';},v=>{v.sessions[0].exercises[0].alternatives[0].diagnosis='fabricated';}];for(const mutate of invalids){const value=clone(p.payload);mutate(value);assert.equal((await f.confirm(p,value)).status,400);}assert.equal(f.store.get('SELECT COUNT(*) AS n FROM plans').n,0);now+=21*60000;assert.equal((await f.confirm(p)).status,409);assert.equal(f.store.get('SELECT COUNT(*) AS n FROM ai_monthly_reservations').n,1);}finally{await f.close();}});

test('attention resolution is required and withdrawal during provider work blocks result without refund',async()=>{let release,begin;const started=new Promise(r=>{begin=r;});const f=await sessionsFixture({fetchImpl:async(_url,options)=>{begin();await new Promise(r=>{release=r;});return fixtureResponse(fixtureSessionPayload(JSON.parse(JSON.parse(options.body).input)));}});try{f.store.run('UPDATE anamneses SET attention_review=1 WHERE student_id=?',f.ids.studentRecord);await f.consent();assert.equal((await f.prepare()).status,409);assert.equal(f.store.get('SELECT COUNT(*) AS n FROM ai_monthly_reservations').n,0);const decision={sequence:0,anamnesisRevision:1,decision:'allow-with-limitations',note:'Decisão fictícia conferida, sem diagnóstico clínico.',confirmed:true};assert.equal((await f.admin.req(f.base+'/training-risk',decision,'PUT')).status,403);assert.equal((await f.coach.req(f.base+'/training-risk',decision,'PUT')).status,200);const pending=f.prepare();await started;await f.consent(false);release();assert.equal((await pending).status,409);assert.equal(f.store.get('SELECT COUNT(*) AS n FROM plans').n,0);assert.equal(f.store.get('SELECT COUNT(*) AS n FROM ai_monthly_reservations').n,1);}finally{release?.();await f.close();}});

test('timeout aborts mock transport and reserves full output cap; idempotency and exhausted budget never retry or refund',async()=>{let calls=0,aborted=false;const f=await sessionsFixture({timeoutMs:25,fetchImpl:async(_url,options)=>{calls++;return new Promise((_,reject)=>options.signal.addEventListener('abort',()=>{aborted=true;reject(Error('Private diagnostics'));},{once:true}));}});try{await f.consent();const key=randomUUID(),r=await f.prepare(key);assert.equal(r.status,502);assert.equal(aborted,true);assert.ok(!JSON.stringify(r.data).includes('Private'));assert.equal((await f.prepare(key)).status,409);assert.equal(calls,1);const reservation=f.store.get('SELECT * FROM ai_monthly_reservations');assert.ok(reservation.amount_micros>=2000);const operation=f.store.all('SELECT result FROM operations').map(x=>JSON.parse(x.result)).find(x=>x.maxOutputTokens);assert.equal(operation.maxOutputTokens,4000);assert.ok(operation.inputTokenUpperBound>2048);assert.equal(f.store.get('SELECT COUNT(*) AS n FROM plans').n,0);}finally{await f.close();}const blocked=await sessionsFixture({budget:{globalMonthlyUSD:.000001,adminMonthlyUSD:.000001},fetchImpl:async()=>assert.fail('Provider must not run')});try{await blocked.consent();assert.equal((await blocked.prepare()).status,503);assert.equal(blocked.store.get('SELECT COUNT(*) AS n FROM ai_monthly_reservations').n,0);}finally{await blocked.close();}});

test('real provider, pending methodology, non-fixture catalog and other organization remain closed',async()=>{const f=await sessionsFixture();try{await f.consent();const method=f.config.methodology;method.status='pending-bruno-validation';assert.equal((await f.prepare()).status,503);method.status='synthetic-fixture';method.fixtureOnly=false;assert.equal((await f.prepare()).status,503);method.fixtureOnly=true;method.orgId=randomUUID();assert.equal((await f.prepare()).status,403);method.orgId=f.store.get('SELECT org_id FROM students WHERE id=?',f.ids.studentRecord).org_id;f.config.provider=responsesProposalAdapter({apiKey:'fixture-only-no-real-key',model:'fixture-responses-model',fetchImpl:async()=>assert.fail('No real transport')});assert.equal((await f.prepare()).status,503);}finally{await f.close();}assert.throws(()=>responsesProposalAdapter({apiKey:'fixture-only',model:'fixture',mockOnly:true}),/Mock transport required/);});

test('Responses strict schema rejects incomplete/error/extra output, excessive usage and oversized body',async()=>{const fakeInput={kind:'training',untrustedFacts:{days:1,environment:['test']},untrustedMethod:{exercises:[{id:'fixture-a',environments:['test'],allowedAlternativeIds:['fixture-b']}]}};const payload=fixtureSessionPayload(fakeInput);validateSchema(payload,trainingProposalSchema);for(const response of [()=>new Response('{}'),()=>new Response('x'.repeat(65537)),()=>new Response(JSON.stringify({status:'completed',usage:{output_tokens:4001},output:[{type:'message',role:'assistant',status:'completed',content:[{type:'output_text',text:JSON.stringify(payload)}]}]})),()=>fixtureResponse({...payload,unexpected:'rejected'}),()=>new Response('private',{status:500})]){const adapter=responsesProposalAdapter({apiKey:'fixture-only',model:'fixture-model',mockOnly:true,fetchImpl:async()=>response()});await assert.rejects(()=>adapter.generate(fakeInput));}});
