-- DRAFT for explicit local tests only. NOT a numbered/runtime migration.
-- Promotion to a reviewed additive migration and least-privilege grants is pending.
CREATE TABLE commerce_buyers(id TEXT PRIMARY KEY,org_id TEXT NOT NULL REFERENCES organizations(id),user_id TEXT REFERENCES users(id),customer_id TEXT NOT NULL,environment TEXT NOT NULL,account_id TEXT NOT NULL,identity_verified_at BIGINT,active INTEGER NOT NULL DEFAULT 1 CHECK(active IN (0,1)),UNIQUE(id,org_id),UNIQUE(environment,account_id,customer_id));
CREATE TABLE commerce_orders(id TEXT PRIMARY KEY,org_id TEXT NOT NULL REFERENCES organizations(id),buyer_id TEXT NOT NULL,environment TEXT NOT NULL,account_id TEXT NOT NULL,customer_id TEXT NOT NULL,idempotency_key TEXT NOT NULL,request_hash TEXT NOT NULL,external_reference TEXT NOT NULL UNIQUE,amount_cents BIGINT NOT NULL CHECK(amount_cents>0),currency TEXT NOT NULL CHECK(currency='BRL'),snapshot TEXT NOT NULL,billing_type TEXT NOT NULL CHECK(billing_type IN ('PIX','CREDIT_CARD')),max_installments INTEGER,checkout_id TEXT,checkout_state TEXT NOT NULL CHECK(checkout_state IN ('new','creating','unknown','ready')),status TEXT NOT NULL CHECK(status IN ('pending','paid','overdue','canceled','expired','refund_pending','partially_refunded','refunded','chargeback','review')),adverse_seen INTEGER NOT NULL DEFAULT 0 CHECK(adverse_seen IN (0,1)),revision INTEGER NOT NULL DEFAULT 1,created_at BIGINT NOT NULL,updated_at BIGINT NOT NULL,FOREIGN KEY(buyer_id,org_id) REFERENCES commerce_buyers(id,org_id),UNIQUE(buyer_id,idempotency_key),UNIQUE(environment,account_id,checkout_id),UNIQUE(id,org_id),UNIQUE(id,org_id,buyer_id),UNIQUE(id,environment,account_id));
CREATE TABLE commerce_events(environment TEXT NOT NULL,account_id TEXT NOT NULL,event_id TEXT NOT NULL,event_type TEXT NOT NULL,checkout_id TEXT,payment_id TEXT,external_reference TEXT,customer_id TEXT,state TEXT NOT NULL CHECK(state IN ('pending','processing','done','review')),lease_until BIGINT,received_at BIGINT NOT NULL,attempts INTEGER NOT NULL DEFAULT 0,PRIMARY KEY(environment,account_id,event_id));
CREATE TABLE commerce_entitlements(order_id TEXT PRIMARY KEY,buyer_id TEXT NOT NULL,org_id TEXT NOT NULL,source TEXT NOT NULL CHECK(source='payment'),onboarding_authorized INTEGER NOT NULL CHECK(onboarding_authorized IN (0,1)),period_state TEXT NOT NULL CHECK(period_state='policy-pending'),created_at BIGINT NOT NULL,FOREIGN KEY(order_id,org_id,buyer_id) REFERENCES commerce_orders(id,org_id,buyer_id));
CREATE TABLE commerce_tasks(id TEXT PRIMARY KEY,order_id TEXT NOT NULL,org_id TEXT NOT NULL,kind TEXT NOT NULL CHECK(kind IN ('verify-identity','onboarding','financial-review')),state TEXT NOT NULL CHECK(state IN ('pending','done')),created_at BIGINT NOT NULL,UNIQUE(order_id,kind),FOREIGN KEY(order_id,org_id) REFERENCES commerce_orders(id,org_id));
CREATE TABLE commerce_interest(id TEXT PRIMARY KEY,buyer_id TEXT NOT NULL,org_id TEXT NOT NULL,sku TEXT NOT NULL CHECK(sku IN ('annual','specific-project')),created_at BIGINT NOT NULL,UNIQUE(buyer_id,sku),FOREIGN KEY(buyer_id,org_id) REFERENCES commerce_buyers(id,org_id));
CREATE TABLE commerce_audit(id TEXT PRIMARY KEY,order_id TEXT NOT NULL,org_id TEXT NOT NULL,event TEXT NOT NULL,created_at BIGINT NOT NULL,FOREIGN KEY(order_id,org_id) REFERENCES commerce_orders(id,org_id));
CREATE TABLE commerce_payments(environment TEXT NOT NULL,account_id TEXT NOT NULL,payment_id TEXT NOT NULL,order_id TEXT NOT NULL,PRIMARY KEY(environment,account_id,payment_id),FOREIGN KEY(order_id,environment,account_id) REFERENCES commerce_orders(id,environment,account_id));
CREATE INDEX commerce_pending_events ON commerce_events(environment,account_id,state,received_at);

-- Additive local fixture migration. NOT loaded by normal SQLite/PG startup.
CREATE UNIQUE INDEX commerce_students_tenant_key ON students(id,org_id);
CREATE TABLE commerce_registrations(buyer_id TEXT PRIMARY KEY,org_id TEXT NOT NULL,email TEXT NOT NULL UNIQUE,name TEXT NOT NULL,student_id TEXT UNIQUE REFERENCES students(id),FOREIGN KEY(buyer_id,org_id) REFERENCES commerce_buyers(id,org_id));
CREATE TABLE commerce_student_sources(student_id TEXT PRIMARY KEY,org_id TEXT NOT NULL,buyer_id TEXT NOT NULL UNIQUE,FOREIGN KEY(student_id,org_id) REFERENCES students(id,org_id),FOREIGN KEY(buyer_id,org_id) REFERENCES commerce_buyers(id,org_id));
CREATE TABLE commerce_buyer_sessions(token_hash TEXT PRIMARY KEY,buyer_id TEXT NOT NULL REFERENCES commerce_buyers(id),expires_at BIGINT NOT NULL);
CREATE TABLE commerce_outbox(id TEXT PRIMARY KEY,buyer_id TEXT NOT NULL,org_id TEXT NOT NULL,dedupe_key TEXT NOT NULL,kind TEXT NOT NULL CHECK(kind IN ('verify-identity','onboarding','financial-review','paid','interest')),state TEXT NOT NULL CHECK(state IN ('pending','previewed','confirmed')),created_at BIGINT NOT NULL,UNIQUE(buyer_id,dedupe_key),FOREIGN KEY(buyer_id,org_id) REFERENCES commerce_buyers(id,org_id));
CREATE TABLE commerce_identity_proofs(token_hash TEXT PRIMARY KEY,buyer_id TEXT NOT NULL REFERENCES commerce_buyers(id),outbox_id TEXT NOT NULL REFERENCES commerce_outbox(id),expires_at BIGINT NOT NULL,consumed_at BIGINT,created_at BIGINT NOT NULL);
-- Provider stand-in persists minimal FICTITIOUS records, never cards or tokens.
CREATE TABLE commerce_mock_checkouts(order_id TEXT PRIMARY KEY REFERENCES commerce_orders(id),checkout_id TEXT NOT NULL UNIQUE,payments TEXT NOT NULL);
CREATE TABLE commerce_fixture_scenarios(order_id TEXT PRIMARY KEY REFERENCES commerce_orders(id),scenario TEXT NOT NULL);
CREATE INDEX commerce_identity_expiry ON commerce_identity_proofs(buyer_id,expires_at);
CREATE INDEX commerce_outbox_pending ON commerce_outbox(org_id,state,created_at);
