export type Exercise={name:string;sets:string;reps:string;rest:string};
export type Workout={id:string;title:string;focus:string;duration:number;exercises:Exercise[]};
export type Measurement={date:string;weight:number;waist:number};
export type Student={id:string;name:string;email:string;goal:string;joinedAt:string;submittedAt:string|null;anamnese:Record<string,string>;planApproved:boolean;demoReleased?:boolean;plan:Workout[];measurements:Measurement[];checkins:{date:string;workout:string}[];active:boolean};
export type Post={id:string;author:string;text:string;image:string;date:string;likes:string[];comments:{id:string;author:string;text:string}[]};
export type State={students:Student[];currentStudentId:string;posts:Post[]};
export type Action={type:string;role?:string;studentId?:string;[key:string]:unknown};
export const dateKey=(date=new Date())=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit'}).format(date);
export function deadlines(submittedAt:string){const start=new Date(submittedAt);const ready=new Date(start.getTime()+48*60*60*1000);const due=new Date(start);let days=0;while(days<3){due.setUTCDate(due.getUTCDate()+1);const day=new Date(due.toLocaleString('en-US',{timeZone:'America/Sao_Paulo'})).getDay();if(day!==0&&day!==6)days++;}return {readyAt:ready.toISOString(),deadlineAt:due.toISOString()};}
export function planStatus(s:{submittedAt:string|null;planApproved:boolean;demoReleased?:boolean},now=new Date()){if(!s.submittedAt)return 'assessment';if(s.planApproved&&(s.demoReleased||now.getTime()>=new Date(deadlines(s.submittedAt).readyAt).getTime()))return 'ready';return 'pending';}
export const defaultPlan:Workout[]=[
{id:'a',title:'Inferiores & glúteos',focus:'Pernas · Glúteos · Core',duration:50,exercises:[{name:'Agachamento livre',sets:'3',reps:'12',rest:'60 s'},{name:'Leg press 45°',sets:'3',reps:'12',rest:'60 s'},{name:'Cadeira extensora',sets:'3',reps:'15',rest:'45 s'},{name:'Mesa flexora',sets:'3',reps:'12',rest:'60 s'},{name:'Elevação pélvica',sets:'3',reps:'12',rest:'60 s'},{name:'Prancha abdominal',sets:'3',reps:'30 s',rest:'45 s'}]},
{id:'b',title:'Superiores & core',focus:'Costas · Peito · Braços',duration:45,exercises:[{name:'Puxada frontal',sets:'3',reps:'12',rest:'60 s'},{name:'Remada baixa',sets:'3',reps:'12',rest:'60 s'},{name:'Supino com halteres',sets:'3',reps:'12',rest:'60 s'},{name:'Desenvolvimento',sets:'3',reps:'12',rest:'60 s'},{name:'Rosca alternada',sets:'3',reps:'12',rest:'45 s'}]},
{id:'c',title:'Full body',focus:'Corpo todo · Condicionamento',duration:40,exercises:[{name:'Agachamento goblet',sets:'3',reps:'12',rest:'60 s'},{name:'Remada unilateral',sets:'3',reps:'12',rest:'60 s'},{name:'Flexão de braços',sets:'3',reps:'10',rest:'60 s'},{name:'Abdominal',sets:'3',reps:'15',rest:'45 s'}]}];
const ago=(days:number)=>new Date(Date.now()-days*86400000).toISOString();
export function createState():State{
const names=[['marina','Marina Duarte','Hipertrofia'],['lucas','Lucas Costa','Condicionamento'],['gabriela','Gabriela Santos','Emagrecimento'],['pedro','Pedro Almeida','Hipertrofia'],['juliana','Juliana Lima','Qualidade de vida'],['bruno','Bruno Oliveira','Condicionamento']];
const students:Student[]=names.map(([id,name,goal],i)=>({id,name,email:id+'@exemplo.com',goal,joinedAt:ago(60-i*5),submittedAt:ago(i===4?1:45),anamnese:{age:'28',height:'168',weight:String(68+i*3),goal,experience:'Intermediário',days:'5',restrictions:'Nenhuma informada'},planApproved:i!==4,plan:i===4?[]:structuredClone(defaultPlan),active:true,measurements:Array.from({length:i===4?1:6},(_,w)=>({date:dateKey(new Date(ago((5-w)*7))),weight:Math.round((70+i*3-w*.55)*10)/10,waist:Math.round((80+i*2-w*.6)*10)/10})),checkins:Array.from({length:i===4?0:18+i*2},(_,n)=>({date:dateKey(new Date(ago(n+1))),workout:['a','b','c'][n%3]}))}));
return {students,currentStudentId:'marina',posts:[{id:'welcome',author:'personal',text:'Bem-vindos ao time! Lembrem-se: consistência vale mais que perfeição. Compartilhem suas conquistas por aqui — cada passo merece ser celebrado. 💪',image:'',date:ago(1),likes:['marina','lucas','pedro'],comments:[{id:'c1',author:'marina',text:'Vamos pra cima! ✨'}]},{id:'first',author:'gabriela',text:'Primeiro mês de treinos concluído! Mais disposição, mais confiança e uma rotina que finalmente faz sentido. Orgulhosa de cada pequeno passo. ✨',image:'',date:ago(2),likes:['marina','lucas'],comments:[]},{id:'second',author:'lucas',text:'Treino de hoje pago! A melhor competição é com a versão de ontem de você mesmo. Quem mais já treinou hoje?',image:'',date:ago(3),likes:['gabriela'],comments:[]}]};
}
function str(x:unknown,max=2000){return typeof x==='string'?x.trim().slice(0,max):'';}
function number(x:unknown,min:number,max:number,label:string){const n=Number(x);if(!Number.isFinite(n)||n<min||n>max)throw Error('Informe '+label+' válido.');return n;}
export function applyAction(state:State,a:Action):State{
const role=a.role==='personal'?'personal':'student';const actor=role==='personal'?'personal':state.currentStudentId;
const student=state.students.find(s=>s.id===(role==='personal'&&a.studentId?a.studentId:state.currentStudentId));
const manager=()=>{if(role!=='personal')throw Error('Apenas o personal pode fazer esta alteração.');};
if(a.type==='checkout'){const name=str(a.name,80),email=str(a.email,150);if(name.length<3||!/^\S+@\S+\.\S+$/.test(email))throw Error('Informe nome e e-mail válidos.');const existing=state.students.find(s=>s.email.toLowerCase()===email.toLowerCase());if(existing){state.currentStudentId=existing.id;return state;}const id=crypto.randomUUID();state.students.push({id,name,email,goal:'Definir objetivo',joinedAt:ago(0),submittedAt:null,anamnese:{},planApproved:false,plan:[],measurements:[],checkins:[],active:true});state.currentStudentId=id;return state;}
if(!student)throw Error('Aluno não encontrado.');
if(a.type==='switchStudent'){manager();const target=state.students.find(s=>s.id===a.studentId);if(!target)throw Error('Aluno não encontrado.');state.currentStudentId=target.id;}
else if(a.type==='assessment'){if(student.submittedAt)throw Error('Anamnese já enviada. Consulte seu personal para atualizar o plano.');const answers=a.answers as Record<string,string>;if(!answers||a.consent!==true)throw Error('Confirme o consentimento para continuar.');number(answers.age,18,100,'idade');number(answers.height,100,250,'altura');number(answers.weight,30,350,'peso');number(answers.days,1,7,'frequência');if(!str(answers.goal)||!str(answers.experience))throw Error('Preencha objetivo e experiência.');student.anamnese=Object.fromEntries(Object.entries(answers).slice(0,12).map(([k,v])=>[str(k,40),str(v,1000)]));student.goal=str(answers.goal,80);student.submittedAt=ago(0);student.planApproved=true;student.plan=structuredClone(defaultPlan);student.measurements=[{date:dateKey(),weight:Number(answers.weight),waist:0}];}
else if(a.type==='profile'){const name=str(a.name,80);if(name.length<3)throw Error('Informe seu nome.');student.name=name;student.goal=str(a.goal,80)||student.goal;}
else if(a.type==='measure'){const weight=number(a.weight,30,350,'peso'),waist=number(a.waist||0,0,250,'cintura');const date=dateKey();student.measurements=student.measurements.filter(m=>m.date!==date);student.measurements.push({date,weight,waist});}
else if(a.type==='checkin'){if(planStatus(student)!=='ready')throw Error('Seu plano ainda está em preparação.');if(!student.plan.some(w=>w.id===a.workout))throw Error('Treino não encontrado.');const date=dateKey();if(student.checkins.some(c=>c.date===date))throw Error('O treino de hoje já foi registrado.');student.checkins.push({date,workout:str(a.workout,50)});}
else if(a.type==='plan'){manager();if(!student.submittedAt)throw Error('Aguarde o envio da anamnese.');const plan=a.plan as Workout[];if(!Array.isArray(plan)||!plan.length||plan.length>7)throw Error('Adicione pelo menos um treino.');student.plan=plan.map((w,i)=>{if(!str(w.title)||!Array.isArray(w.exercises)||!w.exercises.length||w.exercises.length>20)throw Error('Preencha o título e os exercícios.');return {id:w.id||String(i),title:str(w.title,80),focus:str(w.focus,100),duration:number(w.duration,5,180,'duração'),exercises:w.exercises.map(e=>{if(!str(e.name)||!str(e.sets)||!str(e.reps))throw Error('Preencha todos os exercícios.');return {name:str(e.name,120),sets:str(e.sets,20),reps:str(e.reps,30),rest:str(e.rest,30)};})};});student.planApproved=a.approved===true;}
else if(a.type==='releaseDemo'){manager();if(!student.submittedAt)throw Error('Aguarde a anamnese.');student.demoReleased=true;student.planApproved=true;if(!student.plan.length)student.plan=structuredClone(defaultPlan);}
else if(a.type==='active'){manager();student.active=!student.active;}
else if(a.type==='post'){const text=str(a.text),image=str(a.image,500);if(!text&&!image)throw Error('Escreva uma atualização ou adicione uma foto.');if(image&&!/^\/api\/photos\/[a-f0-9-]+$/.test(image))throw Error('Foto inválida.');state.posts.unshift({id:crypto.randomUUID(),author:actor,text,image,date:ago(0),likes:[],comments:[]});}
else if(['like','comment','deletePost'].includes(a.type)){const post=state.posts.find(p=>p.id===a.postId);if(!post)throw Error('Publicação não encontrada.');if(a.type==='like'){post.likes=post.likes.includes(actor)?post.likes.filter(id=>id!==actor):[...post.likes,actor];}if(a.type==='comment'){const text=str(a.text,500);if(!text)throw Error('Escreva seu comentário.');post.comments.push({id:crypto.randomUUID(),author:actor,text});}if(a.type==='deletePost'){if(actor!==post.author&&role!=='personal')throw Error('Você não pode excluir esta publicação.');state.posts=state.posts.filter(p=>p.id!==post.id);}}
else throw Error('Ação inválida.');
return state;
}
