import {createHash,randomUUID,timingSafeEqual} from 'node:crypto';
import {COMMERCE_CATALOG,commerceError,exactFields,purchaseSnapshot,checkoutBody,cents} from './catalog.mjs';

const hash=value=>createHash('sha256').update(value).digest();
const id=value=>typeof value==='string'&&value.length>0&&value.length<=200&&!/[\x00-\x20]/.test(value)?value:null;
const adverseTypes=Object.freeze({PAYMENT_REFUND_IN_PROGRESS:'refund_pending',PAYMENT_PARTIALLY_REFUNDED:'partially_refunded',PAYMENT_REFUNDED:'refunded',PAYMENT_CHARGEBACK_REQUESTED:'chargeback',PAYMENT_CHARGEBACK_DISPUTE:'chargeback',PAYMENT_AWAITING_CHARGEBACK_REVERSAL:'chargeback',PAYMENT_RECEIVED_IN_CASH_UNDONE:'review'});
const checkoutTypes=['CHECKOUT_CREATED','CHECKOUT_PAID','CHECKOUT_CANCELED','CHECKOUT_EXPIRED'];
const paymentTypes=['PAYMENT_CREATED','PAYMENT_CONFIRMED','PAYMENT_RECEIVED','PAYMENT_UPDATED','PAYMENT_AUTHORIZED','PAYMENT_AWAITING_RISK_ANALYSIS','PAYMENT_APPROVED_BY_RISK_ANALYSIS','PAYMENT_REPROVED_BY_RISK_ANALYSIS','PAYMENT_CREDIT_CARD_CAPTURE_REFUSED','PAYMENT_OVERDUE','PAYMENT_DELETED','PAYMENT_RESTORED',...Object.keys(adverseTypes)];

// Opt-in local runtime only; never a production adapter.
// resolvePrincipal/proveIdentity must come from trusted session/token verification,
// never request fields, matching email or successUrl. Tests inject fictitious proofs.
export function localCommerce({store,client,resolvePrincipal,proveIdentity,resolveAdmin=async()=>null,webhookToken,publicOrigin,monthlyMode=null,installmentLimits={},now=Date.now,production=false}){
 if(production||client?.kind!=='mock'||client.scope?.environment!=='mock'||typeof resolvePrincipal!=='function'||typeof proveIdentity!=='function'||typeof webhookToken!=='string'||!webhookToken.startsWith('mock-only-')||webhookToken.length<32||webhookToken.length>255)throw commerceError(503,'Comércio disponível somente em testes locais, com provas fictícias.');
 const {environment,accountId}=client.scope;
 const lock=async(table,key,value)=>{if(store.kind==='postgres')await store.get('SELECT '+key+' FROM '+table+' WHERE '+key+'=? FOR UPDATE',value);};
 async function buyer(credential){const principal=await resolvePrincipal(credential);if(!principal||!id(principal.buyerId)||!id(principal.orgId))throw commerceError(401,'Sessão de compra inválida.');const row=await store.get('SELECT * FROM commerce_buyers WHERE id=? AND org_id=? AND environment=? AND account_id=? AND active=1',principal.buyerId,principal.orgId,environment,accountId);if(!row)throw commerceError(403,'Compra indisponível.');return row;}
 async function ownOrder(credential,orderId){const b=await buyer(credential);const row=await store.get('SELECT * FROM commerce_orders WHERE id=? AND buyer_id=? AND org_id=?',orderId,b.id,b.org_id);if(!row)throw commerceError(404,'Pedido indisponível.');return row;}
 async function admin(credential){const principal=await resolveAdmin(credential);if(!principal?.userId)throw commerceError(403,'Administração obrigatória.');const user=await store.get('SELECT * FROM users WHERE id=? AND active=1 AND role=?',principal.userId,'admin');if(!user)throw commerceError(403,'Administração obrigatória.');return user;}
 const task=(o,kind)=>store.run('INSERT INTO commerce_tasks VALUES (?,?,?,?,?,?) ON CONFLICT(order_id,kind) DO NOTHING',randomUUID(),o.id,o.org_id,kind,'pending',now());
 const audit=(o,event)=>store.run('INSERT INTO commerce_audit VALUES (?,?,?,?,?)',randomUUID(),o.id,o.org_id,event,now());
 async function orderForEvent(e){let o;if(e.checkout_id)o=await store.get('SELECT * FROM commerce_orders WHERE checkout_id=? AND environment=? AND account_id=?',e.checkout_id,environment,accountId);if(!o&&e.payment_id)o=await store.get('SELECT o.* FROM commerce_orders o JOIN commerce_payments p ON p.order_id=o.id WHERE p.payment_id=? AND p.environment=? AND p.account_id=?',e.payment_id,environment,accountId);if(!o&&e.external_reference)o=await store.get('SELECT * FROM commerce_orders WHERE external_reference=? AND environment=? AND account_id=?',e.external_reference,environment,accountId);if(o&&(e.customer_id&&e.customer_id!==o.customer_id||e.external_reference&&e.external_reference!==o.external_reference||e.checkout_id&&o.checkout_id&&e.checkout_id!==o.checkout_id))return null;return o;}
 async function changeStatus(o,status,adverse=false){if(o.status===status&&(!adverse||o.adverse_seen))return;await store.run('UPDATE commerce_orders SET status=?,adverse_seen=?,revision=revision+1,updated_at=? WHERE id=?',status,adverse||o.adverse_seen?1:0,now(),o.id);await audit(o,'commerce.payment.'+status);}
 async function heldByAdverseEvent(o){const rows=await store.all('SELECT * FROM commerce_events WHERE environment=? AND account_id=?',environment,accountId),payments=await store.all('SELECT payment_id FROM commerce_payments WHERE order_id=?',o.id),ids=new Set(payments.map(p=>p.payment_id));return rows.some(e=>adverseTypes[e.event_type]&&(e.checkout_id===o.checkout_id&&o.checkout_id||e.external_reference===o.external_reference||ids.has(e.payment_id))&&(!e.customer_id||e.customer_id===o.customer_id));}
 async function grantOnce(o){const result=await store.run('INSERT INTO commerce_entitlements VALUES (?,?,?,?,?,?,?) ON CONFLICT(order_id) DO NOTHING',o.id,o.buyer_id,o.org_id,'payment',1,'policy-pending',now());if(!result.changes)return;const b=await store.get('SELECT * FROM commerce_buyers WHERE id=?',o.buyer_id);await task(o,b.identity_verified_at!==null?'onboarding':'verify-identity');await audit(o,'commerce.onboarding.authorized');}
 async function paidSnapshot(o){let rows=await client.paymentsByCheckout(o.checkout_id);if(!rows.length)return {status:'pending',payments:[]};
  const groups=new Set(rows.map(p=>p.installment).filter(Boolean));if(groups.size>1)throw commerceError(409,'Parcelamento financeiro divergente.');if(groups.size){if(o.billing_type!=='CREDIT_CARD'||!o.max_installments)throw commerceError(409,'Parcelamento não autorizado no pedido.');const group=[...groups][0];if(rows.some(p=>p.installment!==group))throw commerceError(409,'Cobranças misturadas.');const complete=await client.paymentsByInstallment(group);if(complete.length<2||complete.length>o.max_installments||complete.some(p=>p.installment!==group)||rows.some(p=>!complete.some(c=>c.id===p.id)))throw commerceError(409,'Parcelamento incompleto.');const numbers=new Set(complete.map(p=>p.installmentNumber));if(numbers.size!==complete.length||complete.some(p=>!Number.isInteger(p.installmentNumber)||p.installmentNumber<1||p.installmentNumber>complete.length))throw commerceError(409,'Sequência de parcelas incompleta.');rows=complete;}
  const seen=new Set();let total=0;for(const p of rows){if(!id(p.id)||seen.has(p.id)||p.customer!==o.customer_id||p.externalReference!==o.external_reference||p.billingType!==o.billing_type||p.deleted===true)throw commerceError(409,'Vínculo da cobrança divergente.');seen.add(p.id);total+=cents(p.value);}
  if(total!==o.amount_cents)throw commerceError(409,'Total bruto divergente.');
  if(rows.some(p=>p.refunds?.length||p.chargeback||['REFUNDED','REFUND_REQUESTED','REFUND_IN_PROGRESS','PARTIALLY_REFUNDED','CHARGEBACK_REQUESTED','CHARGEBACK_DISPUTE','AWAITING_CHARGEBACK_REVERSAL'].includes(p.status)))return {status:'review',adverse:true,payments:rows.map(p=>p.id)};
  const paid=rows.every(p=>o.billing_type==='PIX'?p.status==='RECEIVED':['CONFIRMED','RECEIVED'].includes(p.status));return {status:paid?'paid':rows.some(p=>p.status==='OVERDUE')?'overdue':'pending',payments:rows.map(p=>p.id)};
 }
 async function applySnapshot(orderId,snapshot,event=null){return store.transaction(async()=>{await lock('commerce_orders','id',orderId);const o=await store.get('SELECT * FROM commerce_orders WHERE id=? AND environment=? AND account_id=?',orderId,environment,accountId);if(!o)throw commerceError(404,'Pedido indisponível.');
  if(event?.payment_id&&!snapshot.payments?.includes(event.payment_id))throw commerceError(409,'Cobrança notificada não pertence ao checkout reconciliado.');
  for(const paymentId of snapshot.payments||[]){const link=await store.get('SELECT order_id FROM commerce_payments WHERE environment=? AND account_id=? AND payment_id=?',environment,accountId,paymentId);if(link&&link.order_id!==o.id){await changeStatus(o,'review',true);await task(o,'financial-review');return;}}
  for(const paymentId of snapshot.payments||[])await store.run('INSERT INTO commerce_payments VALUES (?,?,?,?) ON CONFLICT(environment,account_id,payment_id) DO NOTHING',environment,accountId,paymentId,o.id);
  if(event&&adverseTypes[event.event_type]){await changeStatus(o,adverseTypes[event.event_type],true);await task(o,'financial-review');return;}
  if(o.adverse_seen||snapshot.adverse||await heldByAdverseEvent(o)){await changeStatus(o,o.adverse_seen?o.status:'review',true);await task(o,'financial-review');return;}
  if(snapshot.status==='paid'&&['canceled','expired','review'].includes(o.status)){await changeStatus(o,'review',true);await task(o,'financial-review');return;}
  // A delayed pending/overdue notification must not undo a confirmed payment.
  if(o.status==='paid'&&snapshot.status!=='paid')return;
  await changeStatus(o,snapshot.status);if(snapshot.status==='paid')await grantOnce(o);
 });}
 async function reconcileRow(o,event=null){if(!o.checkout_id)throw commerceError(409,'Checkout inconclusivo; reconciliar antes de recriar.');let snapshot;try{snapshot=await paidSnapshot(o);}catch(error){if(error.status!==409)throw error;snapshot={status:'review',adverse:true,payments:[]};}await applySnapshot(o.id,snapshot,event);}
 async function createOrder(credential,body,key){exactFields(body,['sku','billingType']);if(!id(key))throw commerceError(400,'Chave de pedido obrigatória.');const snapshot=purchaseSnapshot(body.sku,{monthlyMode}),maxInstallments=body.billingType==='CREDIT_CARD'?(installmentLimits[body.sku]??null):null;
  const fingerprint=hash(JSON.stringify({snapshot,billingType:body.billingType,maxInstallments})).toString('hex');return store.transaction(async()=>{const first=await buyer(credential);await lock('commerce_buyers','id',first.id);const b=await buyer(credential);const old=await store.get('SELECT * FROM commerce_orders WHERE buyer_id=? AND idempotency_key=?',b.id,key);if(old){if(old.request_hash!==fingerprint)throw commerceError(409,'Chave reutilizada para outra compra.');return old;}
   if(await store.get('SELECT id FROM commerce_orders WHERE buyer_id=? AND checkout_state IN (?,?)',b.id,'creating','unknown'))throw commerceError(409,'Compra anterior inconclusiva; reconciliar antes de iniciar outra cobrança.');
   const orderId=randomUUID(),o={id:orderId,customer_id:b.customer_id,amount_cents:snapshot.amountCents,snapshot:JSON.stringify(snapshot),external_reference:orderId};checkoutBody(o,{publicOrigin,billingType:body.billingType,maxInstallmentCount:maxInstallments});
   await store.run('INSERT INTO commerce_orders(id,org_id,buyer_id,environment,account_id,customer_id,idempotency_key,request_hash,external_reference,amount_cents,currency,snapshot,billing_type,max_installments,checkout_state,status,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',orderId,b.org_id,b.id,environment,accountId,b.customer_id,key,fingerprint,orderId,snapshot.amountCents,'BRL',o.snapshot,body.billingType,maxInstallments,'new','pending',now(),now());await audit({...o,org_id:b.org_id},'commerce.order.created');return store.get('SELECT * FROM commerce_orders WHERE id=?',orderId);
  });}
 async function createCheckout(credential,orderId){let claimed=false;await store.transaction(async()=>{const initialBuyer=await buyer(credential);await lock('commerce_buyers','id',initialBuyer.id);const first=await ownOrder(credential,orderId);await lock('commerce_orders','id',first.id);const o=await ownOrder(credential,orderId);if(o.checkout_state==='ready')return;if(o.checkout_state!=='new'||o.status!=='pending')throw commerceError(409,'Checkout inconclusivo ou encerrado; não recriar cobrança.');if(await store.get('SELECT id FROM commerce_orders WHERE buyer_id=? AND id<>? AND checkout_state IN (?,?)',o.buyer_id,o.id,'creating','unknown'))throw commerceError(409,'Compra anterior inconclusiva; reconciliar antes de iniciar outra cobrança.');await store.run('UPDATE commerce_orders SET checkout_state=?,updated_at=? WHERE id=?','creating',now(),o.id);claimed=true;});if(!claimed)return ownOrder(credential,orderId);
  const o=await ownOrder(credential,orderId);try{const result=await client.createCheckout(checkoutBody(o,{publicOrigin,billingType:o.billing_type,maxInstallmentCount:o.max_installments}));await store.transaction(async()=>{await lock('commerce_orders','id',o.id);const current=await store.get('SELECT * FROM commerce_orders WHERE id=?',o.id);if(current.checkout_id&&current.checkout_id!==result.id)throw commerceError(409,'Checkout divergente.');await store.run('UPDATE commerce_orders SET checkout_id=?,checkout_state=?,updated_at=? WHERE id=?',result.id,'ready',now(),o.id);await audit(o,'commerce.checkout.created');});}catch{await store.transaction(async()=>{await lock('commerce_orders','id',o.id);await store.run('UPDATE commerce_orders SET checkout_state=?,updated_at=? WHERE id=? AND checkout_id IS NULL','unknown',now(),o.id);});throw commerceError(503,'Criação inconclusiva. Não repetir; aguardando reconciliação.');}return ownOrder(credential,orderId);}
 async function acceptWebhook({headers,rawBody}){const token=headers?.['asaas-access-token'];if(typeof token!=='string'||token.length>255||!timingSafeEqual(hash(token),hash(webhookToken)))throw commerceError(401,'Notificação não autenticada.');if(typeof rawBody!=='string'||Buffer.byteLength(rawBody)>131072)throw commerceError(413,'Notificação excedeu limite.');let payload;try{payload=JSON.parse(rawBody);}catch{throw commerceError(400,'Notificação inválida.');}if(!id(payload?.id)||!id(payload?.event)||! /^[A-Z_]+$/.test(payload.event)||payload.account?.id!==accountId)throw commerceError(400,'Escopo da notificação inválido.');
  // Strict allowlist: card tokens, customerData, URLs and all raw payload are discarded.
  const c=payload.checkout,p=payload.payment,e={eventId:payload.id,eventType:payload.event,checkoutId:id(c?.id),paymentId:id(p?.id),reference:id(c?.externalReference??p?.externalReference),customerId:id(c?.customer??p?.customer)};
  return store.transaction(async()=>{const inserted=await store.run('INSERT INTO commerce_events(environment,account_id,event_id,event_type,checkout_id,payment_id,external_reference,customer_id,state,received_at) VALUES (?,?,?,?,?,?,?,?,?,?) ON CONFLICT(environment,account_id,event_id) DO NOTHING',environment,accountId,e.eventId,e.eventType,e.checkoutId,e.paymentId,e.reference,e.customerId,'pending',now());return {status:200,received:true,duplicate:inserted.changes===0};});}
 async function processNext({exclude=new Set()}={}){let claimed;await store.transaction(async()=>{const rows=await store.all('SELECT * FROM commerce_events WHERE environment=? AND account_id=? AND (state=? OR (state=? AND lease_until<=?)) ORDER BY received_at,event_id LIMIT 20',environment,accountId,'pending','processing',now());for(const e of rows){if(exclude.has(e.event_id))continue;const result=await store.run('UPDATE commerce_events SET state=?,lease_until=?,attempts=attempts+1 WHERE environment=? AND account_id=? AND event_id=? AND state=? AND attempts=?','processing',now()+30000,environment,accountId,e.event_id,e.state,e.attempts);if(result.changes){claimed={...e,attempts:e.attempts+1,lease_until:now()+30000};break;}}});if(!claimed)return false;exclude.add(claimed.event_id);
  let state='done';try{if([...checkoutTypes,...paymentTypes].includes(claimed.event_type)){let o=await orderForEvent(claimed);if(!o)throw commerceError(409,'Notificação sem vínculo comprovado.');
    if(claimed.event_type==='CHECKOUT_CREATED'&&!o.checkout_id){if(!['unknown','creating'].includes(o.checkout_state)||claimed.external_reference!==o.external_reference||claimed.customer_id!==o.customer_id||!claimed.checkout_id)throw commerceError(409,'Recuperação de checkout não comprovada.');await store.transaction(async()=>{await lock('commerce_orders','id',o.id);const current=await store.get('SELECT * FROM commerce_orders WHERE id=?',o.id);if(current.checkout_id&&current.checkout_id!==claimed.checkout_id)throw commerceError(409,'Checkout divergente.');await store.run('UPDATE commerce_orders SET checkout_id=?,checkout_state=?,updated_at=? WHERE id=?',claimed.checkout_id,'ready',now(),o.id);});o=await store.get('SELECT * FROM commerce_orders WHERE id=?',o.id);}
    if(['CHECKOUT_CANCELED','CHECKOUT_EXPIRED'].includes(claimed.event_type)){await store.transaction(async()=>{await lock('commerce_orders','id',o.id);const current=await store.get('SELECT * FROM commerce_orders WHERE id=?',o.id);if(current.status!=='paid'&&!current.adverse_seen)await changeStatus(current,claimed.event_type==='CHECKOUT_CANCELED'?'canceled':'expired');});}
    else if(claimed.event_type!=='CHECKOUT_CREATED')await reconcileRow(o,claimed);
   }}catch(error){state=error.status===409||claimed.attempts>=5?'review':'pending';if(state==='review'){const o=await orderForEvent(claimed);if(o)await task(o,'financial-review');}}
  await store.run('UPDATE commerce_events SET state=?,lease_until=NULL WHERE environment=? AND account_id=? AND event_id=? AND state=? AND lease_until=?',state,environment,accountId,claimed.event_id,'processing',claimed.lease_until);return true;
 }
 async function reconcile(credential,orderId){await reconcileRow(await ownOrder(credential,orderId));return summary(credential,orderId);}
 async function verifyIdentity(credential,proof){return store.transaction(async()=>{const evidence=await proveIdentity(proof);const first=await buyer(credential);await lock('commerce_buyers','id',first.id);const b=await buyer(credential);if(!evidence||evidence.buyerId!==b.id||evidence.orgId!==b.org_id||!id(evidence.userId))throw commerceError(403,'Identidade não comprovada.');const u=await store.get('SELECT * FROM users WHERE id=? AND org_id=? AND active=1 AND role=?',evidence.userId,b.org_id,'student');if(!u||b.user_id&&b.user_id!==u.id)throw commerceError(403,'Identidade incompatível.');await store.run('UPDATE commerce_buyers SET user_id=?,identity_verified_at=? WHERE id=?',u.id,b.identity_verified_at??now(),b.id);const orders=await store.all('SELECT o.* FROM commerce_orders o JOIN commerce_entitlements e ON e.order_id=o.id WHERE o.buyer_id=? AND e.onboarding_authorized=1',b.id);for(const o of orders){await store.run('UPDATE commerce_tasks SET state=? WHERE order_id=? AND kind=?','done',o.id,'verify-identity');await task(o,'onboarding');}return {verified:true};});}
 async function summary(credential,orderId){const o=await ownOrder(credential,orderId),b=await buyer(credential),e=await store.get('SELECT * FROM commerce_entitlements WHERE order_id=?',o.id);return {orderId:o.id,plan:JSON.parse(o.snapshot),status:o.status,checkoutState:o.checkout_state,identityVerified:b.identity_verified_at!==null,onboardingAuthorized:e?.onboarding_authorized===1&&b.identity_verified_at!==null&&o.status!=='refunded',financialReview:o.adverse_seen===1,periodPolicyPending:true,protocolPublished:false,externalPaymentPerformed:false};}
 async function interest(credential,body){exactFields(body,['sku']);if(!COMMERCE_CATALOG.some(p=>p.id===body.sku&&p.kind==='interest'))throw commerceError(400,'Plano de interesse inválido.');return store.transaction(async()=>{const b=await buyer(credential);await store.run('INSERT INTO commerce_interest VALUES (?,?,?,?,?) ON CONFLICT(buyer_id,sku) DO NOTHING',randomUUID(),b.id,b.org_id,body.sku,now());return {recorded:true,charged:false};});}
 async function pauseOnboarding(credential,orderId,body){exactFields(body,['confirmed']);if(body.confirmed!==true)throw commerceError(400,'Confirme a pausa administrativa.');return store.transaction(async()=>{const first=await admin(credential);await store.lockActor(first.id);const actor=await admin(credential);await lock('commerce_orders','id',orderId);const o=await store.get('SELECT * FROM commerce_orders WHERE id=? AND org_id=?',orderId,actor.org_id);if(!o)throw commerceError(404,'Pedido indisponível.');const result=await store.run('UPDATE commerce_entitlements SET onboarding_authorized=0 WHERE order_id=? AND onboarding_authorized=1',o.id);if(result.changes)await audit(o,'commerce.onboarding.paused');return {paused:true};});}
 async function crm(credential){const actor=await admin(credential),orders=await store.all('SELECT id,buyer_id,status,amount_cents,currency,snapshot,adverse_seen,created_at FROM commerce_orders WHERE org_id=? ORDER BY created_at,id',actor.org_id),tasks=await store.all('SELECT order_id,kind,state,created_at FROM commerce_tasks WHERE org_id=? ORDER BY created_at,id',actor.org_id),interests=await store.all('SELECT buyer_id,sku,created_at FROM commerce_interest WHERE org_id=? ORDER BY created_at,id',actor.org_id);return {orders:orders.map(o=>({orderId:o.id,buyerId:o.buyer_id,status:o.status,amountCents:o.amount_cents,currency:o.currency,plan:JSON.parse(o.snapshot).sku,financialReview:o.adverse_seen===1,createdAt:o.created_at})),tasks,interests};}
 return {createOrder,createCheckout,acceptWebhook,processNext,reconcile,verifyIdentity,summary,interest,pauseOnboarding,crm};
}
